export const stopDialogFieldIds = {
  activity: "stop-activity",
  activityType: "stop-activity-type",
  bookingRef: "stop-booking-ref",
  budgetNote: "stop-budget-note",
  costNote: "stop-cost-note",
  day: "stop-day",
  detail: "stop-detail",
  destination: "stop-destination",
  path: "stop-path",
  derivedDuration: "stop-derived-duration",
  endOffsetDays: "stop-end-offset-days",
  endTime: "stop-end-time",
  entryWindow: "stop-entry-window",
  meal: "stop-meal",
  meetingPoint: "stop-meeting-point",
  mode: "stop-mode",
  mustSee: "stop-must-see",
  mustTry: "stop-must-try",
  mapLink: "stop-map-link",
  note: "stop-note",
  origin: "stop-origin",
  place: "stop-place",
  provider: "stop-provider",
  reservationName: "stop-reservation-name",
  startTime: "stop-start-time",
  targetItems: "stop-target-items",
  taxRefundNote: "stop-tax-refund-note",
  ticketRef: "stop-ticket-ref",
  transportation: "stop-transportation",
  itemKind: "stop-item-kind",
  timeMode: "stop-time-mode",
  isPlanBlock: "stop-is-plan-block",
  status: "stop-status",
  priority: "stop-priority",
};

export {
  buildStructuredStopDetails,
  detailKeysForType,
  detailTypeFromActivityType,
  detailTypeFromItem,
  emptyStopDetailValues,
  itemKindForStopDetailType,
  readStringDetail,
  resolveStopActivityType,
  stopDetailLabels,
  stopDetailTypeFromItem,
  stopDialogDetailTypeOptions,
  stopDialogDetailTypeToActivityType,
  structuredStopDetailValues,
} from "./stop-dialog-details";

export type {
  StopDetailType,
  StopDetailValues,
} from "./stop-dialog-details";

export {
  addMinutesToTime,
  durationBetweenTimes,
  endOffsetDaysBetweenTimes,
  endWindowFromDuration,
  parseRouteActivity,
  parseTimeRange,
  timeToMinutes,
} from "@/src/features/itinerary/domain/stop-time";
