import {
  accountAvatarClassName,
  accountDashboardClassName,
  accountDeviceListClassName,
  accountDeviceRowClassName,
  accountEmptyClassName,
  accountProfileRowClassName,
  accountSettingsFormClassName,
  accountSettingsGridClassName,
  accountStatGridClassName,
  accountTwoColClassName,
  portalContentClassName,
  portalFeatureCardClassName,
  portalHistoryCardClassName,
  portalNewTripCardClassName,
  portalProfileCardClassName,
  portalSectionToplineClassName,
  portalSettingsCardClassName,
  settingsProfilePreviewClassName,
  tripBuilderTopbarClassName,
} from "../account-access-panel-layout";
import { accountStepSummaryClassName } from "../email-login/account-email-login-styles";

export const accountPortalDashboardClassNames = {
  avatar: accountAvatarClassName,
  dashboard: accountDashboardClassName,
  deviceList: accountDeviceListClassName,
  deviceRow: accountDeviceRowClassName,
  empty: accountEmptyClassName,
  featureCard: portalFeatureCardClassName,
  historyCard: portalHistoryCardClassName,
  newTripCard: portalNewTripCardClassName,
  portalContent: portalContentClassName,
  profileCard: portalProfileCardClassName,
  profileRow: accountProfileRowClassName,
  sectionTopline: portalSectionToplineClassName,
  settingsCard: portalSettingsCardClassName,
  settingsForm: accountSettingsFormClassName,
  settingsGrid: accountSettingsGridClassName,
  settingsProfilePreview: settingsProfilePreviewClassName,
  statGrid: accountStatGridClassName,
  stepSummary: accountStepSummaryClassName,
  tripBuilderTopbar: tripBuilderTopbarClassName,
  twoCol: accountTwoColClassName,
};
