export const enPhotoCopy = {
  pageLabel: "Photos & Albums",
  title: "Photos & Albums",
  albumLinks: (count: number) => `${count} album links`,
  canAddAlbums: "Can add albums",
  readOnly: "Read-only",
  summaryLabel: "Photo album summary",
  savedDestinations: "Saved destinations",
  albums: (count: number) => `${count} albums`,
  sharedUploads: "Shared uploads",
  collaborative: (count: number) => `${count} collaborative`,
  uploadRequests: "Upload requests",
  requests: (count: number) => `${count} requests`,
  needsAccessNote: "Needs access note",
  missing: (count: number) => `${count} missing`,
  providersLabel: "Photo providers",
  providerCount: (label: string, count: number) => `${label}, ${count} albums`,
  providerHint: (count: number) => `Photos stay with the linked provider · ${count} visible albums`,
  addAlbum: "Add album",
  albumLinksLabel: "Photo album links",
  emptyTitle: "No albums in this view",
  emptyDetail: "Add a Google Photos album, Drive folder, Dropbox request, or another shared photo destination.",
  deleteAlbum: "Delete album",
  deletePrompt: (title: string) => `Delete ${title}? The external provider album will stay in place.`,
  cancel: "Cancel",
  selectAlbum: (title: string) => `Select ${title}`,
  coverFor: (title: string) => `Cover for ${title}`,
  defaultAccessNote: "Add access note so the group knows how to use this album.",
  noOwner: "No owner",
  tripLevel: "Trip-level",
  unsafeLinkBlocked: "Unsafe link blocked",
  openAlbumTitle: (title: string) => `Open ${title}`,
  openBlocked: "Open blocked",
  editAlbum: "Edit album",
  inspectorLabel: "Photo album inspector",
  selectHint: "Select an album to see access details.",
  externalProviderNote: "External provider permissions control real access.",
  blockedLink: "Blocked link",
  copy: "Copy",
  openAlbum: "Open album",
  access: "Access",
  noAccessNote: "No access note yet.",
  owner: "Owner",
  noOwnerAssigned: "No owner assigned",
  createdBy: (name: string) => `Created by ${name}`,
  relatedStops: "Related stops",
  addAlbumDialog: "Add album",
  editAlbumDialog: "Edit album",
  close: "Close",
  titleField: "Title",
  providerField: "Provider",
  accessField: "Access",
  ownerField: "Owner",
  albumLinkField: "Album link",
  dayField: "Day",
  descriptionField: "Description",
  accessNoteField: "Access note",
  relatedItinerary: "Related itinerary",
  saveAlbum: "Save album",
  providers: {
    all: "All albums",
    google_photos: "Google Photos",
    icloud: "iCloud",
    google_drive: "Google Drive",
    dropbox: "Dropbox",
    onedrive: "OneDrive",
    custom: "Custom",
  },
  accessLabels: {
    view_only: "View only",
    collaborative: "Collaborative",
    upload_request: "Upload request",
  },
} as const;
