import type { ItineraryItem } from "./types";

interface CreateSeedItineraryItemsInput {
  mainPlanId: string;
  tripId: string;
  updatedAt: string;
}

export function createSeedItineraryItems({
  mainPlanId,
  tripId,
  updatedAt,
}: CreateSeedItineraryItemsInput): ItineraryItem[] {
  function item(
    input: Omit<ItineraryItem, "tripId" | "planVariantId" | "createdBy" | "updatedAt" | "version" | "details"> &
      Partial<Pick<ItineraryItem, "planVariantId" | "version" | "details">>,
  ): ItineraryItem {
    return {
      tripId,
      planVariantId: input.planVariantId ?? mainPlanId,
      createdBy: "member-aom",
      updatedAt,
      version: input.version ?? 1,
      ...input,
      details: input.details ?? {},
    };
  }

  return [
    item({
      id: "item-flight-bkk-hkg",
      day: "2026-06-18",
      sortOrder: 100,
      startTime: "09:00",
      activity: "เดินทางออกจากกรุงเทพฯ (BKK)",
      activityType: "travel",
      place: "Bangkok → Hong Kong",
      linkLabel: "QR349",
      mapLink: "https://maps.google.com/?q=Bangkok+Airport",
      coordinates: { lat: 13.69, lng: 100.7501 },
      durationMinutes: null,
      transportation: "CT ✓ → HKG",
      note: "เตรียมพาสปอร์ตและเอกสารเข้าเมืองไว้ในกระเป๋าถือ",
    }),
    item({
      id: "item-arrive-hkg",
      day: "2026-06-18",
      sortOrder: 200,
      startTime: "12:55",
      activity: "ถึง Hong Kong International Airport",
      activityType: "travel",
      place: "Hong Kong International Airport",
      linkLabel: "HKG",
      mapLink: "https://maps.google.com/?q=Hong+Kong+International+Airport",
      coordinates: { lat: 22.308, lng: 113.9185 },
      durationMinutes: null,
      transportation: "",
      note: "รอรับกระเป๋าและซื้อ Octopus Card ถ้ายังไม่มี",
    }),
    item({
      id: "item-airport-express",
      day: "2026-06-18",
      sortOrder: 300,
      startTime: "14:00",
      activity: "Airport Express ไป Kowloon",
      activityType: "travel",
      place: "Kowloon Station",
      linkLabel: "Airport Express",
      mapLink: "https://maps.google.com/?q=Kowloon+Station",
      coordinates: { lat: 22.3048, lng: 114.1615 },
      durationMinutes: 24,
      transportation: "Airport Express",
      note: "เช็คเวลา shuttle หรือเรียกแท็กซี่ต่อเข้าโรงแรม",
    }),
    item({
      id: "item-hotel-checkin",
      day: "2026-06-18",
      sortOrder: 400,
      startTime: "14:30",
      activity: "เช็คอินที่โรงแรม (Tsim Sha Tsui)",
      activityType: "stay",
      place: "The Elements / Tsim Sha Tsui",
      linkLabel: "โรงแรม",
      mapLink: "https://maps.google.com/?q=Tsim+Sha+Tsui+hotel",
      coordinates: { lat: 22.2993, lng: 114.1722 },
      durationMinutes: 30,
      transportation: "แท็กซี่",
      note: "ฝากกระเป๋าก่อนออกไปเดินริมอ่าว",
    }),
    item({
      id: "item-avenue-stars",
      day: "2026-06-18",
      sortOrder: 500,
      startTime: "16:00",
      activity: "Avenue of Stars (星光大道)",
      activityType: "attraction",
      place: "Tsim Sha Tsui promenade",
      linkLabel: "แผนที่",
      mapLink: "https://maps.google.com/?q=Avenue+of+Stars+Hong+Kong",
      coordinates: { lat: 22.2931, lng: 114.1743 },
      durationMinutes: 60,
      transportation: "เดิน",
      note: "จุดถ่ายรูปริมอ่าว เหมาะสำหรับดูแสงเย็น",
    }),
    item({
      id: "item-symphony-lights",
      day: "2026-06-18",
      sortOrder: 600,
      startTime: "17:30",
      activity: "Symphony of Lights",
      activityType: "experience",
      place: "Victoria Harbour",
      linkLabel: "แผนที่",
      mapLink: "https://maps.google.com/?q=Symphony+of+Lights",
      coordinates: { lat: 22.2935, lng: 114.1696 },
      durationMinutes: 20,
      transportation: "เดิน",
      note: "เผื่อเวลาหามุมยืนก่อนแสงเริ่ม",
    }),
    item({
      id: "item-temple-street",
      day: "2026-06-18",
      sortOrder: 700,
      startTime: "19:00",
      activity: "อาหารเย็นที่ Temple Street Night Market",
      activityType: "food",
      place: "Temple Street",
      linkLabel: "แผนที่",
      mapLink: "https://maps.google.com/?q=Temple+Street+Night+Market",
      coordinates: { lat: 22.3067, lng: 114.1707 },
      durationMinutes: 90,
      transportation: "เดิน / MTR",
      note: "เลือกร้านหน้างานตามคิวและเมนูที่ทุกคนกินได้",
    }),
    item({
      id: "item-dimdim",
      day: "2026-06-19",
      sortOrder: 100,
      startTime: "08:30",
      activity: "Dim Dim Sum ที่ Tim Ho Wan",
      activityType: "food",
      place: "Shop G72, G/F, The Elements",
      linkLabel: "แผนที่",
      mapLink: "https://maps.google.com/?q=Dim+Dim+Sum+Tim+Ho+Wan+The+Elements+Hong+Kong",
      coordinates: { lat: 22.3049, lng: 114.1617 },
      address: "Shop G72, G/F, The Elements, 1 Austin Rd W, Tsim Sha Tsui",
      durationMinutes: 60,
      transportation: "เดิน",
      advisories: [{ code: "booking-recommended", label: "จองล่วงหน้าแนะนำ", severity: "warning" }],
      note: "ร้านนี้ได้รับคะแนนสูง 4.3/5 จากรีวิวจำนวนมาก เหมาะกับมื้อเช้าแบบไม่เร่ง",
      version: 4,
    }),
    item({
      id: "item-victoria-peak",
      day: "2026-06-19",
      sortOrder: 200,
      startTime: "10:00",
      activity: "Victoria Peak (The Peak Tram)",
      activityType: "attraction",
      place: "The Peak Tram",
      linkLabel: "แผนที่",
      mapLink: "https://maps.google.com/?q=The+Peak+Tram",
      coordinates: { lat: 22.2759, lng: 114.1455 },
      durationMinutes: 120,
      transportation: "Tram",
      advisories: [{ code: "crowd-window", label: "คนเยอะช่วงสาย", severity: "warning" }],
      note: "ถ้าคิวหนาแน่นให้ขยับไปช่วงบ่ายหรือใช้รถบัสขึ้นเขา",
    }),
    item({
      id: "item-pacific-place",
      day: "2026-06-19",
      sortOrder: 300,
      startTime: "12:30",
      activity: "ช้อปปิ้งที่ Pacific Place",
      activityType: "shopping",
      place: "Admiralty",
      linkLabel: "แผนที่",
      mapLink: "https://maps.google.com/?q=Pacific+Place+Hong+Kong",
      coordinates: { lat: 22.2776, lng: 114.1662 },
      durationMinutes: 90,
      transportation: "Taxi / เดิน",
      note: "พักเดินในห้างและหาเครื่องดื่มก่อนข้ามฝั่ง",
    }),
    item({
      id: "item-star-ferry",
      day: "2026-06-19",
      sortOrder: 400,
      startTime: "14:30",
      activity: "Star Ferry ไป Central",
      activityType: "travel",
      place: "Tsim Sha Tsui Pier",
      linkLabel: "แผนที่",
      mapLink: "https://maps.google.com/?q=Star+Ferry+Pier",
      coordinates: { lat: 22.2939, lng: 114.1698 },
      durationMinutes: 15,
      transportation: "เรือเฟอร์รี่",
      note: "เลือกชั้นบนถ้ามีที่ว่างเพื่อชมวิวอ่าว",
    }),
    item({
      id: "item-central-soho",
      day: "2026-06-19",
      sortOrder: 500,
      startTime: "15:00",
      activity: "เดินเล่นย่าน Central – SOHO",
      activityType: "experience",
      place: "Central / SOHO",
      linkLabel: "แผนที่",
      mapLink: "https://maps.google.com/?q=Central+SOHO+Hong+Kong",
      coordinates: { lat: 22.282, lng: 114.1523 },
      durationMinutes: 120,
      transportation: "เดิน",
      note: "คุม pace ให้ไม่เหนื่อยก่อนมื้อเย็น",
    }),
    item({
      id: "item-luk-yu",
      day: "2026-06-19",
      sortOrder: 600,
      startTime: "18:30",
      activity: "อาหารเย็น Luk Yu Tea House",
      activityType: "food",
      place: "Central",
      linkLabel: "แผนที่",
      mapLink: "https://maps.google.com/?q=Luk+Yu+Tea+House",
      coordinates: { lat: 22.2817, lng: 114.1565 },
      durationMinutes: 90,
      transportation: "MTR",
      advisories: [{ code: "booking-dinner", label: "จองล่วงหน้าแนะนำ", severity: "warning" }],
      note: "โทรยืนยันโต๊ะอีกครั้งช่วงบ่าย",
    }),
    item({
      id: "item-checkout",
      day: "2026-06-20",
      sortOrder: 100,
      startTime: "09:00",
      activity: "เช็คเอาท์จากโรงแรม",
      activityType: "stay",
      place: "Tsim Sha Tsui",
      linkLabel: "โรงแรม",
      mapLink: "https://maps.google.com/?q=Tsim+Sha+Tsui+hotel",
      coordinates: { lat: 22.2993, lng: 114.1722 },
      durationMinutes: 30,
      transportation: "เดิน",
      note: "ตรวจของก่อนออกจากห้อง",
    }),
    item({
      id: "item-shenzhen-transfer",
      day: "2026-06-20",
      sortOrder: 200,
      startTime: "10:00",
      activity: "เดินทางไป Shenzhen (Lo Wu / Lok Ma Chau)",
      activityType: "travel",
      place: "Lo Wu / Lok Ma Chau",
      linkLabel: "แผนที่",
      mapLink: "https://maps.google.com/?q=Lo+Wu+Control+Point",
      coordinates: { lat: 22.5316, lng: 114.1131 },
      durationMinutes: 60,
      transportation: "MTR / เดิน",
      advisories: [{ code: "passport", label: "พกพาสปอร์ต", severity: "warning" }],
      note: "เช็ควีซ่า อินเทอร์เน็ต และวิธีจ่ายเงินก่อนข้ามแดน",
    }),
    item({
      id: "item-shenzhen-hotel",
      day: "2026-06-20",
      sortOrder: 300,
      startTime: "11:30",
      activity: "เข้าพักโรงแรมที่ Shenzhen",
      activityType: "stay",
      place: "Shenzhen hotel",
      linkLabel: "โรงแรม",
      mapLink: "https://maps.google.com/?q=Shenzhen+hotel",
      coordinates: { lat: 22.5431, lng: 114.0579 },
      durationMinutes: 30,
      transportation: "แท็กซี่",
      note: "ฝากกระเป๋าและพักสั้นๆ ก่อนออกไปมื้อกลางวัน",
    }),
  ];
}
