import type { BookingDoc } from "./types";

export function createSeedBookingDocs({
  tripId,
  updatedAt,
}: {
  tripId: string;
  updatedAt: string;
}): BookingDoc[] {
  return [
    {
      id: "booking-flight-bkk-hkg",
      tripId,
      type: "flight",
      title: "Bangkok to Hong Kong flight",
      status: "confirmed",
      visibility: "shared",
      ownerMemberId: null,
      providerName: "Cathay Travel",
      confirmationCode: "QR349-HK",
      startsAt: "2026-06-18T09:00:00+07:00",
      endsAt: "2026-06-18T12:55:00+08:00",
      timezone: "Asia/Bangkok",
      priceAmount: 2180,
      currency: "HKD",
      travelerIds: ["member-aom", "member-beam", "member-nam"],
      externalLinks: [
        { id: "link-flight-source", label: "Airline booking", url: "https://example.com/airline/booking/QR349-HK", provider: "Airline", accessNote: "Use group email login." },
        { id: "link-flight-drive", label: "Google Drive voucher", url: "https://drive.google.com/example-flight-voucher", provider: "Google Drive", accessNote: "Shared with organizers." },
      ],
      relatedItineraryItemIds: ["item-flight-bkk-hkg", "item-arrive-hkg"],
      relatedTaskIds: [],
      relatedExpenseIds: [],
      noteIds: [],
      notes: "Keep passport in carry-on before boarding.",
      createdBy: "member-aom",
      updatedAt,
      version: 1,
    },
    {
      id: "booking-hotel-tst",
      tripId,
      type: "hotel",
      title: "Tsim Sha Tsui hotel stay",
      status: "needs_action",
      visibility: "shared",
      ownerMemberId: null,
      providerName: "Joii Stay",
      confirmationCode: "TST-5600",
      startsAt: "2026-06-18T15:00:00+08:00",
      endsAt: "2026-06-21T11:00:00+08:00",
      timezone: "Asia/Hong_Kong",
      priceAmount: 5600,
      currency: "HKD",
      travelerIds: ["member-aom", "member-beam", "member-nam"],
      externalLinks: [
        { id: "link-hotel-source", label: "Hotel reservation", url: "https://example.com/hotel/tst-5600", provider: "Hotel", accessNote: "Reservation under Demo Traveler." },
      ],
      relatedItineraryItemIds: ["item-hotel-checkin"],
      relatedTaskIds: ["task-hotel-names"],
      relatedExpenseIds: [],
      noteIds: [],
      notes: "Needs final passport names before free-cancellation window closes.",
      createdBy: "member-beam",
      updatedAt,
      version: 1,
    },
    {
      id: "booking-peak-tram",
      tripId,
      type: "activity_ticket",
      title: "Peak Tram tickets",
      status: "paid",
      visibility: "shared",
      ownerMemberId: null,
      providerName: "Peak Tram",
      confirmationCode: "PEAK-0619",
      startsAt: "2026-06-19T10:00:00+08:00",
      endsAt: "2026-06-19T12:00:00+08:00",
      timezone: "Asia/Hong_Kong",
      priceAmount: 880,
      currency: "HKD",
      travelerIds: ["member-aom", "member-beam", "member-nam", "member-family"],
      externalLinks: [
        { id: "link-peak-voucher", label: "Voucher link", url: "https://drive.google.com/example-peak-tram", provider: "Google Drive", accessNote: "Anyone with trip access can open." },
      ],
      relatedItineraryItemIds: ["item-victoria-peak"],
      relatedTaskIds: ["task-peak-tram"],
      relatedExpenseIds: ["expense-peak-tram"],
      noteIds: [],
      notes: "Use printed QR backup if mobile signal is weak.",
      createdBy: "member-beam",
      updatedAt,
      version: 1,
    },
    {
      id: "booking-passport-nam",
      tripId,
      type: "passport",
      title: "Explorer Friend passport",
      status: "needs_action",
      visibility: "sensitive",
      ownerMemberId: "member-nam",
      providerName: null,
      confirmationCode: null,
      startsAt: "2026-06-12T00:00:00+07:00",
      endsAt: null,
      timezone: "Asia/Bangkok",
      priceAmount: null,
      currency: null,
      travelerIds: ["member-nam"],
      externalLinks: [],
      relatedItineraryItemIds: ["item-flight-bkk-hkg", "item-hotel-checkin"],
      relatedTaskIds: ["task-passport-nam"],
      relatedExpenseIds: [],
      noteIds: [],
      notes: "Organizer needs passport name spelling for hotel and flight check-in.",
      createdBy: "member-nam",
      updatedAt,
      version: 1,
    },
    {
      id: "booking-group-insurance",
      tripId,
      type: "insurance",
      title: "Group travel insurance",
      status: "confirmed",
      visibility: "sensitive",
      ownerMemberId: null,
      providerName: "SafeTrip",
      confirmationCode: "SAFE-HK-2026",
      startsAt: "2026-06-18T00:00:00+07:00",
      endsAt: "2026-06-23T23:59:00+07:00",
      timezone: "Asia/Bangkok",
      priceAmount: 1450,
      currency: "THB",
      travelerIds: ["member-aom", "member-beam", "member-nam"],
      externalLinks: [
        { id: "link-insurance-policy", label: "Policy document", url: "https://drive.google.com/example-insurance-policy", provider: "Google Drive", accessNote: "Shared with organizers and insured travelers." },
      ],
      relatedItineraryItemIds: [],
      relatedTaskIds: [],
      relatedExpenseIds: [],
      noteIds: [],
      notes: "Emergency phone number is in the policy document.",
      createdBy: "member-aom",
      updatedAt,
      version: 1,
    },
  ];
}
