export const enBookingCopy = {
  pageLabel: "Bookings & Docs",
  title: "Bookings & Docs",
  records: (count: number) => `${count} records`,
  canEditBookings: "Can edit bookings",
  readOnly: "Read-only",
  bookingFolders: "Booking folders",
  folderCount: (title: string, count: number) => `${title}, ${count} items`,
  visibleItems: (description: string, count: number) => `${description} · ${count} visible items`,
  addBooking: "Add booking",
  searchPlaceholder: "Search bookings, docs, links",
  statusFilter: "Status",
  allStatuses: "All statuses",
  fileList: "Files",
  columnName: "Name",
  columnDate: "Date",
  columnProvider: "Provider",
  columnLinkedStop: "Linked stop",
  columnStatus: "Status",
  columnOpen: "Open",
  itemCount: (count: number) => `${count} items`,
  bookingSummary: "Booking summary",
  emptyTitle: "No matching files",
  emptyDetail: "No items in this view. Try another folder, status, or search term.",
  lockedSensitiveRecord: "Locked sensitive record",
  select: (title: string) => `Select ${title}`,
  noProvider: "No provider",
  noLinkedStop: "No linked stop",
  noDate: "No date",
  noConfirmation: "No confirmation",
  confirmation: "Confirmation",
  quickFacts: "Quick facts",
  travelers: (count: number) => `${count} travelers`,
  noPrice: "No price",
  links: (count: number) => `${count} links`,
  cloudLink: "Cloud link",
  open: "Open",
  noLink: "No link",
  editBooking: "Edit booking",
  deleteBooking: "Delete booking",
  bookingDetails: "Booking details",
  closeBookingPreview: "Close booking preview",
  noBookingSelected: "No booking selected",
  noNotes: "No notes yet.",
  externalLinks: "External links",
  openLink: (label: string) => `Open ${label}`,
  noExternalLinks: "No external links yet.",
  tripContext: "Trip context",
  itineraryLinks: (count: number) => `${count} itinerary links`,
  todos: (count: number) => `${count} todos`,
  expenses: (count: number) => `${count} expenses`,
  notes: (count: number) => `${count} notes`,
  noTravelers: "No travelers",
  addBookingDialog: "Add booking",
  editBookingDialog: "Edit booking",
  closeBookingDialog: "Close booking dialog",
  titleField: "Title",
  typeField: "Type",
  statusField: "Status",
  visibilityField: "Visibility",
  providerField: "Provider",
  confirmationCodeField: "Confirmation code",
  startField: "Start",
  endField: "End",
  priceField: "Price",
  currencyField: "Currency",
  externalLinkField: "External link",
  notesField: "Notes",
  travelersField: "Travelers",
  linkedItinerary: "Linked itinerary",
  linkedTodos: "Linked todos",
  linkedExpenses: "Linked expenses",
  linkedNotes: "Linked notes",
  cancel: "Cancel",
  saveBooking: "Save booking",
  deletePrompt: (title: string) => `Delete ${title}? Related itinerary, todo, and expense records will stay in place.`,
  anyTimeDocs: "Any time docs",
  externalLinkLabel: "External link",
  folders: {
    all: { title: "All items", description: "Everything saved for this trip" },
    transport: { title: "Transport", description: "Flights, trains, local passes" },
    stays: { title: "Stays", description: "Hotels and room bookings" },
    tickets: { title: "Tickets", description: "Attractions and activities" },
    travel_docs: { title: "Travel docs", description: "Passport, visa, insurance" },
    needs_action: { title: "Needs action", description: "Missing, unpaid, or pending" },
    external_links: { title: "Links & files", description: "Drive, photos, cloud storage" },
  },
  enumLabels: {
    flight: "Flight",
    train: "Train",
    public_transport: "Public Transport",
    hotel: "Hotel",
    insurance: "Insurance",
    passport: "Passport",
    visa: "Visa",
    activity_ticket: "Activity Ticket",
    other: "Other",
    draft: "Draft",
    needs_action: "Needs Action",
    booked: "Booked",
    confirmed: "Confirmed",
    paid: "Paid",
    cancelled: "Cancelled",
    expired: "Expired",
    shared: "Shared",
    sensitive: "Sensitive",
    private: "Private",
  },
} as const;
