import { cn } from "@/src/lib/cn";
import { accountFormClassName } from "../../layout/account-form.styles";

export const accountSettingsFormClassName = cn(accountFormClassName, "account-settings-form grid gap-3");
export const portalCreateTripInlineClassName =
  "portal-create-trip-inline portal-trip-simple !gap-4 !rounded-none !border-0 !bg-transparent !p-0 !shadow-none";
export const tripSimpleHeadClassName = "trip-simple-head hidden";
export const tripWizardLayoutClassName =
  "trip-wizard-layout grid grid-cols-[minmax(430px,0.76fr)_minmax(560px,1fr)] items-start gap-[22px] max-[1023px]:grid-cols-1";
export const tripWizardMainClassName =
  "trip-wizard-main min-h-0 rounded-(--radius-lg) border border-(--color-border) bg-(--color-surface) p-0 shadow-[var(--shadow-soft)] max-[767px]:rounded-none max-[767px]:border-0 max-[767px]:bg-transparent max-[767px]:shadow-none";
export const tripWizardPaneClassName =
  "trip-wizard-pane grid gap-0 [&_.account-two-col]:rounded-(--radius-md) [&_.account-two-col]:border [&_.account-two-col]:border-(--color-border) [&_.account-two-col]:bg-(--color-surface) [&_.account-two-col]:p-3 max-[767px]:[&_.account-two-col]:p-2.5 [&>p]:m-0 [&>p]:text-[13px] [&>p]:leading-5 [&>p]:text-(--color-text-muted) [&_input]:min-h-[52px] [&_input]:rounded-(--radius-md) [&_input]:text-[15px] [&_label]:min-h-[76px] [&_label_small]:mt-1.5 [&_label_small]:block [&_label_small]:text-[11px] [&_label_small]:leading-4 [&_label_small]:text-(--color-text-muted)";
export const tripScopePanelClassName =
  "trip-scope-panel grid gap-0 rounded-[10px] border-0 bg-transparent px-[22px] pb-6 pt-7 max-[767px]:px-0 max-[767px]:pb-2 max-[767px]:pt-2";
export const tripLivePreviewClassName =
  "trip-live-preview sticky top-[18px] z-10 grid h-fit max-h-[calc(100vh-36px)] min-h-0 min-w-0 content-start gap-0 self-start overflow-y-auto overscroll-contain rounded-(--radius-lg) border border-(--color-border) bg-(--color-surface) px-3.5 pb-3 pt-5 shadow-[var(--shadow-soft)] max-[1023px]:static max-[1023px]:max-h-none max-[767px]:mt-0 max-[767px]:rounded-none max-[767px]:border-0 max-[767px]:bg-transparent max-[767px]:p-0 max-[767px]:shadow-none";
export const tripWorkflowNavClassName =
  "trip-workflow-nav mb-3 grid gap-2 rounded-[10px] border border-(--color-border) bg-(--color-surface-subtle) p-2.5 min-[1024px]:hidden [&_ol]:m-0 [&_ol]:grid [&_ol]:grid-flow-col [&_ol]:auto-cols-[minmax(64px,1fr)] [&_ol]:gap-1.5 [&_ol]:overflow-x-auto [&_ol]:overscroll-x-contain [&_ol]:p-0 [&_ol]:[scrollbar-width:none] [&_ol::-webkit-scrollbar]:hidden [&_li]:list-none [&_button]:min-h-8 [&_button]:w-full [&_button]:rounded-[7px] [&_button]:border [&_button]:border-(--color-border) [&_button]:bg-white [&_button]:px-1.5 [&_button]:py-1.5 [&_button]:text-center [&_button]:text-[11px] [&_button]:font-black [&_button]:text-(--color-text-muted) [&_button[aria-current='step']]:border-(--color-warning-border) [&_button[aria-current='step']]:bg-(--color-warning-soft) [&_button[aria-current='step']]:text-(--color-warning-strong) [&_p]:m-0 [&_p]:text-xs [&_p]:font-[850] [&_p]:text-(--color-warning-strong)";
export const tripStepSectionClassName = "trip-step-section grid gap-3.5 pb-[34px] max-[767px]:pb-4";
export const tripStepSectionCompactClassName = cn(tripStepSectionClassName, "trip-step-section--compact pb-3.5");
export const tripMobileStepActionsClassName =
  "trip-mobile-step-actions hidden items-center justify-between gap-2 py-2 max-[767px]:flex [&_.button]:w-auto [&_.button]:min-w-[96px] [&_span]:text-xs [&_span]:font-black [&_span]:text-(--color-text-muted)";
export const tripStepHeadingClassName =
  "trip-step-heading grid gap-1.5 [&_span]:text-[13px] [&_span]:leading-[18px] [&_span]:text-(--color-text-muted) [&_strong]:text-lg [&_strong]:leading-6 [&_strong]:text-(--color-text)";
export const tripNameFieldClassName =
  "trip-name-field relative min-h-[52px] [&_input]:min-h-[52px] [&_input]:rounded-(--radius-sm) [&_input]:bg-(--color-surface) [&_input]:shadow-none [&_small]:absolute [&_small]:right-[13px] [&_small]:top-[17px] [&_small]:text-xs [&_small]:font-bold [&_small]:text-(--color-text-muted)";
export const tripCountryPickerClassName =
  "trip-country-picker grid gap-3 [&>small]:text-[11px] [&>small]:font-[750] [&>small]:leading-4 [&>small]:text-(--color-text-muted)";
export const tripCountrySearchClassName =
  "trip-country-search relative grid gap-2 [&_input]:min-h-[52px] [&_input]:rounded-(--radius-sm) [&_input]:bg-(--color-surface) [&_input]:shadow-none [&_label]:min-h-0";
export const tripCityEntryClassName =
  "trip-city-entry grid grid-cols-[minmax(0,1fr)_auto] items-end gap-2.5 rounded-[9px] border border-(--color-border) bg-(--color-surface-subtle) p-2.5 max-[767px]:grid-cols-1 [&_input]:min-h-[42px] [&_input]:rounded-[9px] [&_input]:border [&_input]:border-(--color-border) [&_input]:bg-white [&_input]:px-3.5 [&_label]:grid [&_label]:gap-1 [&_span]:text-xs [&_span]:font-[850] [&_span]:text-(--color-text-muted)";
export const tripFormDestinationRowClassName =
  "trip-form-destination-row grid grid-cols-[minmax(0,1fr)_minmax(0,1fr)] gap-2.5 max-[767px]:grid-cols-1";
export const tripPlaceThumbClassName =
  "trip-place-thumb block size-[42px] rounded-md bg-[linear-gradient(145deg,rgb(15_118_110_/_0.2),transparent_54%),linear-gradient(45deg,rgb(255_255_255_/_0.22)_25%,transparent_25%_50%,rgb(255_255_255_/_0.22)_50%_75%,transparent_75%),var(--color-route-soft)] bg-[length:auto,12px_12px,auto]";
export const tripMiniDestinationClassName =
  "trip-mini-destination grid min-h-[70px] grid-cols-[42px_minmax(0,1fr)_auto] items-center gap-2 rounded-[9px] border border-(--color-border) bg-white p-2 [&_small]:flex [&_small]:min-w-0 [&_small]:flex-wrap [&_small]:gap-x-1 [&_small]:text-[11px] [&_small]:leading-[15px] [&_small]:text-(--color-text-muted) [&_small_span]:min-w-0 [&_small_span]:overflow-hidden [&_small_span]:text-ellipsis [&_strong]:block [&_button]:grid [&_button]:size-6 [&_button]:cursor-pointer [&_button]:place-items-center [&_button]:border-0 [&_button]:bg-transparent [&_button]:text-(--color-text-muted)";
export const tripMiniAddClassName =
  "trip-mini-add grid min-h-[70px] grid-cols-[20px_minmax(0,1fr)] items-center gap-2 rounded-[9px] border border-dashed border-(--color-border) bg-white p-2 text-xs font-extrabold text-(--color-text-muted)";
export const tripSelectedCountriesClassName =
  "trip-selected-countries flex min-h-[44px] flex-wrap items-center gap-3 rounded-(--radius-md) border border-dashed border-(--color-border-strong) bg-(--color-surface-subtle) p-3 text-[13px] font-bold text-(--color-text-muted)";
export const tripCountrySuggestionsClassName =
  "trip-country-suggestions grid grid-cols-3 gap-3 max-[767px]:grid-cols-1 [&_button]:grid [&_button]:min-h-[68px] [&_button]:grid-cols-[42px_minmax(0,1fr)] [&_button]:content-center [&_button]:items-center [&_button]:gap-[3px] [&_button]:rounded-[9px] [&_button]:border [&_button]:border-(--color-border) [&_button]:bg-(--color-surface) [&_button]:px-2.5 [&_button]:py-[9px] [&_button]:text-left [&_button]:text-(--color-text) [&_button]:transition-[background,border-color,box-shadow] [&_button]:duration-[180ms] [&_button:hover]:border-(--color-primary) [&_button:hover]:bg-(--color-primary-soft) [&_button:hover]:shadow-[0_10px_18px_rgb(15_118_110_/_0.08)] [&_button:focus-visible]:border-(--color-route-border) [&_button:focus-visible]:bg-(--color-route-soft) [&_button:focus-visible]:shadow-[0_10px_18px_rgb(191_219_254_/_0.36)] [&_button::before]:block [&_button::before]:size-[42px] [&_button::before]:rounded-md [&_button::before]:bg-[linear-gradient(145deg,rgb(15_118_110_/_0.2),transparent_54%),linear-gradient(45deg,rgb(255_255_255_/_0.22)_25%,transparent_25%_50%,rgb(255_255_255_/_0.22)_50%_75%,transparent_75%),var(--color-route-soft)] [&_button::before]:bg-[length:auto,12px_12px,auto] [&_button::before]:content-[''] [&_span]:col-start-2 [&_span]:overflow-hidden [&_span]:text-ellipsis [&_span]:whitespace-nowrap [&_span]:text-[11px] [&_span]:leading-[15px] [&_span]:text-(--color-text-muted) [&_strong]:col-start-2 [&_strong]:text-[13px] [&_strong]:leading-[18px]";
export const tripRouteCalendarClassName =
  "trip-route-calendar grid gap-2.5 rounded-[10px] border border-(--color-border) bg-white p-3 max-[767px]:rounded-none max-[767px]:border-0 max-[767px]:bg-transparent max-[767px]:p-0 [&>legend]:px-1 [&>legend]:text-[13px] [&>legend]:font-[850] [&>legend]:leading-5 [&>legend]:text-(--color-text) [&>strong]:text-[14px] [&>strong]:leading-5 [&>strong]:text-(--color-text)";
export const tripCalendarSummaryClassName =
  "trip-calendar-summary grid grid-cols-2 gap-2 max-[767px]:grid-cols-1 [&_label]:grid [&_label]:min-h-0 [&_label]:gap-1 [&_input]:min-h-10 [&_input]:rounded-[8px] [&_input]:border [&_input]:border-(--color-border) [&_input]:bg-(--color-surface-subtle) [&_input]:px-3 [&_input]:text-[13px] [&_input]:font-black [&_span]:text-[11px] [&_span]:font-[850] [&_span]:text-(--color-text-muted)";
export const tripCalendarGridClassName =
  "trip-calendar-grid grid grid-cols-7 gap-1 [&_button]:min-h-9 [&_button]:rounded-[7px] [&_button]:border [&_button]:border-(--color-border) [&_button]:bg-(--color-surface) [&_button]:text-xs [&_button]:font-black [&_button]:text-(--color-text-muted) [&_button]:transition-[background,border-color,color,box-shadow] [&_button:hover]:border-(--color-primary) [&_button:hover]:bg-(--color-primary-soft) [&_button[data-date-state='today']]:border-(--color-warning-border) [&_button[data-date-state='today']]:text-(--color-warning-strong) [&_button[data-date-state='in-range']]:border-(--color-route-border) [&_button[data-date-state='in-range']]:bg-(--color-route-soft) [&_button[data-date-state='in-range']]:text-(--color-route) [&_button[data-date-state='start']]:border-(--color-primary) [&_button[data-date-state='start']]:bg-(--color-primary) [&_button[data-date-state='start']]:text-white [&_button[data-date-state='end']]:border-(--color-primary) [&_button[data-date-state='end']]:bg-(--color-primary) [&_button[data-date-state='end']]:text-white [&_button[aria-pressed='true']]:shadow-[0_6px_12px_rgb(15_118_110_/_0.14)]";
export const tripCalendarFooterClassName =
  "trip-calendar-footer grid grid-cols-[minmax(0,1fr)_36px] items-center gap-2 max-[767px]:grid-cols-1 [&_.button]:min-h-9 [&_.button]:rounded-[8px]";
export const tripDateArrowClassName =
  "trip-date-arrow grid size-9 items-center justify-items-center rounded-[8px] border border-(--color-primary-border) bg-(--color-primary-soft) text-(--color-primary-strong) max-[767px]:w-full";
export const tripCalendarHelperClassName =
  "trip-calendar-helper flex items-center gap-2 border-t border-(--color-border) pt-2 text-xs leading-[18px] text-(--color-text-muted) [&_.icon]:size-4 [&_.icon]:shrink-0 [&_.icon]:text-(--color-primary-strong)";
export const tripAccessPanelClassName =
  "trip-access-panel grid gap-3 rounded-(--radius-lg) border border-(--color-border) bg-(--color-surface) p-3 max-[767px]:rounded-none max-[767px]:border-0 max-[767px]:bg-transparent max-[767px]:p-0 [&_summary]:mb-0 [&_summary]:flex [&_summary]:min-h-[42px] [&_summary]:cursor-pointer [&_summary]:items-center [&_summary]:justify-between [&_summary]:gap-3 [&_summary]:text-[13px] [&_summary]:font-black [&_summary]:text-(--color-text) [&_summary_strong]:overflow-hidden [&_summary_strong]:text-ellipsis [&_summary_strong]:whitespace-nowrap [&_summary_strong]:text-xs [&_summary_strong]:font-[850] [&_summary_strong]:text-(--color-text-muted) open:[&_summary]:mb-2 open:[&_summary]:border-b open:[&_summary]:border-(--color-border) open:[&_summary]:pb-2.5";
export const tripGeneratedAccessClassName =
  "trip-generated-access grid grid-cols-[minmax(0,1fr)_minmax(0,1fr)_auto] items-end gap-2.5 border-t border-(--color-border) pt-3 max-[767px]:grid-cols-1 [&_label]:min-w-0 [&_input]:bg-white [&_.button]:min-h-[42px] [&_.button]:w-auto [&_.button]:whitespace-nowrap [&_.button]:rounded-[8px]";
export const tripAccessNoteClassName =
  "trip-access-note mt-3 flex items-center gap-2 border-t border-(--color-border) pt-3 text-xs font-[750] leading-[18px] text-(--color-text-muted) max-[767px]:hidden [&_.icon]:size-4 [&_.icon]:shrink-0 [&_.icon]:text-(--color-primary-strong)";
export const tripTicketReviewClassName =
  "trip-ticket-review grid grid-cols-2 gap-2.5 [.account-page--portal-new-trip_&]:hidden max-[767px]:grid-cols-1 [&>div]:grid [&>div]:min-h-[76px] [&>div]:content-center [&>div]:gap-1 [&>div]:rounded-(--radius-md) [&>div]:border [&>div]:border-(--color-border) [&>div]:bg-(--color-surface) [&>div]:p-3 [&_span]:text-[11px] [&_span]:font-[850] [&_span]:uppercase [&_span]:text-(--color-text-muted) [&_strong]:min-w-0 [&_strong]:[overflow-wrap:anywhere]";
export const tripShareStripClassName =
  "trip-share-strip grid min-h-[52px] grid-cols-[minmax(0,1fr)_auto_auto] items-center gap-3 rounded-[9px] border border-(--color-route-border) bg-(--color-route-soft) py-2 pl-4 pr-2.5 text-[13px] font-extrabold text-(--color-route) min-[1024px]:grid-cols-[minmax(0,1fr)_auto_auto] max-[1023px]:grid-cols-1 max-[1023px]:text-left max-[1023px]:[&_.button]:w-full [&_span]:inline-flex [&_span]:min-w-0 [&_span]:items-center [&_span]:gap-2 [&_strong]:[overflow-wrap:anywhere] [&_.icon]:size-6 [&_.button]:min-h-9 [&_.button]:rounded-[7px]";
export const tripWizardActionsClassName =
  "trip-wizard-actions sticky bottom-0 z-20 grid gap-2.5 border-t border-(--color-border) bg-(--color-surface) px-[22px] pb-[22px] pt-3.5 shadow-[0_-8px_18px_rgb(15_23_42_/_0.05)] min-[1024px]:grid-cols-[minmax(430px,0.76fr)_minmax(560px,1fr)] min-[1024px]:items-stretch max-[767px]:[.account-page--portal-new-trip_&]:w-full max-[767px]:[.account-page--portal-new-trip_&]:px-0 max-[767px]:pb-3 max-[767px]:pt-2.5 [&_.trip-wizard-action-buttons]:flex [&_.trip-wizard-action-buttons]:justify-between [&_.trip-wizard-action-buttons]:gap-2.5 max-[767px]:[&_.trip-wizard-action-buttons]:flex-col [&_.button]:w-auto max-[767px]:[&_.button]:w-full [&_.button--primary]:min-h-[58px] [&_.button--primary]:flex-1 [&_.button--primary]:justify-center [&_.button--primary]:rounded-[9px] [&_.button--primary]:bg-(--color-primary) [&_.button--primary]:text-base [&_.button--primary]:shadow-[0_12px_24px_rgb(15_118_110_/_0.18)] [&_.button--primary:disabled]:bg-(--color-surface-muted) [&_.button--primary:disabled]:text-(--color-text-subtle) [&_.button--primary:disabled]:shadow-none [&_.button--secondary]:hidden";
export const tripWizardActionStatusClassName =
  "trip-wizard-action-status m-0 inline-flex min-h-8 items-center gap-2 px-0 text-[12px] font-[850] text-(--color-text-muted) min-[1024px]:col-start-1 [&_.icon]:size-4 [&_.icon]:text-(--color-primary-strong)";
export const tripWizardActionSummaryClassName =
  "trip-wizard-action-summary hidden min-h-8 min-w-0 items-center gap-4 text-[12px] text-(--color-text-muted) min-[1024px]:col-start-2 min-[1024px]:row-span-2 min-[1024px]:row-start-1 min-[1024px]:grid min-[1024px]:grid-cols-[minmax(0,1.1fr)_minmax(0,1fr)_auto] [&_strong]:min-w-0 [&_strong]:overflow-hidden [&_strong]:text-ellipsis [&_strong]:whitespace-nowrap [&_strong]:text-[14px] [&_strong]:text-(--color-text) [&_span]:min-w-0 [&_span]:overflow-hidden [&_span]:text-ellipsis [&_span]:whitespace-nowrap";
export const tripWizardActionButtonsClassName = "trip-wizard-action-buttons";
export const tripBoardingPassClassName =
  "trip-draft-summary mx-auto mb-3 grid w-[min(100%,760px)] gap-3";
export const tripMainTicketClassName =
  "trip-main-ticket relative grid gap-4 rounded-[10px] border border-(--color-border) bg-white p-5 max-[767px]:[.account-page--portal-new-trip_&]:p-4 [&_.trip-preview-map]:min-h-[170px] [&_.trip-preview-map]:rounded-[9px] max-[767px]:[.account-page--portal-new-trip_&_.trip-preview-map]:min-h-[148px] [&>p]:m-0 [&>p]:flex [&>p]:items-center [&>p]:gap-2 [&>p]:text-[13px] [&>p]:text-(--color-text-muted) [&>strong]:block [&>strong]:[overflow-wrap:anywhere] [&>strong]:text-[24px] [&>strong]:leading-8 [&>strong]:text-(--color-text) max-[767px]:[.account-page--portal-new-trip_&>strong]:text-2xl max-[767px]:[.account-page--portal-new-trip_&>strong]:leading-[29px]";
export const tripPreviewTicketTopClassName =
  "trip-boarding-ticket-top flex items-center justify-between gap-2.5 [&>span]:text-xs [&>span]:font-black [&>span]:tracking-[0.02em] [&>span]:text-(--color-text-muted)";
export const tripFlightRouteClassName =
  "trip-flight-route mb-[18px] grid grid-cols-[86px_minmax(0,1fr)_86px] items-center gap-2.5 max-[767px]:[.account-page--portal-new-trip_&]:grid-cols-[58px_minmax(0,1fr)_58px] [&_div]:grid [&_div]:gap-0.5 [&_div:last-child]:text-right [&_span]:text-xs [&_span]:text-(--color-text-muted) [&_strong]:text-[21px] [&_strong]:leading-6 [&_strong]:text-(--color-text)";
export const tripFlightLineClassName =
  "trip-flight-line relative grid h-px place-items-center border-t-2 border-dashed border-[color-mix(in_srgb,var(--color-route)_34%,var(--color-border-strong))] before:absolute before:left-0 before:top-[-5px] before:size-2.5 before:rounded-full before:bg-(--color-route) before:content-[''] after:absolute after:right-0 after:top-[-5px] after:size-2.5 after:rounded-full after:bg-(--color-route) after:content-[''] [&_.icon]:size-7 [&_.icon]:bg-white [&_.icon]:p-1 [&_.icon]:text-(--color-route)";
export const tripPreviewDestinationRowClassName =
  "trip-preview-destination-row grid gap-2.5 [&>span]:text-xs [&>span]:font-black [&>span]:uppercase [&>span]:text-(--color-text-muted) [&>div]:grid [&>div]:grid-cols-[repeat(auto-fit,minmax(180px,1fr))] [&>div]:gap-2.5 max-[767px]:[.account-page--portal-new-trip_&>div]:grid-cols-1";
export const tripPreviewDestinationCardClassName =
  "trip-preview-destination-card grid min-h-[82px] gap-1.5 rounded-[9px] border border-(--color-border) bg-(--color-surface-subtle) p-3 text-left [&_small]:flex [&_small]:min-w-0 [&_small]:flex-wrap [&_small]:gap-x-1 [&_small]:text-[11px] [&_small]:leading-4 [&_small]:text-(--color-text-muted) [&_strong]:min-w-0 [&_strong]:[overflow-wrap:anywhere] [&_strong]:text-[15px] [&_strong]:leading-5 [&_strong]:text-(--color-text)";
export const tripTicketStubClassName =
  "trip-ticket-stub grid grid-cols-3 gap-2.5 rounded-[10px] border border-(--color-border) bg-(--color-surface-subtle) p-3 max-[767px]:[.account-page--portal-new-trip_&]:grid-cols-1 [&>div]:grid [&>div]:gap-1 [&>div]:rounded-[8px] [&>div]:border [&>div]:border-(--color-border) [&>div]:bg-white [&>div]:p-3 [&>div_span]:text-xs [&>div_span]:text-(--color-text-muted) [&>div_strong]:min-w-0 [&>div_strong]:[overflow-wrap:anywhere] [&>div_strong]:text-[15px] [&>div_strong]:leading-5 [&>div_strong]:text-(--color-text) [&>.icon]:hidden";
