export const photoCopy = {
  en: {
    pageLabel: "Photos & Albums",
    title: "Photos & Albums",
    albumLinks: (count: number) => `${count} album links`,
    canAddAlbums: "Can add albums",
    readOnly: "Read-only",
    summaryLabel: "Photo album summary",
    savedDestinations: "Saved destinations",
    albums: (count: number) => `${count} albums`,
    sharedUploads: "Shared uploads",
    collaborative: (count: number) => `${count} collaborative`,
    uploadRequests: "Upload requests",
    requests: (count: number) => `${count} requests`,
    needsAccessNote: "Needs access note",
    missing: (count: number) => `${count} missing`,
    providersLabel: "Photo providers",
    providerCount: (label: string, count: number) => `${label}, ${count} albums`,
    providerHint: (count: number) => `Photos stay with the linked provider · ${count} visible albums`,
    addAlbum: "Add album",
    albumLinksLabel: "Photo album links",
    emptyTitle: "No albums in this view",
    emptyDetail: "Add a Google Photos album, Drive folder, Dropbox request, or another shared photo destination.",
    deleteAlbum: "Delete album",
    deletePrompt: (title: string) => `Delete ${title}? The external provider album will stay in place.`,
    cancel: "Cancel",
    selectAlbum: (title: string) => `Select ${title}`,
    coverFor: (title: string) => `Cover for ${title}`,
    defaultAccessNote: "Add access note so the group knows how to use this album.",
    noOwner: "No owner",
    tripLevel: "Trip-level",
    unsafeLinkBlocked: "Unsafe link blocked",
    openAlbumTitle: (title: string) => `Open ${title}`,
    openBlocked: "Open blocked",
    editAlbum: "Edit album",
    inspectorLabel: "Photo album inspector",
    selectHint: "Select an album to see access details.",
    externalProviderNote: "External provider permissions control real access.",
    blockedLink: "Blocked link",
    copy: "Copy",
    openAlbum: "Open album",
    access: "Access",
    noAccessNote: "No access note yet.",
    owner: "Owner",
    noOwnerAssigned: "No owner assigned",
    createdBy: (name: string) => `Created by ${name}`,
    relatedStops: "Related stops",
    addAlbumDialog: "Add album",
    editAlbumDialog: "Edit album",
    close: "Close",
    titleField: "Title",
    providerField: "Provider",
    accessField: "Access",
    ownerField: "Owner",
    albumLinkField: "Album link",
    dayField: "Day",
    descriptionField: "Description",
    accessNoteField: "Access note",
    relatedItinerary: "Related itinerary",
    saveAlbum: "Save album",
    providers: {
      all: "All albums",
      google_photos: "Google Photos",
      icloud: "iCloud",
      google_drive: "Google Drive",
      dropbox: "Dropbox",
      onedrive: "OneDrive",
      custom: "Custom",
    },
    accessLabels: {
      view_only: "View only",
      collaborative: "Collaborative",
      upload_request: "Upload request",
    },
  },
  th: {
    pageLabel: "รูปภาพและอัลบั้ม",
    title: "รูปภาพและอัลบั้ม",
    albumLinks: (count: number) => `${count} ลิงก์อัลบั้ม`,
    canAddAlbums: "เพิ่มอัลบั้มได้",
    readOnly: "อ่านอย่างเดียว",
    summaryLabel: "สรุปอัลบั้มรูปภาพ",
    savedDestinations: "ปลายทางที่บันทึกไว้",
    albums: (count: number) => `${count} อัลบั้ม`,
    sharedUploads: "อัปโหลดร่วมกัน",
    collaborative: (count: number) => `${count} อัลบั้มร่วม`,
    uploadRequests: "คำขออัปโหลด",
    requests: (count: number) => `${count} คำขอ`,
    needsAccessNote: "ต้องมีโน้ตการเข้าถึง",
    missing: (count: number) => `ขาด ${count} รายการ`,
    providersLabel: "ผู้ให้บริการรูปภาพ",
    providerCount: (label: string, count: number) => `${label}, ${count} อัลบั้ม`,
    providerHint: (count: number) => `รูปภาพยังอยู่กับผู้ให้บริการที่ลิงก์ไว้ · แสดง ${count} อัลบั้ม`,
    addAlbum: "เพิ่มอัลบั้ม",
    albumLinksLabel: "ลิงก์อัลบั้มรูปภาพ",
    emptyTitle: "ไม่มีอัลบั้มในมุมมองนี้",
    emptyDetail: "เพิ่ม Google Photos, โฟลเดอร์ Drive, คำขอ Dropbox หรือปลายทางรูปภาพอื่นที่แชร์ได้",
    deleteAlbum: "ลบอัลบั้ม",
    deletePrompt: (title: string) => `ลบ ${title}? อัลบั้มภายนอกจะยังอยู่ที่ผู้ให้บริการเดิม`,
    cancel: "ยกเลิก",
    selectAlbum: (title: string) => `เลือก ${title}`,
    coverFor: (title: string) => `ภาพปกของ ${title}`,
    defaultAccessNote: "เพิ่มโน้ตการเข้าถึงเพื่อให้กลุ่มรู้วิธีใช้อัลบั้มนี้",
    noOwner: "ยังไม่มีเจ้าของ",
    tripLevel: "ระดับทริป",
    unsafeLinkBlocked: "บล็อกลิงก์ที่ไม่ปลอดภัย",
    openAlbumTitle: (title: string) => `เปิด ${title}`,
    openBlocked: "เปิดไม่ได้",
    editAlbum: "แก้ไขอัลบั้ม",
    inspectorLabel: "รายละเอียดอัลบั้มรูปภาพ",
    selectHint: "เลือกอัลบั้มเพื่อดูรายละเอียดการเข้าถึง",
    externalProviderNote: "สิทธิ์จริงถูกควบคุมโดยผู้ให้บริการภายนอก",
    blockedLink: "ลิงก์ถูกบล็อก",
    copy: "คัดลอก",
    openAlbum: "เปิดอัลบั้ม",
    access: "การเข้าถึง",
    noAccessNote: "ยังไม่มีโน้ตการเข้าถึง",
    owner: "เจ้าของ",
    noOwnerAssigned: "ยังไม่ได้กำหนดเจ้าของ",
    createdBy: (name: string) => `สร้างโดย ${name}`,
    relatedStops: "จุดที่เกี่ยวข้อง",
    addAlbumDialog: "เพิ่มอัลบั้ม",
    editAlbumDialog: "แก้ไขอัลบั้ม",
    close: "ปิด",
    titleField: "ชื่อ",
    providerField: "ผู้ให้บริการ",
    accessField: "การเข้าถึง",
    ownerField: "เจ้าของ",
    albumLinkField: "ลิงก์อัลบั้ม",
    dayField: "วัน",
    descriptionField: "คำอธิบาย",
    accessNoteField: "โน้ตการเข้าถึง",
    relatedItinerary: "แผนการเดินทางที่เกี่ยวข้อง",
    saveAlbum: "บันทึกอัลบั้ม",
    providers: {
      all: "ทุกอัลบั้ม",
      google_photos: "Google Photos",
      icloud: "iCloud",
      google_drive: "Google Drive",
      dropbox: "Dropbox",
      onedrive: "OneDrive",
      custom: "กำหนดเอง",
    },
    accessLabels: {
      view_only: "ดูอย่างเดียว",
      collaborative: "ร่วมแก้ไขได้",
      upload_request: "คำขออัปโหลด",
    },
  },
} as const;

export type PhotoCopy = typeof photoCopy.en | typeof photoCopy.th;
