import { describe, expect, it } from "vitest";
import { frontendRoot } from "../../project/contracts/project-contract.helpers";
import { readWorkspaceBoundarySources } from "./workspace-source-boundaries.sources";

describe("Sagittarius workspace command hook source boundaries", () => {
  it("keeps workspace commands, record inputs, photo albums, and expense drafts split by responsibility", () => {
    const {
      sagaCore,
      workspaceContextsHook,
      workspaceCommandsHook,
      workspaceCommandsParams,
      administrationHook,
      administrationCommandTypes,
      memberAdminActions,
      memberPatchActions,
      accountClaimActions,
      tripSettingsActions,
      itineraryBookingCommands,
      itineraryMoveCommands,
      itineraryMoveCommandTypes,
      itineraryBlockMoveCommand,
      itineraryDayMoveCommand,
      itineraryPathMoveCommand,
      itineraryInlineUpdateCommand,
      itineraryInlineUpdateInputs,
      itineraryReorderCommand,
      itineraryStopSaveCommands,
      itineraryStopCommandTypes,
      itineraryStopCreateCommand,
      itineraryStopUpdateCommand,
      bookingDocCommands,
      bookingCommandInputs,
      bookingCommandCreateInputs,
      bookingCommandDraftInputs,
      bookingCommandTicketInputs,
      taskActionsHook,
      taskCommandTypes,
      createTaskCommand,
      toggleTaskStatusCommand,
      suggestionActionsHook,
      suggestionCommandTypes,
      suggestSelectedStopCommand,
      reviewSuggestionCommand,
      stopNoteActionsHook,
      stopNoteCommandTypes,
      createStopNoteCommand,
      updateStopNoteCommand,
      deleteStopNoteCommand,
      recordCommandInputs,
      photoAlbumsHook,
      photoAlbumApiCommands,
      photoAlbumLocalCommands,
      photoAlbumsDomain,
      photoAlbumApi,
      photoAlbumLocal,
      photoAlbumQuery,
      expenseMutationCommands,
      expenseMutationCommandTypes,
      createExpenseCommand,
      deleteExpenseCommand,
      updateExpenseCommand,
      expenseDrafts,
      planningCommandsHook,
      planningCommandsParams,
      itineraryBookingCommandTypes,
      createItineraryBookingDraftCommand,
      saveItineraryBookingTicketCommand,
      unlinkItineraryBookingCommand,
      bookingDocUpdateCommands,
      bookingDocCommandTypes,
      createBookingDocCommand,
      deleteBookingDocCommand,
      bookingDocUpdateCommandTypes,
      bookingDocUpdateRunner,
      bookingDocTypeCommand,
      bookingDocQuickFieldCommand,
    } = readWorkspaceBoundarySources(frontendRoot);

    expect(sagaCore).not.toContain("useWorkspacePhotoAlbums");
    expect(sagaCore).not.toContain("useWorkspaceRecords");
    expect(sagaCore).toContain("useSagittariusWorkspaceContexts");
    expect(workspaceContextsHook).toContain("useWorkspaceCommands");
    expect(sagaCore).not.toContain("useWorkspaceAdministration");
    expect(sagaCore).not.toContain("useWorkspaceBookingCommands");
    expect(sagaCore).not.toContain("useWorkspaceItineraryCommands");
    expect(sagaCore).not.toContain("useWorkspaceItineraryImport");
    expect(workspaceCommandsHook).toContain("useWorkspacePlanningCommands");
    expect(workspaceCommandsHook).not.toContain("useWorkspaceBookingCommands");
    expect(workspaceCommandsHook).not.toContain("useWorkspaceItineraryCommands");
    expect(workspaceCommandsHook).not.toContain("useWorkspaceItineraryImport");
    expect(workspaceCommandsHook).toContain("useWorkspaceAdministration");
    expect(workspaceCommandsHook).not.toContain("type AdministrationParams");
    expect(workspaceCommandsParams).toContain("type AdministrationParams");
    expect(administrationHook).toContain("useWorkspaceAccountClaimActions");
    expect(administrationHook).toContain("useWorkspaceMemberAdminActions");
    expect(administrationHook).toContain("useWorkspaceTripSettingsActions");
    expect(administrationHook).not.toContain("interface UseWorkspaceAdministrationOptions");
    expect(administrationCommandTypes).toContain(
      "WorkspaceAdministrationCommandBaseParams",
    );
    expect(administrationCommandTypes).toContain(
      "UseWorkspaceAdministrationOptions",
    );
    expect(memberAdminActions).toContain("UseWorkspaceMemberAdminActionsOptions");
    expect(memberAdminActions).not.toContain(
      "interface UseWorkspaceMemberAdminActionsOptions",
    );
    expect(memberPatchActions).toContain("UseWorkspaceMemberPatchActionsOptions");
    expect(memberPatchActions).not.toContain(
      "interface UseWorkspaceMemberPatchActionsOptions",
    );
    expect(accountClaimActions).toContain("UseWorkspaceAccountClaimActionsOptions");
    expect(accountClaimActions).not.toContain(
      "interface UseWorkspaceAccountClaimActionsOptions",
    );
    expect(tripSettingsActions).toContain("UseWorkspaceTripSettingsActionsOptions");
    expect(tripSettingsActions).not.toContain(
      "interface UseWorkspaceTripSettingsActionsOptions",
    );
    expect(planningCommandsHook).toContain("useWorkspaceBookingCommands");
    expect(planningCommandsHook).toContain("useWorkspaceItineraryCommands");
    expect(planningCommandsHook).toContain("useWorkspaceItineraryImport");
    expect(planningCommandsHook).not.toContain("type BookingParams");
    expect(planningCommandsParams).toContain("type BookingParams");
    expect(sagaCore).not.toContain("useWorkspaceRecordState");
    expect(sagaCore).not.toContain("useWorkspaceRecordActions");
    expect(itineraryBookingCommands).toContain("useCreateItineraryBookingDraftCommand");
    expect(itineraryBookingCommands).toContain("useSaveItineraryBookingTicketCommand");
    expect(itineraryBookingCommands).toContain("useUnlinkItineraryBookingCommand");
    expect(itineraryBookingCommands).not.toContain("resolveItineraryBookingTicketCommandInput");
    expect(itineraryBookingCommands).not.toContain("syncItineraryDetailsWithBookingTicket");
    expect(itineraryBookingCommands).not.toContain("bookingDocInputFromRecord");
    expect(itineraryBookingCommands).not.toContain(
      "buildItineraryBookingTicketDocInput",
    );
    expect(itineraryBookingCommandTypes).toContain("UseWorkspaceItineraryBookingCommandsOptions");
    expect(itineraryMoveCommands).toContain("useWorkspaceItineraryReorderCommand");
    expect(itineraryMoveCommands).toContain(
      "useWorkspaceItineraryBlockMoveCommand",
    );
    expect(itineraryMoveCommands).toContain("useWorkspaceItineraryDayMoveCommand");
    expect(itineraryMoveCommands).toContain("useWorkspaceItineraryPathMoveCommand");
    expect(itineraryMoveCommands).not.toContain("moveTripItemIntoPlanBlock");
    expect(itineraryMoveCommands).not.toContain("moveTripItemToDay");
    expect(itineraryMoveCommandTypes).toContain(
      "UseWorkspaceItineraryMoveCommandsParams",
    );
    expect(itineraryMoveCommandTypes).toContain(
      "UseWorkspaceItineraryReorderCommandParams",
    );
    expect(itineraryMoveCommandTypes).toContain(
      "UseWorkspaceItineraryPathMoveCommandParams",
    );
    expect(itineraryBlockMoveCommand).toContain("moveTripItemIntoPlanBlock");
    expect(itineraryBlockMoveCommand).toContain(
      "buildWorkspaceMoveItemPatchRequest",
    );
    expect(itineraryDayMoveCommand).toContain("moveTripItemToDay");
    expect(itineraryDayMoveCommand).toContain(
      "buildWorkspaceMoveItemToDayPatchRequest",
    );
    expect(itineraryPathMoveCommand).toContain(
      "buildWorkspacePathMovePlacement",
    );
    expect(itineraryPathMoveCommand).not.toContain(
      "interface UseWorkspaceItineraryPathMoveCommandParams",
    );
    expect(itineraryInlineUpdateCommand).toContain("@/src/trip/itinerary-items");
    expect(itineraryInlineUpdateCommand).not.toContain(
      "@/src/features/itinerary/lib/inline-itinerary-item-patch",
    );
    expect(itineraryInlineUpdateInputs).toContain("@/src/trip/itinerary-items");
    expect(itineraryInlineUpdateInputs).not.toContain(
      "@/src/features/itinerary/lib/inline-itinerary-item-patch",
    );
    expect(itineraryReorderCommand).toContain("buildWorkspaceReorderApiInput");
    expect(itineraryReorderCommand).not.toContain(
      "interface UseWorkspaceItineraryReorderCommandParams",
    );
    expect(itineraryStopSaveCommands).toContain(
      "useWorkspaceItineraryStopCreateCommand",
    );
    expect(itineraryStopSaveCommands).toContain(
      "useWorkspaceItineraryStopUpdateCommand",
    );
    expect(itineraryStopSaveCommands).not.toContain(
      "interface UseWorkspaceItineraryStopSaveCommandsParams",
    );
    expect(itineraryStopCommandTypes).toContain(
      "WorkspaceItineraryStopCommandBaseParams",
    );
    expect(itineraryStopCommandTypes).toContain(
      "UseWorkspaceItineraryStopSaveCommandsParams",
    );
    expect(itineraryStopCommandTypes).toContain(
      "@/src/features/itinerary/domain/stop-form-values",
    );
    expect(itineraryStopCommandTypes).not.toContain(
      "@/src/features/itinerary/components",
    );
    expect(itineraryStopCreateCommand).toContain("buildWorkspaceCreatedStop");
    expect(itineraryStopCreateCommand).toContain("placeCreatedWorkspaceStop");
    expect(itineraryStopCreateCommand).not.toContain(
      "interface UseWorkspaceItineraryStopCreateCommandParams",
    );
    expect(itineraryStopUpdateCommand).toContain("buildWorkspaceUpdatedStop");
    expect(itineraryStopUpdateCommand).toContain("placeUpdatedWorkspaceStop");
    expect(itineraryStopUpdateCommand).not.toContain(
      "interface UseWorkspaceItineraryStopUpdateCommandParams",
    );
    expect(createItineraryBookingDraftCommand).toContain("buildItineraryBookingDraftInput");
    expect(createItineraryBookingDraftCommand).toContain("findDuplicateBookingDoc");
    expect(saveItineraryBookingTicketCommand).toContain(
      "resolveItineraryBookingTicketCommandInput",
    );
    expect(saveItineraryBookingTicketCommand).toContain("syncItineraryDetailsWithBookingTicket");
    expect(unlinkItineraryBookingCommand).toContain("bookingDocInputFromRecord");
    expect(unlinkItineraryBookingCommand).toContain("clearItineraryBookingTicketDetails");
    expect(bookingDocCommands).toContain("useCreateBookingDocCommand");
    expect(bookingDocCommands).toContain("useDeleteBookingDocCommand");
    expect(bookingDocCommands).toContain("useWorkspaceBookingDocUpdateCommands");
    expect(bookingDocCommands).not.toContain("buildWorkspaceBookingDocCreateInput");
    expect(bookingDocCommands).not.toContain("removeBookingDocFromTrip");
    expect(bookingDocCommands).not.toContain("normalizeBookingDocTitle");
    expect(bookingDocCommands).not.toContain("resolveBookingDocCreateTripPlanId");
    expect(bookingDocCommandTypes).toContain("UseWorkspaceBookingDocCommandsOptions");
    expect(createBookingDocCommand).toContain("buildWorkspaceBookingDocCreateInput");
    expect(createBookingDocCommand).toContain("buildCreateBookingDocRequest");
    expect(createBookingDocCommand).toContain("createLocalBookingDoc");
    expect(deleteBookingDocCommand).toContain("removeBookingDocFromTrip");
    expect(bookingDocUpdateCommands).toContain("useBookingDocUpdateRunner");
    expect(bookingDocUpdateCommands).toContain("useBookingDocTypeCommand");
    expect(bookingDocUpdateCommands).toContain("useBookingDocQuickFieldCommand");
    expect(bookingDocUpdateCommands).not.toContain("runWorkspaceVersionConflictRetry");
    expect(bookingDocUpdateCommands).not.toContain("bookingDocInputFromRecord");
    expect(bookingDocUpdateCommands).not.toContain("bookingDocQuickFieldsInputFromRecord");
    expect(bookingDocUpdateCommandTypes).toContain("UseWorkspaceBookingDocUpdateCommandsOptions");
    expect(bookingDocUpdateRunner).toContain("runWorkspaceVersionConflictRetry");
    expect(bookingDocUpdateRunner).toContain("queueKeyedUpdate");
    expect(bookingDocUpdateRunner).toContain("updateLocalBookingDocInTrip");
    expect(bookingDocTypeCommand).toContain("bookingDocInputFromRecord");
    expect(bookingDocQuickFieldCommand).toContain("bookingDocQuickFieldsInputFromRecord");
    expect(bookingCommandInputs).toContain("./booking-command-create-inputs");
    expect(bookingCommandInputs).toContain("./booking-command-draft-inputs");
    expect(bookingCommandInputs).toContain("./booking-command-ticket-inputs");
    expect(bookingCommandInputs).not.toContain("findDuplicateBookingDoc");
    expect(bookingCommandCreateInputs).toContain("buildWorkspaceBookingDocCreateInput");
    expect(bookingCommandCreateInputs).toContain("normalizeBookingDocTitle");
    expect(bookingCommandCreateInputs).toContain("resolveBookingDocCreateTripPlanId");
    expect(bookingCommandDraftInputs).toContain("buildItineraryBookingDraftInput");
    expect(bookingCommandDraftInputs).toContain("bookingDraftTitleForItineraryItem");
    expect(bookingCommandTicketInputs).toContain("buildItineraryBookingTicketDocInput");
    expect(bookingCommandTicketInputs).toContain("resolveItineraryBookingTicketCommandInput");
    expect(bookingCommandTicketInputs).toContain("findDuplicateBookingDoc");
    expect(taskActionsHook).toContain("useCreateWorkspaceTaskCommand");
    expect(taskActionsHook).toContain("useToggleWorkspaceTaskStatusCommand");
    expect(taskActionsHook).not.toContain("buildWorkspaceTaskCreateDraft");
    expect(taskActionsHook).not.toContain("buildToggleTaskStatusRequest");
    expect(taskCommandTypes).toContain("WorkspaceTaskCommandBaseParams");
    expect(createTaskCommand).toContain("buildWorkspaceTaskCreateDraft");
    expect(createTaskCommand).toContain("buildCreateTaskRequest");
    expect(toggleTaskStatusCommand).toContain("buildToggleTaskStatusRequest");
    expect(taskActionsHook).not.toContain("tripPlanIdForRecord");
    expect(suggestionActionsHook).toContain("useSuggestSelectedStopCommand");
    expect(suggestionActionsHook).toContain("useReviewWorkspaceSuggestionCommand");
    expect(suggestionActionsHook).not.toContain("buildCreateEditSuggestionRequest");
    expect(suggestionActionsHook).not.toContain("approveSuggestion");
    expect(suggestionCommandTypes).toContain("WorkspaceSuggestionCommandBaseParams");
    expect(suggestSelectedStopCommand).toContain(
      "buildCreateEditSuggestionRequest",
    );
    expect(suggestSelectedStopCommand).toContain("createLocalEditSuggestion");
    expect(reviewSuggestionCommand).toContain("approveSuggestion");
    expect(reviewSuggestionCommand).toContain("rejectSuggestionById");
    expect(stopNoteActionsHook).toContain("useCreateWorkspaceStopNoteCommand");
    expect(stopNoteActionsHook).toContain("useUpdateWorkspaceStopNoteCommand");
    expect(stopNoteActionsHook).toContain("useDeleteWorkspaceStopNoteCommand");
    expect(stopNoteActionsHook).not.toContain("buildWorkspaceStopNoteCreateInput");
    expect(stopNoteActionsHook).not.toContain("buildPatchStopNoteRequest");
    expect(stopNoteCommandTypes).toContain("WorkspaceStopNoteCommandBaseParams");
    expect(createStopNoteCommand).toContain("buildWorkspaceStopNoteCreateInput");
    expect(createStopNoteCommand).toContain("buildCreateStopNoteRequest");
    expect(updateStopNoteCommand).toContain("buildPatchStopNoteRequest");
    expect(deleteStopNoteCommand).toContain("deleteLocalStopNote");
    expect(stopNoteActionsHook).not.toContain("tripPlanIdForRecord");
    expect(recordCommandInputs).toContain("tripPlanIdForRecord");
    expect(photoAlbumsHook).toContain("normalizePhotoAlbumCreateInput");
    expect(photoAlbumsHook).toContain("useWorkspaceApiPhotoAlbumCommands");
    expect(photoAlbumsHook).toContain("useWorkspaceLocalPhotoAlbumCommands");
    expect(photoAlbumsHook).not.toContain("const title = input.title.trim()");
    expect(photoAlbumsHook).not.toContain("const url = input.url.trim()");
    expect(photoAlbumApiCommands).toContain("isVersionConflict");
    expect(photoAlbumApiCommands).toContain("buildCreatePhotoAlbumRequest");
    expect(photoAlbumApiCommands).toContain("buildPatchPhotoAlbumRequest");
    expect(photoAlbumLocalCommands).toContain("createLocalPhotoAlbum");
    expect(photoAlbumLocalCommands).toContain("updateLocalPhotoAlbumInTrip");
    expect(photoAlbumsDomain).toContain("./photo-album-api");
    expect(photoAlbumsDomain).toContain("./photo-album-local");
    expect(photoAlbumsDomain).toContain("./photo-album-query");
    expect(photoAlbumApi).toContain("serializePhotoAlbumInputForApi");
    expect(photoAlbumLocal).toContain("normalizePhotoAlbumCreateInput");
    expect(photoAlbumLocal).toContain("createLocalPhotoAlbum");
    expect(photoAlbumQuery).toContain("buildPhotoAlbumSummary");
    expect(expenseMutationCommands).toContain("useCreateWorkspaceExpenseCommand");
    expect(expenseMutationCommands).toContain("useDeleteWorkspaceExpenseCommand");
    expect(expenseMutationCommands).toContain("useUpdateWorkspaceExpenseCommand");
    expect(expenseMutationCommands).not.toContain(
      "resolveExpenseCreateDraftTripPlanId",
    );
    expect(expenseMutationCommands).not.toContain("buildExpenseUpdateDraft");
    expect(expenseMutationCommandTypes).toContain("UseWorkspaceExpenseMutationCommandsOptions");
    expect(createExpenseCommand).toContain("buildExpenseCreateDrafts");
    expect(createExpenseCommand).toContain(
      "resolveExpenseCreateDraftTripPlanId",
    );
    expect(deleteExpenseCommand).toContain("removeExpenseFromTrip");
    expect(updateExpenseCommand).toContain("buildExpenseUpdateDraft");
    expect(updateExpenseCommand).toContain("buildPatchExpenseRequest");
    expect(expenseDrafts).toContain("resolveExpenseCreateDraftTripPlanId");
  });
});
