export const workspaceTripContextBoundarySourcePaths = {
  workspaceRecordsHook: "src/trip/workspace/use-trip-workspace-records.ts",
  itineraryViewModelHook: "src/trip/workspace/sagittarius-app/hooks/use-workspace-itinerary-view-model.ts",
  apiClientsHook: "src/trip/workspace/sagittarius-app/hooks/use-workspace-api-clients.ts",
  setupContextHook: "src/trip/workspace/sagittarius-app/hooks/use-workspace-setup-context.ts",
  setupContextParams: "src/trip/workspace/sagittarius-app/hooks/use-workspace-setup-context-params.ts",
  dataContextHook: "src/trip/workspace/sagittarius-app/hooks/use-workspace-data-context.ts",
  backendExpenseSummaryHook: "src/trip/workspace/sagittarius-app/hooks/use-workspace-backend-expense-summary.ts",
  cockpitReplacementHook: "src/trip/workspace/sagittarius-app/hooks/use-workspace-cockpit-replacement.ts",
  memberContextHook: "src/trip/workspace/sagittarius-app/hooks/use-workspace-member-context.ts",
  navigationContextHook: "src/trip/workspace/sagittarius-app/hooks/use-workspace-navigation-context.ts",
  planningContextHook: "src/trip/workspace/sagittarius-app/hooks/use-workspace-planning-context.ts",
  planningRecordsContextHook: "src/trip/workspace/sagittarius-app/hooks/use-workspace-planning-records-context.ts",
  planningCommandsHook: "src/trip/workspace/sagittarius-app/hooks/use-workspace-planning-commands.ts",
  planningCommandsParams: "src/trip/workspace/sagittarius-app/hooks/use-workspace-planning-commands-params.ts",
  workspaceCommandsHook: "src/trip/workspace/sagittarius-app/hooks/use-workspace-commands.ts",
  workspaceCommandsParams: "src/trip/workspace/sagittarius-app/hooks/use-workspace-commands-params.ts",
} as const;
