const importAndRoutingTerms = [
  "function shouldUseApiItineraryImport",
  "interface PendingItineraryImport",
  "resolveViewFromPath",
  "navigatedView",
  "function buildImportItineraryRequest",
  "function resolveCreatedImportId",
  "function slugifyFilePart",
  "function resolveJoinPostAuthReturnTo",
] as const;

const workspaceUiStateTerms = [
  "setContextRailMounted",
  "setSidebarCollapsed",
  "setToastDismissed",
  "setToastDismissing",
  "workspaceToastDismissClassName",
  "portalLoadingCardClassName",
  "function TripAccessLoadingFrame",
  "function WorkspaceToast",
  "Role preview",
  "WorkspaceRolePreview",
] as const;

const fixtureAndRecordTerms = [
  "@/src/trip/testing/fixtures/trip-fixtures",
  "tripFixtureSuggestions",
  "tripFixtureTasks",
  "tripFixtureStopNotes",
  "function selectTripPlanRecords",
  "function tripPlanIdForRecord",
  "buildItineraryCommitmentsByItemId",
  "function buildItineraryCommitmentsByItemId",
  "buildExpenseSummary",
  "useState<{ tripPlanId: string; summary: ExpenseSummary } | null>",
] as const;

const sessionAndAuthTerms = [
  "function loadPersistedParticipantSession",
  "function clearParticipantSession",
  "function loadPersistedTrip",
  "function persistTripDraft",
  "function replaceTripParticipant",
  "function appendTripParticipant",
  "function buildCreateMemberRequest",
  "function buildPatchMemberRoleRequest",
  "function buildPatchMemberAccessStatusRequest",
  "function buildPatchMemberPasswordRequest",
  "function buildUpdatePresenceRequest",
  "function isUnauthenticated",
  "function isForbidden",
  "function isAuthFailure",
] as const;

const localIdTerms = [
  "function nextLocalItemId",
  "function nextLocalSuggestionId",
  "function nextLocalTaskId",
  "function nextLocalStopNoteId",
  "function nextLocalBookingDocId",
  "function nextLocalPhotoAlbumId",
  "function nextLocalPlanVariantId",
  "function nextLocalExpenseId",
  "function nextClientMutationId",
] as const;

const tripPlanTerms = [
  "function resolveSelectedTripPlanId",
  "function rememberSelectedTripPlanId",
  "function normalizeTripPlanAliases",
  "function buildSetMainTripPlanRequest",
  "function buildPatchTripPlanStatusRequest",
  "function buildRenameTripPlanRequest",
  "function buildCreateTripPlanRequest",
  "function updateTripPlanInTrip",
  "function mergePublishedTripPlan",
  "function setLocalMainTripPlan",
  "function createLocalTripPlan",
  "function normalizeTripPlanSummary",
  "function planStatusForLegacyKind",
  "function legacyKindForPlanStatus",
] as const;

const itineraryTerms = [
  "useState<ItineraryPathSelection>",
  "function changeTripPath",
  "function toggleShowAllPaths",
  "past: Trip[]",
  "future: Trip[]",
  "function daysBetweenIsoDates",
  "function shiftIsoDate",
  "function itineraryDateTime",
  "function buildItineraryItemDraft",
  "function buildUpdatedItineraryItem",
  "function appendItineraryItemToTrip",
  "function appendItineraryItemPlacement",
  "function mergeCreatedItineraryItemIntoTrip",
  "function mergeUpdatedItineraryBranchIntoTrip",
  "function shiftItineraryItemsToStartDate",
  "function buildInlineItineraryItemPatch",
  "function buildInlineItineraryItemPatchRequest",
  "function buildCreateItineraryItemRequest",
  "function buildPatchItineraryItemRequest",
  "function buildMoveItineraryItemRequest",
  "function buildMoveItineraryItemToDayRequest",
  "function buildReorderItineraryItemsRequest",
  "function buildShiftItineraryItemDayRequest",
  "function normalizeInlineTimePatch",
  "function buildMapLink",
  "function buildMapPlaceResolutionRequest",
  "function mapResolutionPlaceHint",
  "function mapResolutionActivity",
  "function resolveStopPlace",
  "function locationFieldsFromCandidate",
  "function readItineraryDetailString",
  "async function patchApiItineraryBranchItems",
  "function selectedItineraryPathIdForDay",
  "function updateItineraryPathSelection",
  "function itineraryItemPathFieldsForTarget",
  "function getNextSortOrder",
  "function getNextChildSortOrder",
  "function normalizeStopHierarchyValues",
  "function replaceItineraryItem",
  "function replaceItineraryItems",
  "function deleteItineraryItemFromTrip",
  "function moveTripItem",
  "function moveTripItemToDay",
  "function moveTripItemIntoPlanBlock",
  "function hasDescendantItem",
] as const;

const bookingTerms = [
  "function createLocalBookingDoc",
  "function replaceBookingDocInTrip",
  "function updateLocalBookingDocInTrip",
  "function removeBookingDocFromTrip",
  "function normalizeBookingDocTitle",
  "function resolveBookingDocCreateTripPlanId",
  "function bookingDocQuickFieldsInputFromRecord",
  "function serializeBookingDocInputForApi",
  "function normalizeBookingDocDateTimeForApi",
  "function bookingTypeForItineraryItem",
  "function syncItineraryDetailsWithBookingTicket",
  "function clearItineraryBookingTicketDetails",
  "function findDuplicateBookingDoc",
  "function buildCreateBookingDocRequest",
  "function buildPatchBookingDocRequest",
  "function bookingDraftTitleForItineraryItem",
  "function bookingTypeForExpenseEstimate",
  "function bookingDocInputForExpenseEstimate",
  "function bookingDraftDetailsForItineraryItem",
  "function bookingDraftTimeWindowForItineraryItem",
] as const;

const photoAlbumTerms = [
  "function createLocalPhotoAlbum",
  "function buildCreatePhotoAlbumRequest",
  "function buildPatchPhotoAlbumRequest",
  "function appendPhotoAlbumToTrip",
  "function replacePhotoAlbumInTrip",
  "function updateLocalPhotoAlbum",
  "function updateLocalPhotoAlbumInTrip",
  "function removePhotoAlbumFromTrip",
  'from "@/src/trip/photo-albums"',
  "async function createPhotoAlbum",
  "async function updatePhotoAlbum",
  "async function deletePhotoAlbum",
  "function serializePhotoAlbumInputForApi",
] as const;

const expenseTerms = [
  "function buildExpenseCreateDrafts",
  "function buildCreateExpenseRequest",
  "function buildPatchExpenseRequest",
  "function appendExpensesToTrip",
  "function appendLocalExpensesToTrip",
  "function buildExpenseUpdateDraft",
  "function replaceExpenseInTrip",
  "function updateLocalExpenseInTrip",
  "function removeExpenseFromTrip",
  "function expenseReminderRequestForSuggestion",
  "function buildExpenseReminderRequest",
  "function recordLocalExpenseReminderInTrip",
  "function normalizeExpenseRepeatCount",
  "function repeatExpenseLineItems",
] as const;

const recordAndSettingsTerms = [
  "function buildCreateEditSuggestionRequest",
  "function createLocalEditSuggestion",
  "function rejectSuggestionById",
  "function buildPatchDailyBriefingRequest",
  "function applyDailyBriefingOverrides",
  "buildFallbackBriefings",
  "buildPatchDailyBriefingRequest",
  "function buildPatchTripSettingsRequest",
  "function applyTripSettingsToTrip",
  "function mergePatchedTripSettings",
  "function createLocalStopNote",
  "function buildCreateStopNoteRequest",
  "function buildPatchStopNoteRequest",
  "function appendStopNote",
  "function createLocalStopNoteInList",
  "function replaceStopNote",
  "function updateLocalStopNote",
  "function removeStopNote",
  "function deleteLocalStopNote",
  "function buildTaskCreateDraft",
  "function buildCreateTaskRequest",
  "function createLocalTask",
  "function appendTask",
  "function createLocalTaskInList",
  "function replaceTask",
  "function toggledTaskStatus",
  "function buildToggleTaskStatusRequest",
  "function toggleLocalTaskStatus",
  "function replaceSuggestionById",
  "function deriveTripCountriesFromDestination",
] as const;

const legacyComponentTerms = [
  'from "@/src/components/OverviewPage"',
  'from "@/src/components/TimelineView"',
] as const;

export const sagittariusAppBlockedBoundaryTerms = [
  ...importAndRoutingTerms,
  ...workspaceUiStateTerms,
  ...fixtureAndRecordTerms,
  ...sessionAndAuthTerms,
  ...localIdTerms,
  ...tripPlanTerms,
  ...itineraryTerms,
  ...bookingTerms,
  ...photoAlbumTerms,
  ...expenseTerms,
  ...recordAndSettingsTerms,
  ...legacyComponentTerms,
] as const;
