import type { Locale } from "@/src/i18n/types";

export function emptyText(locale: Locale): string {
  return locale === "th" ? "ยังไม่มีข้อมูล" : "No data yet";
}

export function weatherDrawerCopy(locale: Locale) {
  return locale === "th"
    ? {
        regionLabel: "รายละเอียดพยากรณ์อากาศ",
        close: "ปิด",
        weather: "สภาพอากาศ",
        feelsLike: "รู้สึกเหมือน",
        humidity: "ความชื้น",
        wind: "ลม",
        windGust: "ลมกระโชก",
        rain: "ฝน",
        rainAmount: "ปริมาณฝน",
        rainHours: "ช่วงฝน",
        uv: "UV",
        visibilityMin: "ทัศนวิสัยต่ำสุด",
        cloudCover: "เมฆ",
        sunrise: "พระอาทิตย์ขึ้น",
        sunset: "พระอาทิตย์ตก",
        tripImpact: "ผลต่อแผนวันนี้",
        impactRain: "พกร่ม + เผื่อเวลาให้ช่วงกลางแจ้ง",
        impactUv: "เตรียมกันแดด + แทรกจุดพักในร่ม",
        impactWind: "เช็คจุดริมน้ำหรือกิจกรรมกลางแจ้งก่อนออก",
        impactDefault: "อากาศจัดการได้ ใช้ itinerary เป็นหลัก",
        outfitAdvice: "คำแนะนำการแต่งตัว",
        pendingTitle: "กำลังซิงก์พยากรณ์",
        pendingBody: "เช็คอีกครั้งก่อนออกเดินทาง",
        pendingStatus: "ยังไม่มีข้อมูล",
        holiday: "วันหยุด",
        festival: "เทศกาล",
        dailyFacts: "เกร็ดประจำวัน",
        supportingDetails: "รายละเอียดเพิ่มเติม",
        organizerNotes: "โน้ตผู้จัดทริป",
        outfitOverride: "ปรับคำแนะนำการแต่งตัว",
        festivalOverride: "ปรับโน้ตเทศกาล",
        factsOverride: "ปรับเกร็ดประจำวัน",
        save: "บันทึก",
        noSource: "ไม่มีแหล่งข้อมูล",
        fetched: "อัปเดต",
        expires: "ใช้ได้ถึง",
      }
    : {
        regionLabel: "Weather briefing",
        close: "Close",
        weather: "Weather",
        feelsLike: "Feels like",
        humidity: "Humidity",
        wind: "Wind",
        windGust: "Wind gust",
        rain: "Rain",
        rainAmount: "Rain amount",
        rainHours: "Rain hours",
        uv: "UV",
        visibilityMin: "Min visibility",
        cloudCover: "Cloud cover",
        sunrise: "Sunrise",
        sunset: "Sunset",
        tripImpact: "Trip impact",
        impactRain: "Umbrella + buffer for outdoor stops.",
        impactUv: "Sun protection + shade breaks.",
        impactWind: "Recheck waterfront or outdoor stops.",
        impactDefault: "Manageable. Follow itinerary timing.",
        outfitAdvice: "Outfit advice",
        pendingTitle: "Forecast syncing",
        pendingBody: "Check again before departure.",
        pendingStatus: "No data yet",
        holiday: "Holiday",
        festival: "Festival",
        dailyFacts: "Daily facts",
        supportingDetails: "Supporting details",
        organizerNotes: "Organizer notes",
        outfitOverride: "Outfit advice override",
        festivalOverride: "Festival note override",
        factsOverride: "Facts note override",
        save: "Save",
        noSource: "No source",
        fetched: "Updated",
        expires: "valid until",
      };
}
