import { useWorkspaceBookingCommands } from "./use-workspace-booking-commands";
import { useWorkspaceExpenses } from "./use-workspace-expenses";
import { useWorkspaceItineraryCommands } from "./use-workspace-itinerary-commands";
import { useWorkspaceItineraryImport } from "./use-workspace-itinerary-import";
import type { UseWorkspacePlanningCommandsParams } from "./use-workspace-planning-commands-params";

export function useWorkspacePlanningCommands({
  activeMemberId,
  canCreateExpenses,
  canEdit,
  canEditBookings,
  canEditExpenses,
  canSaveItineraryErrorMessage,
  commitTrip,
  dialogState,
  effectivePlaceResolver,
  isApiMode,
  latestTripRef,
  nextClientMutationId,
  participantSession,
  pathOptions,
  pathSelection,
  planItems,
  refreshBackendExpenseSummary,
  replaceApiTrip,
  replaceCockpitFromApi,
  resolvedApiClient,
  selectedDay,
  selectedItemId,
  selectedTripPlanId,
  setBackendExpenseSummary,
  setContextRailPreferredTab,
  setContextRailVisibility,
  setDialogState,
  setSelectedItemId,
  setStopNotes,
  setStopPlaceResolution,
  setTasks,
  setTripPlanError,
  stopNotes,
  tasks,
  trip,
  tripPlanErrorMessage,
  updateApiTrip,
}: UseWorkspacePlanningCommandsParams) {
  const itineraryCommands = useWorkspaceItineraryCommands({
    canEdit,
    canSaveItineraryErrorMessage,
    currentMemberId: activeMemberId,
    dialogState,
    effectivePlaceResolver,
    isApiMode,
    latestTripRef,
    nextClientMutationId,
    pathOptions,
    pathSelection,
    planItems,
    participantSession,
    resolvedApiClient,
    replaceApiTrip,
    replaceCockpitFromApi,
    selectedDay,
    selectedItemId,
    selectedTripPlanId,
    setContextRailVisibility,
    setDialogState,
    setSelectedItemId,
    setStopPlaceResolution,
    setTripPlanError,
    tripPlanErrorMessage,
    trip,
    commitTrip,
    updateApiTrip,
  });

  const bookingCommands = useWorkspaceBookingCommands({
    apiClient: resolvedApiClient,
    canEditBookings,
    commitTrip,
    currentMemberId: activeMemberId,
    isApiMode,
    latestTripRef,
    nextClientMutationId,
    participantSession,
    replaceApiTrip,
    replaceCockpitFromApi,
    selectedTripPlanId,
    setContextRailPreferredTab,
    setSelectedItemId,
    trip,
    updateItineraryItemInline: itineraryCommands.updateItineraryItemInline,
  });

  const expenseCommands = useWorkspaceExpenses({
    apiClient: resolvedApiClient,
    canCreateExpenses,
    canEditBookings,
    canEditExpenses,
    commitTrip,
    createBookingDoc: bookingCommands.createBookingDoc,
    currentMemberId: activeMemberId,
    isApiMode,
    participantSession,
    refreshBackendExpenseSummary,
    selectedTripPlanId,
    setBackendExpenseSummary,
    trip,
    updateApiTrip,
  });

  const importCommands = useWorkspaceItineraryImport({
    apiClient: resolvedApiClient,
    canEdit,
    commitTrip,
    isApiMode,
    participantSession,
    planItems,
    selectedTripPlanId,
    setBackendExpenseSummary,
    setContextRailVisibility,
    setSelectedItemId,
    setStopNotes,
    setTasks,
    stopNotes,
    tasks,
    trip,
    updateApiTrip,
  });

  return {
    ...itineraryCommands,
    ...bookingCommands,
    ...expenseCommands,
    ...importCommands,
  };
}
