import { useWorkspaceAdministration } from "./use-workspace-administration";
import { useWorkspaceItineraryUiActions } from "./use-workspace-itinerary-ui-actions";
import { useWorkspaceParticipantSessionActions } from "./use-workspace-participant-session-actions";
import { useWorkspacePlanningCommands } from "./use-workspace-planning-commands";

type AdministrationParams = Parameters<typeof useWorkspaceAdministration>[0];
type ItineraryUiParams = Parameters<typeof useWorkspaceItineraryUiActions>[0];
type ParticipantSessionParams = Parameters<
  typeof useWorkspaceParticipantSessionActions
>[0];
type PlanningParams = Parameters<typeof useWorkspacePlanningCommands>[0];

type UseWorkspaceCommandsParams =
  PlanningParams &
  Omit<AdministrationParams, "currentMemberId" | "resolvedApiClient"> &
  Omit<ItineraryUiParams, "createStop"> &
  ParticipantSessionParams & {
    currentMemberId: string;
    resolvedApiClient:
      | PlanningParams["resolvedApiClient"]
      | AdministrationParams["resolvedApiClient"];
  };

export function useWorkspaceCommands({
  accountClient,
  accountSession,
  activeMemberId,
  canEdit,
  canEditBookings,
  canEditExpenses,
  canManagePeople,
  canSaveItineraryErrorMessage,
  commitTrip,
  currentMemberId,
  dialogState,
  effectivePlaceResolver,
  initialTrip,
  isApiMode,
  latestTripRef,
  nextClientMutationId,
  participantSession,
  pathOptions,
  pathSelection,
  planItems,
  refreshBackendExpenseSummary,
  replaceApiTrip,
  replaceCockpitFromApi,
  replaceWorkspacePath,
  resetTrip,
  resolvedApiClient,
  routeTripId,
  selectedDay,
  selectedItemId,
  selectedTripPlanId,
  setAccessError,
  setAccountClaimState,
  setBackendExpenseSummary,
  setContextRailPreferredTab,
  setContextRailVisibility,
  setCurrentMemberId,
  setDialogDeleteItem,
  setDialogState,
  setIsCockpitLoaded,
  setJoinInviteToken,
  setParticipantSession,
  setSelectedItemId,
  setStopNotes,
  setStopPlaceResolution,
  setTasks,
  setTripPlanError,
  stopNotes,
  tasks,
  trip,
  tripPlanErrorMessage,
  updateApiTrip,
}: UseWorkspaceCommandsParams) {
  const {
    addStop,
    addSubActivity,
    applyPendingItineraryImport,
    changeBookingDocQuickFields,
    changeBookingDocType,
    clearPendingItineraryImport,
    createBookingDoc,
    createExpense,
    createItineraryBookingDraft,
    createStop,
    deleteBookingDoc,
    deleteExpense,
    deleteStop,
    duplicateExpenseAsEstimate,
    importItineraryError,
    moveItemToPath,
    pendingItineraryImport,
    recordPaybackReminder,
    resolveMissingMapCoordinates,
    saveItineraryBookingTicket,
    unlinkBookingFromItineraryItem,
    updateBookingDoc,
    updateExpense,
    updateItineraryItemInline,
    updateSelectedStop,
  } = useWorkspacePlanningCommands({
    activeMemberId,
    canEdit,
    canEditBookings,
    canEditExpenses,
    canSaveItineraryErrorMessage,
    commitTrip,
    dialogState,
    effectivePlaceResolver,
    isApiMode,
    latestTripRef,
    nextClientMutationId,
    participantSession,
    pathOptions,
    pathSelection,
    planItems,
    refreshBackendExpenseSummary,
    replaceApiTrip,
    replaceCockpitFromApi,
    resolvedApiClient,
    selectedDay,
    selectedItemId,
    selectedTripPlanId,
    setBackendExpenseSummary,
    setContextRailPreferredTab,
    setContextRailVisibility,
    setDialogState,
    setSelectedItemId,
    setStopNotes,
    setStopPlaceResolution,
    setTasks,
    setTripPlanError,
    stopNotes,
    tasks,
    trip,
    tripPlanErrorMessage,
    updateApiTrip,
  });

  const {
    changeMemberAccessStatus,
    changeMemberPassword,
    changeMemberRole,
    claimCurrentMemberToAccount,
    createMember,
    resetMemberClaim,
    saveTripSettings,
    rotateJoinInviteToken,
    transferOwnerToAccountMember,
  } = useWorkspaceAdministration({
    accountClient,
    accountSession,
    canManagePeople,
    commitTrip,
    currentMemberId,
    isApiMode,
    participantSession,
    resolvedApiClient,
    setAccountClaimState,
    setJoinInviteToken,
    trip,
    replaceCockpitFromApi,
    updateApiTrip,
  });

  const {
    deleteSelectedStop,
    editItem,
    openItemDetails,
    promoteFoodRecommendation,
    selectItem,
  } = useWorkspaceItineraryUiActions({
    canEdit,
    createStop,
    dialogState,
    setContextRailPreferredTab,
    setContextRailVisibility,
    setDialogDeleteItem,
    setDialogState,
    setSelectedItemId,
    setStopPlaceResolution,
    trip,
  });

  const {
    authenticateParticipant,
    leaveParticipantSession,
    replaceTripFromJoin,
  } = useWorkspaceParticipantSessionActions({
    initialTrip,
    isApiMode,
    replaceWorkspacePath,
    resetTrip,
    routeTripId,
    setAccessError,
    setContextRailVisibility,
    setCurrentMemberId,
    setIsCockpitLoaded,
    setParticipantSession,
  });

  return {
    addStop,
    addSubActivity,
    applyPendingItineraryImport,
    authenticateParticipant,
    changeBookingDocQuickFields,
    changeBookingDocType,
    changeMemberAccessStatus,
    changeMemberPassword,
    changeMemberRole,
    claimCurrentMemberToAccount,
    clearPendingItineraryImport,
    createBookingDoc,
    createExpense,
    createItineraryBookingDraft,
    createMember,
    createStop,
    deleteBookingDoc,
    deleteExpense,
    deleteSelectedStop,
    deleteStop,
    duplicateExpenseAsEstimate,
    editItem,
    importItineraryError,
    leaveParticipantSession,
    moveItemToPath,
    openItemDetails,
    pendingItineraryImport,
    promoteFoodRecommendation,
    recordPaybackReminder,
    replaceTripFromJoin,
    resetMemberClaim,
    resolveMissingMapCoordinates,
    rotateJoinInviteToken,
    saveItineraryBookingTicket,
    saveTripSettings,
    selectItem,
    transferOwnerToAccountMember,
    unlinkBookingFromItineraryItem,
    updateBookingDoc,
    updateExpense,
    updateItineraryItemInline,
    updateSelectedStop,
  };
}
