import {
  initialSelectedTripPlanId,
  rememberSelectedTripPlanId,
  resolveSelectedTripPlanId,
} from "@/src/trip/workspace/selected-trip-plan";
import { useWorkspaceApiCockpitEffects } from "./use-workspace-api-cockpit-effects";
import { useWorkspaceCockpitReplacement } from "./use-workspace-cockpit-replacement";
import { useWorkspacePlanningRecordsContext } from "./use-workspace-planning-records-context";
import type { UseWorkspacePlanningContextParams } from "./use-workspace-planning-context-params";
import { useWorkspaceSelectedTripPlanSync } from "./use-workspace-selected-trip-plan";
import { useWorkspaceTripPlanCommands } from "./use-workspace-trip-plans";

export function useWorkspacePlanningContext({
  activePlanItems,
  backendExpenseSummary,
  canCreateStopNote,
  canCreateSuggestion,
  canEdit,
  canManageTripPlans,
  canReviewSuggestions,
  commitTrip,
  currentMember,
  initialTrip,
  isApiMode,
  latestTripRef,
  mainPlanItems,
  participantSession,
  planItems,
  replaceDailyBriefings,
  resetBackendExpenseSummary,
  resetDailyBriefings,
  resolvedApiClient,
  selectedItemId,
  selectedTripPlanId,
  sessionRestored,
  setAccessError,
  setContextRailPreferredTab,
  setIsCockpitLoaded,
  setIsTripPlanBusy,
  setParticipantSession,
  setSelectedItemId,
  setSelectedTripPlanId,
  setTripPlanError,
  setTripState,
  trip,
  tripPlanErrorMessage,
  updateApiTrip,
}: UseWorkspacePlanningContextParams) {
  useWorkspaceSelectedTripPlanSync({
    isApiMode,
    sessionRestored,
    setSelectedTripPlanId,
    trip,
  });
  const records = useWorkspacePlanningRecordsContext({
    activePlanItems,
    backendExpenseSummary,
    canCreateStopNote,
    canCreateSuggestion,
    canEdit,
    canReviewSuggestions,
    commitTrip,
    currentMember,
    initialTrip,
    isApiMode,
    latestTripRef,
    mainPlanItems,
    participantSession,
    planItems,
    resolvedApiClient,
    selectedItemId,
    selectedTripPlanId,
    setContextRailPreferredTab,
    setSelectedItemId,
    trip,
  });
  const {
    createItineraryNote,
    createStopNote,
    createTask,
    deleteStopNote,
    replaceWorkspaceRecords,
    reviewSuggestion,
    setStopNotes,
    setTasks,
    stopNotes,
    suggestSelectedStop,
    tasks,
    toggleTaskStatus,
    updateStopNote,
  } = records;

  const replaceCockpitFromApi = useWorkspaceCockpitReplacement({
    replaceWorkspaceRecords,
    resetBackendExpenseSummary,
    setIsCockpitLoaded,
    setTripState,
  });

  const {
    createTripPlan,
    selectTripPlan,
    setMainTripPlan,
    updateTripPlanStatus,
    renameTripPlan,
  } = useWorkspaceTripPlanCommands({
    canManageTripPlans,
    isApiMode,
    latestTripRef,
    participantSession,
    rememberSelectedTripPlanId,
    replaceCockpitFromApi,
    resolveSelectedTripPlanId,
    selectedTripPlanId,
    setIsTripPlanBusy,
    setSelectedTripPlanId,
    setTripPlanError,
    trip,
    tripPlanErrorMessage,
    commitTrip,
    updateApiTrip,
    initialSelectedTripPlanId,
    resolvedApiClient,
  });

  useWorkspaceApiCockpitEffects({
    isApiMode,
    participantSession,
    rememberSelectedTripPlanId,
    replaceCockpitFromApi,
    replaceDailyBriefings,
    resetDailyBriefings,
    resolvedApiClient,
    resolveSelectedTripPlanId,
    setAccessError,
    setIsCockpitLoaded,
    setParticipantSession,
    setSelectedTripPlanId,
    updateApiTrip,
  });

  return {
    createItineraryNote,
    createStopNote,
    createTask,
    createTripPlan,
    deleteStopNote,
    expenseSummary: records.expenseSummary,
    itineraryView: records.itineraryView,
    mainItineraryView: records.mainItineraryView,
    renameTripPlan,
    replaceCockpitFromApi,
    reviewSuggestion,
    scopedSuggestions: records.scopedSuggestions,
    scopedTripForRecords: records.scopedTripForRecords,
    scopedTripPlanRecords: records.scopedTripPlanRecords,
    selectTripPlan,
    selectedDay: records.selectedDay,
    selectedItem: records.selectedItem,
    selectedItemIdForView: records.selectedItemIdForView,
    setMainTripPlan,
    setStopNotes,
    setTasks,
    stopNotes,
    suggestSelectedStop,
    tasks,
    toggleTaskStatus,
    updateStopNote,
    updateTripPlanStatus,
  };
}
