export const requiredStoryCategories = [
  "Design System/Buttons",
  "Design System/Badges",
  "Design System/Context Rail",
  "Design System/Date Time Pickers",
  "Design System/Language Switch",
  "Design System/Page Header",
  "Design System/People Panel",
  "Design System/Suggestion Panel",
  "Design System/Travel Motifs",
  "Design System/Weather Briefing Drawer",
  "Design System/Weather Forecast Strip",
  "Design System/Workspace Summary Stat",
  "Pages/Account Access",
  "Pages/Account Portal Primitives",
  "Sagittarius/App",
  "Templates/Workspace Shell",
  "Templates/Overview",
  "Templates/Itinerary",
  "Templates/Timeline",
  "Templates/Map",
  "Templates/Members",
  "Pages/Overview",
  "Pages/Itinerary",
  "Pages/Timeline",
  "Pages/Map",
  "Pages/Members",
  "Pages/Photos",
  "Pages/Expenses",
  "Pages/Bookings & Docs",
  "Pages/Trip Settings",
  "Pages/Home Landing",
  "Pages/About",
  "Pages/Stop Dialog",
  "Pages/Trip Join Gate",
] as const;

export const requiredGlobalStoryStates = [
  "Owner",
  "OwnerThai",
  "Traveler",
  "Viewer",
  "Empty",
  "Dense",
  "Mobile",
  "TabletItinerary",
  "MobileItinerary",
  "Desktop1024",
  "Desktop1440",
  "TableOverflow",
] as const;

export const requiredAppResponsiveStates = [
  "TabletOverview",
  "MobileOverview",
  "Desktop1024Overview",
  "Desktop1440Overview",
  "TabletItinerary",
  "MobileItinerary",
  "Desktop1024Itinerary",
  "Desktop1440Itinerary",
  "TabletTimeline",
  "MobileTimeline",
  "Desktop1024Timeline",
  "Desktop1440Timeline",
  "TabletMap",
  "MobileMap",
  "Desktop1024Map",
  "Desktop1440Map",
  "TabletMembers",
  "MobileMembers",
  "Desktop1024Members",
  "Desktop1440Members",
  "TabletExpenses",
  "MobileExpenses",
  "Desktop1024Expenses",
  "Desktop1440Expenses",
  "TabletBookings",
  "MobileBookings",
  "Desktop1024Bookings",
  "Desktop1440Bookings",
  "TabletPhotos",
  "MobilePhotos",
  "Desktop1024Photos",
  "Desktop1440Photos",
  "TabletSettings",
  "MobileSettings",
  "Desktop1024Settings",
  "Desktop1440Settings",
] as const;

export const requiredTemplateStates: Array<[string, string[]]> = [
  [
    "features/workspace/stories/AppShell.stories.tsx",
    ["Owner", "Traveler", "Viewer", "Mobile", "Tablet", "OwnerThai"],
  ],
  [
    "features/itinerary/stories/workspace/OverviewTemplate.stories.tsx",
    ["Owner", "Traveler", "OwnerThai", "Viewer", "Empty", "Dense"],
  ],
  [
    "features/itinerary/stories/ItineraryTemplate.stories.tsx",
    [
      "Owner",
      "OwnerThai",
      "Viewer",
      "Traveler",
      "Dense",
      "HierarchyBlocks",
      "HierarchyWarnings",
      "TableOverflow",
      "BranchGraph",
      "PlanAExample",
      "PlanABAlternatives",
      "RequestedPlanExample",
      "StressPaths",
    ],
  ],
  [
    "features/itinerary/stories/TimelineTemplate.stories.tsx",
    ["Owner", "OwnerThai", "Traveler", "Viewer", "Dense", "Empty"],
  ],
  [
    "features/itinerary/stories/workspace/MapTemplate.stories.tsx",
    ["Owner", "OwnerThai", "Traveler", "Viewer", "Dense", "Empty"],
  ],
  [
    "features/workspace/pages/members/MembersTemplate.stories.tsx",
    ["Owner", "OwnerThai", "Traveler", "Viewer", "Dense", "Empty"],
  ],
];

export const requiredAccessRouteStoryStates = [
  "PublicEntry",
  "AccountLogin",
  "AccountRegister",
  "AccountPortal",
  "AccountPortalMyTrips",
  "AccountPortalExplorer",
  "AccountPortalToDos",
  "AccountPortalVault",
  "AccountPortalSettings",
  "AccountPortalSignOut",
  "AccountTrips",
  "AccountNewTrip",
  "TripAccess",
  "JoinWithSeedCredentials",
  "TripAccessWithJoinCode",
  "TripOverviewAccess",
  "TripItineraryAccess",
  "TripMapAccess",
  "TripTimelineAccess",
  "TripMembersAccess",
] as const;
