import { readFileSync } from "node:fs";
import { join } from "node:path";

export const workspaceBoundarySourcePaths = {
  sagaCore: "src/trip/workspace/sagittarius-app/SagittariusAppCore.tsx",
  workspaceContextsHook: "src/trip/workspace/sagittarius-app/hooks/use-sagittarius-workspace-contexts.ts",
  sagittariusAccessGate: "src/trip/workspace/sagittarius-app/access-gate.tsx",
  workspaceAppFrame: "src/trip/workspace/sagittarius-app/WorkspaceAppFrame.tsx",
  workspaceMainShell: "src/trip/workspace/sagittarius-app/WorkspaceMainShell.tsx",
  workspaceAccessProps: "src/trip/workspace/sagittarius-app/props/workspace-access-props.ts",
  workspaceShellProps: "src/trip/workspace/sagittarius-app/props/workspace-shell-props.ts",
  workspaceDialogsProps: "src/trip/workspace/sagittarius-app/props/workspace-dialogs-props.ts",
  workspaceRailProps: "src/trip/workspace/sagittarius-app/props/workspace-rail-props.ts",
  workspaceToastProps: "src/trip/workspace/sagittarius-app/props/workspace-toast-props.ts",
  workspaceCoreCommandProps: "src/trip/workspace/sagittarius-app/props/workspace-core-command-props.ts",
  workspaceCoreFrameProps: "src/trip/workspace/sagittarius-app/props/workspace-core-frame-props.ts",
  workspaceCoreRecordProps: "src/trip/workspace/sagittarius-app/props/workspace-core-record-props.ts",
  workspacePageViewProps: "src/trip/workspace/sagittarius-app/props/workspace-page-view-props.ts",
  workspacePlanningViewProps: "src/trip/workspace/sagittarius-app/props/workspace-planning-view-props.ts",
  workspaceFrameActionProps: "src/trip/workspace/sagittarius-app/props/workspace-frame-action-props.ts",
  workspaceFrameProps: "src/trip/workspace/sagittarius-app/props/workspace-frame-props.ts",
  workspaceViewProps: "src/trip/workspace/sagittarius-app/props/workspace-view-props.ts",
  workspaceViewPropsTypes: "src/trip/workspace/sagittarius-app/props/workspace-view-props.types.ts",
  workspaceFacade: "src/trip/workspace/SagittariusApp.tsx",
  sagittariusAppTestAccountApi: "src/trip/workspace/sagittarius-app/sagittarius-app.test-account-api.ts",
  sagittariusAppTestBriefingFixtures: "src/trip/workspace/sagittarius-app/sagittarius-app.test-briefing-fixtures.ts",
  sagittariusAppTestFixtures: "src/trip/workspace/sagittarius-app/sagittarius-app.test-fixtures.tsx",
  sagittariusAppTestPlanFixtures: "src/trip/workspace/sagittarius-app/sagittarius-app.test-plan-fixtures.ts",
  sagittariusAppTestStorage: "src/trip/workspace/sagittarius-app/sagittarius-app.test-storage.ts",
  sagittariusAppTestSupport: "src/trip/workspace/sagittarius-app/sagittarius-app.test-support.tsx",
  sagittariusAppUiTest: "src/trip/workspace/sagittarius-app/SagittariusApp.test.tsx",
  sagittariusAppAccessTest: "src/trip/workspace/sagittarius-app/SagittariusApp.access.test.tsx",
  sagittariusAppAccountTripAccessTest:
    "src/trip/workspace/sagittarius-app/SagittariusApp.account-trip-access.test.tsx",
  workspaceRecordsHook: "src/trip/workspace/use-trip-workspace-records.ts",
  itineraryImportModel: "src/trip/workspace/itinerary-import-model.ts",
  itineraryImportApiRequests: "src/trip/workspace/itinerary-import-api-requests.ts",
  itineraryImportItemApiRequests: "src/trip/workspace/itinerary-import-item-api-requests.ts",
  itineraryImportRecordApiRequests: "src/trip/workspace/itinerary-import-record-api-requests.ts",
  itineraryImportRecordMapping: "src/trip/workspace/itinerary-import-record-mapping.ts",
  itineraryImportRecordMerge: "src/trip/workspace/itinerary-import-record-merge.ts",
  importHook: "src/trip/workspace/sagittarius-app/hooks/use-workspace-itinerary-import.ts",
  importApplyCommand: "src/trip/workspace/sagittarius-app/hooks/itinerary/use-workspace-itinerary-import-apply-command.ts",
  apiImportApplyCommand: "src/trip/workspace/sagittarius-app/hooks/itinerary/apply-api-itinerary-import.ts",
  accessContextHook: "src/trip/workspace/sagittarius-app/hooks/use-workspace-access-context.ts",
  accessGateHook: "src/trip/workspace/sagittarius-app/hooks/use-workspace-access-gate.ts",
  accountSessionHook: "src/trip/workspace/sagittarius-app/hooks/use-workspace-account-session.ts",
  uiStateHook: "src/trip/workspace/sagittarius-app/hooks/use-workspace-ui-state.ts",
  accessState: "src/trip/workspace/sagittarius-app/hooks/workspace-access-state.ts",
  participantSessionActions: "src/trip/workspace/sagittarius-app/hooks/use-workspace-participant-session-actions.ts",
  participantSessionRestoreHook: "src/trip/workspace/sagittarius-app/hooks/use-workspace-participant-session-restore.ts",
  participantPostAuthNavigation: "src/trip/workspace/sagittarius-app/hooks/participant-post-auth-navigation.ts",
  workspaceSessionHook: "src/trip/workspace/sagittarius-app/hooks/use-workspace-session.ts",
  workspaceSessionRestore: "src/trip/workspace/sagittarius-app/hooks/workspace-session-restore.ts",
  workspaceTripPlansHook: "src/trip/workspace/sagittarius-app/hooks/use-workspace-trip-plans.ts",
  workspaceTripPlanSelection: "src/trip/workspace/sagittarius-app/hooks/trip-plans/workspace-trip-plan-selection.ts",
  workspaceCommandsHook: "src/trip/workspace/sagittarius-app/hooks/use-workspace-commands.ts",
  itineraryBookingCommands: "src/trip/workspace/sagittarius-app/hooks/bookings/use-workspace-itinerary-booking-commands.ts",
  bookingCommandInputs: "src/trip/workspace/sagittarius-app/hooks/bookings/booking-command-inputs.ts",
  taskActionsHook: "src/trip/workspace/sagittarius-app/hooks/records/use-workspace-task-actions.ts",
  stopNoteActionsHook: "src/trip/workspace/sagittarius-app/hooks/records/use-workspace-stop-note-actions.ts",
  recordCommandInputs: "src/trip/workspace/sagittarius-app/hooks/records/workspace-record-command-inputs.ts",
  photoAlbumsHook: "src/trip/workspace/sagittarius-app/hooks/use-workspace-photo-albums.ts",
  photoAlbumApiCommands: "src/trip/workspace/sagittarius-app/hooks/photo-albums/use-workspace-api-photo-album-commands.ts",
  photoAlbumLocalCommands: "src/trip/workspace/sagittarius-app/hooks/photo-albums/use-workspace-local-photo-album-commands.ts",
  photoAlbumsDomain: "src/trip/photo-albums.ts",
  photoAlbumApi: "src/trip/photo-album-api.ts",
  photoAlbumLocal: "src/trip/photo-album-local.ts",
  photoAlbumQuery: "src/trip/photo-album-query.ts",
  expensesPageStory: "src/features/workspace/pages/expenses/ExpensesPage.stories.tsx",
  expenseMutationCommands: "src/trip/workspace/sagittarius-app/hooks/expenses/use-workspace-expense-mutation-commands.ts",
  expenseDrafts: "src/trip/expense-drafts.ts",
  expenseSummary: "src/trip/expense-summary.ts",
  expenseSettlements: "src/trip/expense-settlements.ts",
  expensePageOptions: "src/features/workspace/pages/expenses/expense-page-options.ts",
  itineraryViewModelHook: "src/trip/workspace/sagittarius-app/hooks/use-workspace-itinerary-view-model.ts",
  apiClientsHook: "src/trip/workspace/sagittarius-app/hooks/use-workspace-api-clients.ts",
  setupContextHook: "src/trip/workspace/sagittarius-app/hooks/use-workspace-setup-context.ts",
  dataContextHook: "src/trip/workspace/sagittarius-app/hooks/use-workspace-data-context.ts",
  backendExpenseSummaryHook: "src/trip/workspace/sagittarius-app/hooks/use-workspace-backend-expense-summary.ts",
  cockpitReplacementHook: "src/trip/workspace/sagittarius-app/hooks/use-workspace-cockpit-replacement.ts",
  memberContextHook: "src/trip/workspace/sagittarius-app/hooks/use-workspace-member-context.ts",
  navigationContextHook: "src/trip/workspace/sagittarius-app/hooks/use-workspace-navigation-context.ts",
  planningContextHook: "src/trip/workspace/sagittarius-app/hooks/use-workspace-planning-context.ts",
  planningRecordsContextHook: "src/trip/workspace/sagittarius-app/hooks/use-workspace-planning-records-context.ts",
  planningCommandsHook: "src/trip/workspace/sagittarius-app/hooks/use-workspace-planning-commands.ts",
  selectedTripPlanHook: "src/trip/workspace/sagittarius-app/hooks/use-workspace-selected-trip-plan.ts",
  selectedTripPlanHookTest: "src/trip/workspace/sagittarius-app/hooks/use-workspace-selected-trip-plan.test.tsx",
  selectedTripPlanTest: "src/trip/workspace/selected-trip-plan.test.ts",
  selectedTripPlanTestFixtures: "src/trip/workspace/selected-trip-plan.test-fixtures.ts",
  workspaceDialogs: "src/trip/workspace/sagittarius-app/WorkspaceDialogs.tsx",
  sagittariusAppStory: "src/app/SagittariusApp.stories.tsx",
  appShellStory: "src/features/workspace/stories/AppShell.stories.tsx",
  bookingsDocsPageStory: "src/features/workspace/pages/bookings-docs/BookingsDocsPage.stories.tsx",
  bookingDisplay: "src/features/workspace/pages/bookings-docs/booking-display.ts",
  bookingFolders: "src/features/workspace/pages/bookings-docs/booking-folders.ts",
  bookingList: "src/features/workspace/pages/bookings-docs/booking-list.ts",
  bookingDialog: "src/features/workspace/pages/bookings-docs/components/BookingDialog.tsx",
  bookingDialogLinks: "src/features/workspace/pages/bookings-docs/components/BookingDialogLinks.tsx",
  bookingFilePanel: "src/features/workspace/pages/bookings-docs/components/BookingFilePanel.tsx",
  bookingDialogState: "src/features/workspace/pages/bookings-docs/components/useBookingDialogState.ts",
  checkboxGroup: "src/shared/components/checkbox-group/CheckboxGroup.tsx",
  workspaceEmptyState: "src/shared/components/workspace-empty-state/WorkspaceEmptyState.tsx",
  itineraryTimeLib: "src/features/itinerary/lib/itinerary-time.ts",
  overviewPage: "src/features/itinerary/components/overview/OverviewPage.tsx",
  overviewSummaryBand: "src/features/itinerary/components/overview/OverviewSummaryBand.tsx",
  overviewCockpit: "src/features/itinerary/components/overview/OverviewCockpit.tsx",
  overviewTaskDialog: "src/features/itinerary/components/overview/OverviewTaskDialog.tsx",
  overviewTaskLayer: "src/features/itinerary/components/overview/OverviewTaskLayer.tsx",
  overviewWeatherBriefing: "src/features/itinerary/components/overview/OverviewWeatherBriefing.tsx",
  routeMapTypes: "src/features/itinerary/components/route-map/route-map.types.ts",
  smartItineraryTable: "src/features/itinerary/components/smart-itinerary-table/SmartItineraryTable.tsx",
  smartItineraryTableTypes: "src/features/itinerary/components/smart-itinerary-table/SmartItineraryTable.types.ts",
  smartItineraryTablePageHeader: "src/features/itinerary/components/smart-itinerary-table/SmartItineraryTablePageHeader.tsx",
  routeMapView: "src/features/itinerary/components/route-map/RouteMapView.tsx",
  routeMapCanvas: "src/features/itinerary/components/route-map/RouteMapCanvas.tsx",
  routeMapUnresolvedPanel: "src/features/itinerary/components/route-map/RouteMapUnresolvedPanel.tsx",
  routeLiveMapHook: "src/features/itinerary/components/route-map/use-route-live-map.ts",
  routeLiveMapMarkers: "src/features/itinerary/components/route-map/route-map.live-markers.ts",
  routeMapViewport: "src/features/itinerary/components/route-map/route-map.viewport.ts",
  routeMapUtils: "src/features/itinerary/components/route-map/route-map.utils.ts",
  contextRailStory: "src/features/itinerary/stories/ContextRail.stories.tsx",
  stopDialog: "src/features/itinerary/components/stop-dialog/StopDialog.tsx",
  stopDialogStory: "src/features/itinerary/stories/StopDialog.stories.tsx",
  stopDialogStorySupport: "src/features/itinerary/stories/StopDialog.stories.support.ts",
  stopDialogStoryItems: "src/features/itinerary/stories/StopDialog.stories.items.ts",
  stopDialogModel: "src/features/itinerary/components/stop-dialog/use-stop-dialog-model.ts",
  stopDialogForm: "src/features/itinerary/components/stop-dialog/stop-dialog.form.ts",
  stopDialogTimeFields: "src/features/itinerary/components/stop-dialog/stop-dialog-time-fields.ts",
  tripSettingsPageSource: "src/features/workspace/pages/trip-settings/TripSettingsPage.tsx",
  tripSettingsPageStory: "src/features/workspace/pages/trip-settings/TripSettingsPage.stories.tsx",
  tripSettingsIndexSource: "src/features/workspace/pages/trip-settings/index.ts",
  memberPageOptions: "src/features/workspace/pages/members/member-page-options.ts",
  memberPageSelectors: "src/features/workspace/pages/members/member-page-selectors.ts",
  memberInviteActions: "src/features/workspace/pages/members/use-member-invite-actions.ts",
  photoPageOptions: "src/features/workspace/pages/photos/photo-page-options.ts",
  photoPageSelectors: "src/features/workspace/pages/photos/photo-page-selectors.ts",
  photosPageStory: "src/features/workspace/pages/photos/TripPhotosPage.stories.tsx",
  photoAlbumBrowser: "src/features/workspace/pages/photos/components/PhotoAlbumBrowser.tsx",
  photoAlbumDialog: "src/features/workspace/pages/photos/components/PhotoAlbumDialog.tsx",
  photoAlbumDialogRelatedItems: "src/features/workspace/pages/photos/components/PhotoAlbumDialogRelatedItems.tsx",
  photoAlbumDialogState: "src/features/workspace/pages/photos/components/usePhotoAlbumDialogState.ts",
  accountAccessPanel: "src/features/account/components/account-access-panel/AccountAccessPanel.tsx",
  accountAccessPanelContent:
    "src/features/account/components/account-access-panel/composition/account-access-panel-content.tsx",
  accountAccessChrome:
    "src/features/account/components/account-access-panel/composition/account-access-panel-chrome.tsx",
  accountAccessShellClasses:
    "src/features/account/components/account-access-panel/layout/account-access-panel-shell-classes.ts",
  accountAccessPortalHandlers:
    "src/features/account/components/account-access-panel/portal/account-access-panel-portal-handlers.ts",
  accountAccessPortalContent:
    "src/features/account/components/account-access-panel/portal/account-access-panel-portal-content.tsx",
  accountAccessModes: "src/features/account/components/account-access-panel/model/account-access-modes.ts",
  accountPortalNavItems: "src/features/account/components/account-access-panel/portal/account-portal-nav-items.ts",
  accountPortalDataCache: "src/features/account/components/account-access-panel/portal/account-portal-data-cache.ts",
  accountPortalDashboardClassNames:
    "src/features/account/components/account-access-panel/portal/account-portal-dashboard-classnames.ts",
  accountTripDates: "src/features/account/components/account-access-panel/trip-wizard/model/account-trip-dates.ts",
  accountTripForm: "src/features/account/components/account-access-panel/trip-wizard/model/account-trip-form.ts",
  accountTripWizardSupport:
    "src/features/account/components/account-access-panel/trip-wizard/model/account-trip-wizard-support.ts",
  accountTripWizardSteps:
    "src/features/account/components/account-access-panel/trip-wizard/model/account-trip-wizard-steps.ts",
  portalTripWizard: "src/features/account/components/account-access-panel/trip-wizard/portal-trip-wizard.tsx",
  portalTripWizardMainPanel: "src/features/account/components/account-access-panel/trip-wizard/portal-trip-wizard-main-panel.tsx",
  portalTripWizardModel:
    "src/features/account/components/account-access-panel/trip-wizard/state/use-portal-trip-wizard-model.ts",
  portalTripWizardModelActions:
    "src/features/account/components/account-access-panel/trip-wizard/state/portal-trip-wizard-model-actions.ts",
  portalTripWizardDestinationState:
    "src/features/account/components/account-access-panel/trip-wizard/state/use-portal-trip-wizard-destination-state.ts",
  portalTripWizardMobileState:
    "src/features/account/components/account-access-panel/trip-wizard/state/use-portal-trip-wizard-mobile-state.ts",
  portalTripWizardDerivedState:
    "src/features/account/components/account-access-panel/trip-wizard/state/portal-trip-wizard-derived-state.ts",
  portalTripWizardActions: "src/features/account/components/account-access-panel/trip-wizard/portal-trip-wizard-actions.tsx",
  portalTripWizardDateActions:
    "src/features/account/components/account-access-panel/trip-wizard/state/use-portal-trip-wizard-date-actions.ts",
  portalTripWizardAccessActions:
    "src/features/account/components/account-access-panel/trip-wizard/state/use-portal-trip-wizard-access-actions.ts",
  portalTripWizardCredentialSync:
    "src/features/account/components/account-access-panel/trip-wizard/state/use-portal-trip-wizard-credential-sync.ts",
  accountAuthSupport: "src/features/account/components/account-access-panel/auth/account-auth-support.ts",
  emailLoginStepContent: "src/features/account/components/account-access-panel/email-login/account-email-login-step-content.tsx",
  dateTimePickers: "src/shared/components/date-time-pickers/DateTimePickers.tsx",
  tripJoinGate: "src/features/account/components/trip-join-gate/TripJoinGate.tsx",
  tripJoinGateChrome: "src/features/account/components/trip-join-gate/TripJoinGateChrome.tsx",
  tripJoinGateVisual: "src/features/account/components/trip-join-gate/TripJoinGateVisual.tsx",
  tripJoinRoomForm: "src/features/account/components/trip-join-gate/forms/TripJoinRoomForm.tsx",
  tripJoinParticipantAuthForm:
    "src/features/account/components/trip-join-gate/forms/TripJoinParticipantAuthForm.tsx",
  tripJoinParticipantStep: "src/features/account/components/trip-join-gate/TripJoinParticipantStep.tsx",
  tripJoinParticipantStatus: "src/features/account/components/trip-join-gate/model/trip-join-participant-status.ts",
  tripJoinResponseMapper: "src/features/account/components/trip-join-gate/model/trip-join-response-mapper.ts",
  tripJoinErrorMessage: "src/features/account/components/trip-join-gate/model/trip-join-error-message.ts",
  tripJoinGateStyles: "src/features/account/components/trip-join-gate/layout/trip-join-gate.styles.ts",
  tripWizardFormSections:
    "src/features/account/components/account-access-panel/trip-wizard/steps/portal-trip-wizard-form-sections.tsx",
  tripJoinGateStory: "src/features/account/components/trip-join-gate/TripJoinGate.stories.tsx",
  membersPageStory: "src/features/workspace/pages/members/MembersPage.stories.tsx",
  membersTemplateStory: "src/features/workspace/pages/members/MembersTemplate.stories.tsx",
  itineraryStoryFixtures: "src/features/itinerary/stories/itinerary-story-fixtures.ts",
  itineraryStoryPathScenarios: "src/features/itinerary/stories/itinerary-story-path-scenarios.ts",
  itineraryStoryPathItems: "src/features/itinerary/stories/fixtures/itinerary-story-path-items.ts",
  itineraryStoryPathOptions: "src/features/itinerary/stories/itinerary-story-path-options.ts",
  itineraryPageStory: "src/features/itinerary/stories/ItineraryPage.stories.tsx",
  storyBuilders: "src/shared/storybook/story-builders.ts",
  languageSwitchStory: "src/i18n/LanguageSwitch.stories.tsx",
  uiPrimitivesStory: "src/ui/ui.stories.tsx",
  weatherForecastStripStory: "src/shared/components/weather/WeatherForecastStrip.stories.tsx",
  weatherBriefingDrawerStory: "src/shared/components/weather/WeatherBriefingDrawer.stories.tsx",
  itineraryPageStoryPlays: "src/features/itinerary/stories/ItineraryPage.stories.plays.ts",
  itineraryTemplateStory: "src/features/itinerary/stories/ItineraryTemplate.stories.tsx",
  itineraryTemplateStoryPlays: "src/features/itinerary/stories/ItineraryTemplate.stories.plays.ts",
  overviewPageStory: "src/features/itinerary/stories/OverviewPage.stories.tsx",
  overviewTemplateStory: "src/features/itinerary/stories/workspace/OverviewTemplate.stories.tsx",
  timelinePageStory: "src/features/itinerary/stories/TimelinePage.stories.tsx",
  timelineTemplateStory: "src/features/itinerary/stories/TimelineTemplate.stories.tsx",
  mapPageStory: "src/features/itinerary/stories/workspace/MapPage.stories.tsx",
  mapTemplateStory: "src/features/itinerary/stories/workspace/MapTemplate.stories.tsx",
  homeLandingStory: "src/features/public-site/pages/home/HomeLanding.stories.tsx",
  aboutAppPageStory: "src/features/public-site/pages/about/AboutAppPage.stories.tsx",
  accountAccessStory: "src/features/account/components/account-access-panel/AccountAccessPanel.stories.tsx",
  accountAccessFixtures:
    "src/features/account/components/account-access-panel/fixtures/account-access-panel-fixtures.ts",
  accountAccessTestClients: "src/features/account/components/account-access-panel/testing/account-access-panel-test-clients.ts",
  accountAccessPasskeyTestUtils:
    "src/features/account/components/account-access-panel/testing/account-access-panel-passkey-test-utils.ts",
  accountAccessStorySupport:
    "src/features/account/components/account-access-panel/storybook/account-access-panel.stories.support.ts",
  accountSettingsEditor: "src/features/account/components/account-access-panel/portal/account-settings-editor.tsx",
  accountSettingsEditorState: "src/features/account/components/account-access-panel/portal/use-account-settings-editor-state.ts",
  emailLoginState: "src/features/account/components/account-access-panel/email-login/state/use-email-login-panel-state.ts",
  emailLoginEntryActions:
    "src/features/account/components/account-access-panel/email-login/state/use-email-login-entry-actions.ts",
  emailLoginAuthActions: "src/features/account/components/account-access-panel/email-login/submit/email-login-auth-actions.ts",
  emailLoginFormState: "src/features/account/components/account-access-panel/email-login/state/use-email-login-form-state.ts",
  emailLoginChallengeState:
    "src/features/account/components/account-access-panel/email-login/state/use-email-login-challenge-state.ts",
  emailLoginSubmitActions: "src/features/account/components/account-access-panel/email-login/submit/use-email-login-submit-actions.ts",
  emailLoginCodeRequestActions:
    "src/features/account/components/account-access-panel/email-login/submit/use-email-login-code-request-actions.ts",
  emailLoginSignInActions:
    "src/features/account/components/account-access-panel/email-login/submit/use-email-login-sign-in-actions.ts",
  emailLoginRegistrationActions:
    "src/features/account/components/account-access-panel/email-login/submit/use-email-login-registration-actions.ts",
  emailLoginSubmitErrors: "src/features/account/components/account-access-panel/email-login/submit/email-login-submit-errors.ts",
  emailLoginResendCooldown: "src/features/account/components/account-access-panel/email-login/state/use-email-login-resend-cooldown.ts",
  emailLoginPanel: "src/features/account/components/account-access-panel/email-login/account-email-login-panel.tsx",
  emailLoginStepStage: "src/features/account/components/account-access-panel/email-login/account-email-login-step-stage.tsx",
  appFacade: "src/app/SagittariusApp.tsx",
  tripSettingsPage: "src/features/workspace/pages/trip-settings/TripSettingsPage.tsx",
  tripSettingsStateKey: "src/features/workspace/pages/trip-settings/trip-settings-state-key.ts",
  tripSettingsFormModel: "src/features/workspace/pages/trip-settings/trip-settings-form-model.ts",
  tripSettingsDateImpact: "src/features/workspace/pages/trip-settings/trip-settings-date-impact.ts",
  tripSettingsFormState: "src/features/workspace/pages/trip-settings/use-trip-settings-form-state.ts",
} as const;

export type WorkspaceBoundarySourceName = keyof typeof workspaceBoundarySourcePaths;

export type WorkspaceBoundarySources = {
  [Name in WorkspaceBoundarySourceName]: string;
};

export function readWorkspaceBoundarySources(frontendRoot: string): WorkspaceBoundarySources {
  return Object.fromEntries(
    Object.entries(workspaceBoundarySourcePaths).map(([name, sourcePath]) => [
      name,
      readFileSync(join(frontendRoot, sourcePath), "utf8"),
    ]),
  ) as WorkspaceBoundarySources;
}
