import { describe, expect, it } from "vitest";
import { frontendRoot } from "./project-contract.helpers";
import { readWorkspaceBoundarySources } from "./workspace-source-boundaries.sources";

describe("Sagittarius workspace hook source boundaries", () => {
  it("keeps workspace setup, planning, data, session, and command hooks split by responsibility", () => {
    const {
      sagaCore,
      workspaceRecordsHook,
      importHook,
      accessContextHook,
      accessGateHook,
      accountSessionHook,
      uiStateHook,
      accessState,
      participantSessionActions,
      participantSessionRestoreHook,
      participantPostAuthNavigation,
      workspaceSessionHook,
      workspaceSessionRestore,
      workspaceCommandsHook,
      workspaceTripPlansHook,
      workspaceTripPlanSelection,
      itineraryBookingCommands,
      bookingCommandInputs,
      taskActionsHook,
      stopNoteActionsHook,
      recordCommandInputs,
      photoAlbumsHook,
      photoAlbumApiCommands,
      photoAlbumLocalCommands,
      photoAlbumsDomain,
      photoAlbumApi,
      photoAlbumLocal,
      photoAlbumQuery,
      expenseMutationCommands,
      expenseDrafts,
      itineraryViewModelHook,
      apiClientsHook,
      setupContextHook,
      dataContextHook,
      backendExpenseSummaryHook,
      cockpitReplacementHook,
      memberContextHook,
      navigationContextHook,
      planningContextHook,
      planningRecordsContextHook,
      planningCommandsHook,
      selectedTripPlanHook,
    } = readWorkspaceBoundarySources(frontendRoot);

    expect(sagaCore).toContain("useWorkspaceSetupContext");
    expect(setupContextHook).toContain("useWorkspaceUiState");
    expect(sagaCore).not.toContain("useState");
    expect(uiStateHook).toContain("export function useWorkspaceUiState");
    expect(uiStateHook).toContain("useState");
    expect(sagaCore).not.toContain("useWorkspaceApiClients");
    expect(setupContextHook).toContain("useWorkspaceApiClients");
    expect(sagaCore).not.toContain("createConfiguredTripApiClient");
    expect(sagaCore).not.toContain("createConfiguredAccountApiClient");
    expect(sagaCore).not.toContain("publicSagittariusApiBaseUrl");
    expect(apiClientsHook).toContain("createConfiguredTripApiClient");
    expect(apiClientsHook).toContain("createConfiguredAccountApiClient");
    expect(apiClientsHook).toContain("publicSagittariusApiBaseUrl");
    expect(sagaCore).not.toContain("useWorkspaceAccessContext");
    expect(setupContextHook).toContain("useWorkspaceAccessContext");
    expect(sagaCore).not.toContain("useWorkspaceMemberContext");
    expect(accessContextHook).toContain("useWorkspaceMemberContext");
    expect(accessContextHook).toContain("deriveWorkspacePermissions");
    expect(accessContextHook).toContain("useWorkspaceAccessGate");
    expect(sagaCore).not.toContain("findSessionMember");
    expect(sagaCore).not.toContain("isLocalParticipantSession");
    expect(memberContextHook).toContain("findSessionMember");
    expect(memberContextHook).toContain("isLocalParticipantSession");
    expect(sagaCore).not.toContain("useWorkspaceNavigationContext");
    expect(setupContextHook).toContain("useWorkspaceNavigationContext");
    expect(sagaCore).not.toContain("@/src/trip/workspace/use-workspace-navigation");
    expect(sagaCore).not.toContain("workspaceViewSupportsContextRail");
    expect(sagaCore).not.toContain("appRoutes.tripExpenses");
    expect(navigationContextHook).toContain("useWorkspaceNavigation");
    expect(navigationContextHook).toContain("workspaceViewSupportsContextRail");
    expect(navigationContextHook).toContain("appRoutes.tripExpenses");
    expect(sagaCore).not.toContain("useWorkspaceBackendExpenseSummary");
    expect(setupContextHook).toContain("useWorkspaceDataContext");
    expect(dataContextHook).toContain("useWorkspaceBackendExpenseSummary");
    expect(dataContextHook).toContain("useWorkspacePhotoAlbums");
    expect(dataContextHook).toContain("useDailyBriefings");
    expect(sagaCore).not.toContain("useBackendExpenseSummary");
    expect(sagaCore).not.toContain("workspaceViewShouldSyncBackendExpenseSummary");
    expect(backendExpenseSummaryHook).toContain("useBackendExpenseSummary");
    expect(backendExpenseSummaryHook).toContain("workspaceViewShouldSyncBackendExpenseSummary");
    expect(backendExpenseSummaryHook).toContain("clearParticipantSession");
    expect(sagaCore).toContain("useWorkspacePlanningContext");
    expect(sagaCore).not.toContain("useWorkspaceCockpitReplacement");
    expect(sagaCore).not.toContain("normalizeTripPlanAliases");
    expect(cockpitReplacementHook).toContain("export function useWorkspaceCockpitReplacement");
    expect(cockpitReplacementHook).toContain("normalizeTripPlanAliases");
    expect(cockpitReplacementHook).toContain("resetBackendExpenseSummary");
    expect(planningContextHook).toContain("useWorkspaceCockpitReplacement");
    expect(planningContextHook).toContain("useWorkspacePlanningRecordsContext");
    expect(planningContextHook).not.toContain("useWorkspaceItineraryViewModel");
    expect(planningContextHook).not.toContain("useWorkspaceRecords");
    expect(planningRecordsContextHook).toContain("useWorkspaceItineraryViewModel");
    expect(planningRecordsContextHook).toContain("useWorkspaceRecords");
    expect(planningRecordsContextHook).toContain("useTripWorkspaceRecords");
    expect(planningContextHook).toContain("useWorkspaceTripPlanCommands");
    expect(planningContextHook).toContain("useWorkspaceApiCockpitEffects");
    expect(sagaCore).not.toContain("useWorkspaceItineraryViewModel");
    expect(sagaCore).not.toContain("buildItineraryView");
    expect(sagaCore).not.toContain("resolveSelectedWorkspaceItem");
    expect(itineraryViewModelHook).toContain("buildItineraryView");
    expect(itineraryViewModelHook).toContain("resolveSelectedWorkspaceItem");
    expect(sagaCore).not.toContain("useWorkspaceSelectedTripPlanState");
    expect(setupContextHook).toContain("useWorkspaceSelectedTripPlanState");
    expect(sagaCore).not.toContain("useWorkspaceSelectedTripPlanSync");
    expect(planningContextHook).toContain("useWorkspaceSelectedTripPlanSync");
    expect(sagaCore).not.toContain("queueMicrotask");
    expect(selectedTripPlanHook).toContain("queueMicrotask");
    expect(selectedTripPlanHook).toContain("rememberSelectedTripPlanId");
    expect(selectedTripPlanHook).toContain("resolveSelectedTripPlanId");
    expect(sagaCore).not.toContain("@/src/trip/workspace/selected-trip-plan");
    expect(planningContextHook).toContain("@/src/trip/workspace/selected-trip-plan");
    expect(sagaCore).not.toContain("@/src/trip/workspace/use-backend-expense-summary");
    expect(backendExpenseSummaryHook).toContain("@/src/trip/workspace/use-backend-expense-summary");
    expect(sagaCore).not.toContain("@/src/trip/workspace/use-daily-briefings");
    expect(dataContextHook).toContain("@/src/trip/workspace/use-daily-briefings");
    expect(sagaCore).not.toContain("@/src/trip/workspace/use-itinerary-path-workspace");
    expect(setupContextHook).toContain("@/src/trip/workspace/use-itinerary-path-workspace");
    expect(sagaCore).not.toContain("@/src/trip/workspace/use-trip-workspace-records");
    expect(planningContextHook).not.toContain("@/src/trip/workspace/use-trip-workspace-records");
    expect(planningRecordsContextHook).toContain("@/src/trip/workspace/use-trip-workspace-records");
    expect(sagaCore).not.toContain("useWorkspacePhotoAlbums");
    expect(sagaCore).not.toContain("useWorkspaceRecords");
    expect(sagaCore).toContain("useWorkspaceCommands");
    expect(sagaCore).not.toContain("useWorkspaceAdministration");
    expect(sagaCore).not.toContain("useWorkspaceBookingCommands");
    expect(sagaCore).not.toContain("useWorkspaceItineraryCommands");
    expect(sagaCore).not.toContain("useWorkspaceItineraryImport");
    expect(workspaceCommandsHook).toContain("useWorkspacePlanningCommands");
    expect(workspaceCommandsHook).not.toContain("useWorkspaceBookingCommands");
    expect(workspaceCommandsHook).not.toContain("useWorkspaceItineraryCommands");
    expect(workspaceCommandsHook).not.toContain("useWorkspaceItineraryImport");
    expect(workspaceCommandsHook).toContain("useWorkspaceAdministration");
    expect(planningCommandsHook).toContain("useWorkspaceBookingCommands");
    expect(planningCommandsHook).toContain("useWorkspaceItineraryCommands");
    expect(planningCommandsHook).toContain("useWorkspaceItineraryImport");
    expect(sagaCore).not.toContain("useWorkspaceRecordState");
    expect(sagaCore).not.toContain("useWorkspaceRecordActions");
    expect(accessGateHook).toContain("resolveWorkspaceAccessState");
    expect(accessState).toContain("shouldRedirectUnauthenticatedTripRoute");
    expect(participantSessionActions).toContain("resolveParticipantPostAuthHref");
    expect(participantSessionActions).not.toContain("decodeReturnTo");
    expect(participantPostAuthNavigation).toContain("resolveJoinPostAuthReturnTo");
    expect(workspaceSessionHook).toContain("useWorkspaceAccountSession");
    expect(workspaceSessionHook).not.toContain("loadPersistedAccountSession");
    expect(workspaceSessionHook).not.toContain("persistAccountSession");
    expect(accountSessionHook).toContain("loadPersistedAccountSession");
    expect(accountSessionHook).toContain("persistAccountSession");
    expect(workspaceSessionHook).toContain("useWorkspaceParticipantSessionRestore");
    expect(workspaceSessionHook).not.toContain("loadPersistedParticipantSession");
    expect(workspaceSessionHook).not.toContain("resolveWorkspaceSessionRestore");
    expect(participantSessionRestoreHook).toContain("loadPersistedParticipantSession");
    expect(participantSessionRestoreHook).toContain("resolveWorkspaceSessionRestore");
    expect(workspaceSessionHook).not.toContain("normalizeTripPlanAliases");
    expect(workspaceSessionRestore).toContain("normalizeTripPlanAliases");
    expect(workspaceSessionRestore).toContain("resolveSelectedTripPlanId");
    expect(workspaceTripPlansHook).toContain("canSelectWorkspaceTripPlan");
    expect(workspaceTripPlansHook).toContain("resolveReloadedTripPlanSelection");
    expect(workspaceTripPlanSelection).toContain("planVariants.some");
    expect(itineraryBookingCommands).toContain(
      "resolveItineraryBookingTicketCommandInput",
    );
    expect(itineraryBookingCommands).not.toContain(
      "buildItineraryBookingTicketDocInput",
    );
    expect(bookingCommandInputs).toContain("findDuplicateBookingDoc");
    expect(taskActionsHook).toContain("buildWorkspaceTaskCreateDraft");
    expect(taskActionsHook).not.toContain("tripPlanIdForRecord");
    expect(stopNoteActionsHook).toContain("buildWorkspaceStopNoteCreateInput");
    expect(stopNoteActionsHook).not.toContain("tripPlanIdForRecord");
    expect(recordCommandInputs).toContain("tripPlanIdForRecord");
    expect(photoAlbumsHook).toContain("normalizePhotoAlbumCreateInput");
    expect(photoAlbumsHook).toContain("useWorkspaceApiPhotoAlbumCommands");
    expect(photoAlbumsHook).toContain("useWorkspaceLocalPhotoAlbumCommands");
    expect(photoAlbumsHook).not.toContain("const title = input.title.trim()");
    expect(photoAlbumsHook).not.toContain("const url = input.url.trim()");
    expect(photoAlbumApiCommands).toContain("isVersionConflict");
    expect(photoAlbumApiCommands).toContain("buildCreatePhotoAlbumRequest");
    expect(photoAlbumApiCommands).toContain("buildPatchPhotoAlbumRequest");
    expect(photoAlbumLocalCommands).toContain("createLocalPhotoAlbum");
    expect(photoAlbumLocalCommands).toContain("updateLocalPhotoAlbumInTrip");
    expect(photoAlbumsDomain).toContain("./photo-album-api");
    expect(photoAlbumsDomain).toContain("./photo-album-local");
    expect(photoAlbumsDomain).toContain("./photo-album-query");
    expect(photoAlbumApi).toContain("serializePhotoAlbumInputForApi");
    expect(photoAlbumLocal).toContain("normalizePhotoAlbumCreateInput");
    expect(photoAlbumLocal).toContain("createLocalPhotoAlbum");
    expect(photoAlbumQuery).toContain("buildPhotoAlbumSummary");
    expect(expenseMutationCommands).toContain(
      "resolveExpenseCreateDraftTripPlanId",
    );
    expect(expenseDrafts).toContain("resolveExpenseCreateDraftTripPlanId");
    expect(sagaCore).toContain("./hooks");
    expect(sagaCore).not.toContain("@/src/trip/workspace/use-trip-workspace-state");
    expect(sagaCore).not.toContain("@/src/trip/workspace/use-workspace-chrome");
    expect(setupContextHook).toContain("@/src/trip/workspace/use-trip-workspace-state");
    expect(setupContextHook).toContain("@/src/trip/workspace/use-workspace-chrome");
    expect(sagaCore).not.toContain("@/src/trip/workspace/use-workspace-navigation");
    expect(navigationContextHook).toContain("@/src/trip/workspace/use-workspace-navigation");
    expect(sagaCore).not.toContain("function buildImportedPlanRecordsForTripPlan");
    expect(sagaCore).not.toContain("function mergeApiImportedPlanRecordsIntoTrip");
    expect(sagaCore).not.toContain("function mergeImportedRecordsIntoTripPlan");
    expect(sagaCore).not.toContain("function buildImportedItineraryItemCreateRequest");
    expect(sagaCore).not.toContain("upsertById");
    expect(sagaCore).not.toContain("async function createImportedPlanRecordsViaApi");
    expect(importHook).toContain("@/src/trip/workspace/itinerary-import-model");
    expect(importHook).toContain("@/src/trip/workspace/itinerary-import-api");
    expect(workspaceRecordsHook).toContain("@/src/trip/workspace/trip-plan-records");
  });
});
