import { readFileSync } from "node:fs";
import { join } from "node:path";

export const workspaceBoundarySourcePaths = {
  sagaCore: "src/trip/workspace/sagittarius-app/SagittariusAppCore.tsx",
  sagittariusAccessGate: "src/trip/workspace/sagittarius-app/access-gate.tsx",
  workspaceAppFrame: "src/trip/workspace/sagittarius-app/WorkspaceAppFrame.tsx",
  workspaceMainShell: "src/trip/workspace/sagittarius-app/WorkspaceMainShell.tsx",
  workspaceAccessProps: "src/trip/workspace/sagittarius-app/workspace-access-props.ts",
  workspaceShellProps: "src/trip/workspace/sagittarius-app/workspace-shell-props.ts",
  workspaceViewProps: "src/trip/workspace/sagittarius-app/workspace-view-props.ts",
  workspaceFacade: "src/trip/workspace/SagittariusApp.tsx",
  workspaceRecordsHook: "src/trip/workspace/use-trip-workspace-records.ts",
  importHook: "src/trip/workspace/sagittarius-app/hooks/use-workspace-itinerary-import.ts",
  accessGateHook: "src/trip/workspace/sagittarius-app/hooks/use-workspace-access-gate.ts",
  uiStateHook: "src/trip/workspace/sagittarius-app/hooks/use-workspace-ui-state.ts",
  accessState: "src/trip/workspace/sagittarius-app/hooks/workspace-access-state.ts",
  participantSessionActions: "src/trip/workspace/sagittarius-app/hooks/use-workspace-participant-session-actions.ts",
  participantPostAuthNavigation: "src/trip/workspace/sagittarius-app/hooks/participant-post-auth-navigation.ts",
  workspaceSessionHook: "src/trip/workspace/sagittarius-app/hooks/use-workspace-session.ts",
  workspaceSessionRestore: "src/trip/workspace/sagittarius-app/hooks/workspace-session-restore.ts",
  workspaceTripPlansHook: "src/trip/workspace/sagittarius-app/hooks/use-workspace-trip-plans.ts",
  workspaceTripPlanSelection: "src/trip/workspace/sagittarius-app/hooks/trip-plans/workspace-trip-plan-selection.ts",
  itineraryBookingCommands: "src/trip/workspace/sagittarius-app/hooks/bookings/use-workspace-itinerary-booking-commands.ts",
  bookingCommandInputs: "src/trip/workspace/sagittarius-app/hooks/bookings/booking-command-inputs.ts",
  taskActionsHook: "src/trip/workspace/sagittarius-app/hooks/records/use-workspace-task-actions.ts",
  stopNoteActionsHook: "src/trip/workspace/sagittarius-app/hooks/records/use-workspace-stop-note-actions.ts",
  recordCommandInputs: "src/trip/workspace/sagittarius-app/hooks/records/workspace-record-command-inputs.ts",
  photoAlbumsHook: "src/trip/workspace/sagittarius-app/hooks/use-workspace-photo-albums.ts",
  photoAlbumsDomain: "src/trip/photo-albums.ts",
  photoAlbumApi: "src/trip/photo-album-api.ts",
  photoAlbumLocal: "src/trip/photo-album-local.ts",
  photoAlbumQuery: "src/trip/photo-album-query.ts",
  expenseMutationCommands: "src/trip/workspace/sagittarius-app/hooks/expenses/use-workspace-expense-mutation-commands.ts",
  expenseDrafts: "src/trip/expense-drafts.ts",
  itineraryViewModelHook: "src/trip/workspace/sagittarius-app/hooks/use-workspace-itinerary-view-model.ts",
  apiClientsHook: "src/trip/workspace/sagittarius-app/hooks/use-workspace-api-clients.ts",
  backendExpenseSummaryHook: "src/trip/workspace/sagittarius-app/hooks/use-workspace-backend-expense-summary.ts",
  cockpitReplacementHook: "src/trip/workspace/sagittarius-app/hooks/use-workspace-cockpit-replacement.ts",
  memberContextHook: "src/trip/workspace/sagittarius-app/hooks/use-workspace-member-context.ts",
  selectedTripPlanHook: "src/trip/workspace/sagittarius-app/hooks/use-workspace-selected-trip-plan.ts",
  workspaceDialogs: "src/trip/workspace/sagittarius-app/WorkspaceDialogs.tsx",
  bookingDisplay: "src/features/workspace/pages/bookings-docs/booking-display.ts",
  bookingFolders: "src/features/workspace/pages/bookings-docs/booking-folders.ts",
  bookingList: "src/features/workspace/pages/bookings-docs/booking-list.ts",
  bookingDialog: "src/features/workspace/pages/bookings-docs/components/BookingDialog.tsx",
  bookingDialogState: "src/features/workspace/pages/bookings-docs/components/useBookingDialogState.ts",
  itineraryTimeLib: "src/features/itinerary/lib/itinerary-time.ts",
  overviewPage: "src/features/itinerary/components/overview/OverviewPage.tsx",
  overviewSummaryBand: "src/features/itinerary/components/overview/OverviewSummaryBand.tsx",
  overviewCockpit: "src/features/itinerary/components/overview/OverviewCockpit.tsx",
  overviewTaskDialog: "src/features/itinerary/components/overview/OverviewTaskDialog.tsx",
  overviewTaskLayer: "src/features/itinerary/components/overview/OverviewTaskLayer.tsx",
  overviewWeatherBriefing: "src/features/itinerary/components/overview/OverviewWeatherBriefing.tsx",
  routeMapTypes: "src/features/itinerary/components/route-map/route-map.types.ts",
  smartItineraryTable: "src/features/itinerary/components/smart-itinerary-table/SmartItineraryTable.tsx",
  smartItineraryTablePageHeader: "src/features/itinerary/components/smart-itinerary-table/SmartItineraryTablePageHeader.tsx",
  routeMapView: "src/features/itinerary/components/route-map/RouteMapView.tsx",
  routeMapUnresolvedPanel: "src/features/itinerary/components/route-map/RouteMapUnresolvedPanel.tsx",
  routeLiveMapHook: "src/features/itinerary/components/route-map/use-route-live-map.ts",
  routeMapUtils: "src/features/itinerary/components/route-map/route-map.utils.ts",
  stopDialog: "src/features/itinerary/components/stop-dialog/StopDialog.tsx",
  stopDialogStory: "src/features/itinerary/stories/StopDialog.stories.tsx",
  stopDialogStorySupport: "src/features/itinerary/stories/StopDialog.stories.support.ts",
  stopDialogModel: "src/features/itinerary/components/stop-dialog/use-stop-dialog-model.ts",
  stopDialogForm: "src/features/itinerary/components/stop-dialog/stop-dialog.form.ts",
  stopDialogTimeFields: "src/features/itinerary/components/stop-dialog/stop-dialog-time-fields.ts",
  tripSettingsPageSource: "src/features/workspace/pages/trip-settings/TripSettingsPage.tsx",
  tripSettingsIndexSource: "src/features/workspace/pages/trip-settings/index.ts",
  memberSupport: "src/features/workspace/pages/members/TripMembersPage.support.ts",
  accountAccessPanel: "src/features/account/components/account-access-panel/AccountAccessPanel.tsx",
  accountAccessChrome: "src/features/account/components/account-access-panel/account-access-panel-chrome.tsx",
  accountTripWizardSupport: "src/features/account/components/account-access-panel/trip-wizard/account-trip-wizard-support.ts",
  portalTripWizard: "src/features/account/components/account-access-panel/trip-wizard/portal-trip-wizard.tsx",
  portalTripWizardModel: "src/features/account/components/account-access-panel/trip-wizard/use-portal-trip-wizard-model.ts",
  portalTripWizardDerivedState: "src/features/account/components/account-access-panel/trip-wizard/portal-trip-wizard-derived-state.ts",
  portalTripWizardActions: "src/features/account/components/account-access-panel/trip-wizard/portal-trip-wizard-actions.tsx",
  accountAuthSupport: "src/features/account/components/account-access-panel/auth/account-auth-support.ts",
  emailLoginStepContent: "src/features/account/components/account-access-panel/email-login/account-email-login-step-content.tsx",
  dateTimePickers: "src/shared/components/date-time-pickers/DateTimePickers.tsx",
  tripJoinGate: "src/features/account/components/trip-join-gate/TripJoinGate.tsx",
  tripJoinGateChrome: "src/features/account/components/trip-join-gate/TripJoinGateChrome.tsx",
  tripJoinGateVisual: "src/features/account/components/trip-join-gate/TripJoinGateVisual.tsx",
  tripJoinRoomForm: "src/features/account/components/trip-join-gate/TripJoinRoomForm.tsx",
  tripJoinParticipantStep: "src/features/account/components/trip-join-gate/TripJoinParticipantStep.tsx",
  tripJoinGateStyles: "src/features/account/components/trip-join-gate/trip-join-gate.styles.ts",
  tripWizardFormSections: "src/features/account/components/account-access-panel/trip-wizard/portal-trip-wizard-form-sections.tsx",
  itineraryStoryFixtures: "src/features/itinerary/stories/itinerary-story-fixtures.ts",
  itineraryStoryPathScenarios: "src/features/itinerary/stories/itinerary-story-path-scenarios.ts",
  itineraryPageStory: "src/features/itinerary/stories/ItineraryPage.stories.tsx",
  itineraryTemplateStory: "src/features/itinerary/stories/ItineraryTemplate.stories.tsx",
  accountAccessStory: "src/features/account/components/account-access-panel/AccountAccessPanel.stories.tsx",
  accountAccessStorySupport: "src/features/account/components/account-access-panel/account-access-panel.stories.support.ts",
  accountSettingsEditor: "src/features/account/components/account-access-panel/portal/account-settings-editor.tsx",
  accountSettingsEditorState: "src/features/account/components/account-access-panel/portal/use-account-settings-editor-state.ts",
  emailLoginState: "src/features/account/components/account-access-panel/email-login/use-email-login-panel-state.ts",
  emailLoginAuthActions: "src/features/account/components/account-access-panel/email-login/email-login-auth-actions.ts",
  emailLoginFormState: "src/features/account/components/account-access-panel/email-login/use-email-login-form-state.ts",
  emailLoginSubmitActions: "src/features/account/components/account-access-panel/email-login/use-email-login-submit-actions.ts",
  emailLoginResendCooldown: "src/features/account/components/account-access-panel/email-login/use-email-login-resend-cooldown.ts",
  emailLoginPanel: "src/features/account/components/account-access-panel/email-login/account-email-login-panel.tsx",
  emailLoginStepStage: "src/features/account/components/account-access-panel/email-login/account-email-login-step-stage.tsx",
  appFacade: "src/app/SagittariusApp.tsx",
  tripSettingsPage: "src/features/workspace/pages/trip-settings/TripSettingsPage.tsx",
  tripSettingsSupport: "src/features/workspace/pages/trip-settings/TripSettingsPage.support.ts",
  tripSettingsFormState: "src/features/workspace/pages/trip-settings/use-trip-settings-form-state.ts",
} as const;

export type WorkspaceBoundarySourceName = keyof typeof workspaceBoundarySourcePaths;

export type WorkspaceBoundarySources = {
  [Name in WorkspaceBoundarySourceName]: string;
};

export function readWorkspaceBoundarySources(frontendRoot: string): WorkspaceBoundarySources {
  return Object.fromEntries(
    Object.entries(workspaceBoundarySourcePaths).map(([name, sourcePath]) => [
      name,
      readFileSync(join(frontendRoot, sourcePath), "utf8"),
    ]),
  ) as WorkspaceBoundarySources;
}
