export const sagittariusAppBlockedBoundaryTerms = [
      "function shouldUseApiItineraryImport",
      "interface PendingItineraryImport",
      "resolveViewFromPath",
      "navigatedView",
      "setContextRailMounted",
      "setSidebarCollapsed",
      "setToastDismissed",
      "setToastDismissing",
      "buildFallbackBriefings",
      "buildPatchDailyBriefingRequest",
      "useState<{ tripPlanId: string; summary: ExpenseSummary } | null>",
      "@/src/trip/trip-fixtures",
      "tripFixtureSuggestions",
      "tripFixtureTasks",
      "tripFixtureStopNotes",
      "function resolveSelectedTripPlanId",
      "function rememberSelectedTripPlanId",
      "function selectTripPlanRecords",
      "function tripPlanIdForRecord",
      "buildItineraryCommitmentsByItemId",
      "buildExpenseSummary",
      "function loadPersistedParticipantSession",
      "function clearParticipantSession",
      "function loadPersistedTrip",
      "function persistTripDraft",
      "useState<ItineraryPathSelection>",
      "function changeTripPath",
      "function toggleShowAllPaths",
      "past: Trip[]",
      "future: Trip[]",
      "function replaceTripParticipant",
      "function appendTripParticipant",
      "function nextLocalItemId",
      "function nextLocalSuggestionId",
      "function nextLocalTaskId",
      "function nextLocalStopNoteId",
      "function nextLocalBookingDocId",
      "function nextLocalPhotoAlbumId",
      "function nextLocalPlanVariantId",
      "function nextLocalExpenseId",
      "function nextClientMutationId",
      "function normalizeTripPlanAliases",
      "function buildSetMainTripPlanRequest",
      "function buildPatchTripPlanStatusRequest",
      "function buildRenameTripPlanRequest",
      "function buildCreateTripPlanRequest",
      "function buildCreateMemberRequest",
      "function buildPatchMemberRoleRequest",
      "function buildPatchMemberAccessStatusRequest",
      "function buildPatchMemberPasswordRequest",
      "function buildUpdatePresenceRequest",
      "function updateTripPlanInTrip",
      "function mergePublishedTripPlan",
      "function setLocalMainTripPlan",
      "function createLocalTripPlan",
      "function buildCreateEditSuggestionRequest",
      "function createLocalEditSuggestion",
      "function rejectSuggestionById",
      "function buildPatchDailyBriefingRequest",
      "function applyDailyBriefingOverrides",
      "function buildPatchTripSettingsRequest",
      "function applyTripSettingsToTrip",
      "function mergePatchedTripSettings",
      "function normalizeTripPlanSummary",
      "function planStatusForLegacyKind",
      "function legacyKindForPlanStatus",
      "function daysBetweenIsoDates",
      "function shiftIsoDate",
      "function itineraryDateTime",
      "function buildItineraryItemDraft",
      "function buildUpdatedItineraryItem",
      "function appendItineraryItemToTrip",
      "function appendItineraryItemPlacement",
      "function mergeCreatedItineraryItemIntoTrip",
      "function mergeUpdatedItineraryBranchIntoTrip",
      "function shiftItineraryItemsToStartDate",
      "function buildInlineItineraryItemPatch",
      "function buildInlineItineraryItemPatchRequest",
      "function buildCreateItineraryItemRequest",
      "function buildPatchItineraryItemRequest",
      "function buildMoveItineraryItemRequest",
      "function buildMoveItineraryItemToDayRequest",
      "function buildReorderItineraryItemsRequest",
      "function buildShiftItineraryItemDayRequest",
      "function normalizeInlineTimePatch",
      "function createLocalBookingDoc",
      "function replaceBookingDocInTrip",
      "function updateLocalBookingDocInTrip",
      "function removeBookingDocFromTrip",
      "function normalizeBookingDocTitle",
      "function resolveBookingDocCreateTripPlanId",
      "function bookingDocQuickFieldsInputFromRecord",
      "function serializeBookingDocInputForApi",
      "function normalizeBookingDocDateTimeForApi",
      "function bookingTypeForItineraryItem",
      "function syncItineraryDetailsWithBookingTicket",
      "function clearItineraryBookingTicketDetails",
      "function findDuplicateBookingDoc",
      "function buildCreateBookingDocRequest",
      "function buildPatchBookingDocRequest",
      "function bookingDraftTitleForItineraryItem",
      "function bookingTypeForExpenseEstimate",
      "function bookingDocInputForExpenseEstimate",
      "function bookingDraftDetailsForItineraryItem",
      "function bookingDraftTimeWindowForItineraryItem",
      "function createLocalPhotoAlbum",
      "function buildCreatePhotoAlbumRequest",
      "function buildPatchPhotoAlbumRequest",
      "function appendPhotoAlbumToTrip",
      "function replacePhotoAlbumInTrip",
      "function updateLocalPhotoAlbum",
      "function updateLocalPhotoAlbumInTrip",
      "function removePhotoAlbumFromTrip",
      'from "@/src/trip/photo-albums"',
      "async function createPhotoAlbum",
      "async function updatePhotoAlbum",
      "async function deletePhotoAlbum",
      "function buildExpenseCreateDrafts",
      "function buildCreateExpenseRequest",
      "function buildPatchExpenseRequest",
      "function appendExpensesToTrip",
      "function appendLocalExpensesToTrip",
      "function buildExpenseUpdateDraft",
      "function replaceExpenseInTrip",
      "function updateLocalExpenseInTrip",
      "function removeExpenseFromTrip",
      "function expenseReminderRequestForSuggestion",
      "function buildExpenseReminderRequest",
      "function recordLocalExpenseReminderInTrip",
      "function createLocalStopNote",
      "function buildCreateStopNoteRequest",
      "function buildPatchStopNoteRequest",
      "function appendStopNote",
      "function createLocalStopNoteInList",
      "function replaceStopNote",
      "function updateLocalStopNote",
      "function removeStopNote",
      "function deleteLocalStopNote",
      "function buildTaskCreateDraft",
      "function buildCreateTaskRequest",
      "function createLocalTask",
      "function appendTask",
      "function createLocalTaskInList",
      "function replaceTask",
      "function toggledTaskStatus",
      "function buildToggleTaskStatusRequest",
      "function toggleLocalTaskStatus",
      "function TripAccessLoadingFrame",
      "function WorkspaceToast",
      "Role preview",
      "WorkspaceRolePreview",
      "workspaceToastDismissClassName",
      "portalLoadingCardClassName",
      "function buildMapLink",
      "function buildMapPlaceResolutionRequest",
      "function mapResolutionPlaceHint",
      "function mapResolutionActivity",
      "function resolveStopPlace",
      "function locationFieldsFromCandidate",
      "function readItineraryDetailString",
      "function normalizeExpenseRepeatCount",
      "function repeatExpenseLineItems",
      "function buildImportItineraryRequest",
      "function resolveCreatedImportId",
      "function serializePhotoAlbumInputForApi",
      "function deriveTripCountriesFromDestination",
      "async function patchApiItineraryBranchItems",
      "function buildItineraryCommitmentsByItemId",
      "function selectedItineraryPathIdForDay",
      "function updateItineraryPathSelection",
      "function itineraryItemPathFieldsForTarget",
      "function getNextSortOrder",
      "function getNextChildSortOrder",
      "function normalizeStopHierarchyValues",
      "function replaceItineraryItem",
      "function replaceItineraryItems",
      "function deleteItineraryItemFromTrip",
      "function moveTripItem",
      "function moveTripItemToDay",
      "function moveTripItemIntoPlanBlock",
      "function hasDescendantItem",
      "function isUnauthenticated",
      "function isForbidden",
      "function isAuthFailure",
      "function slugifyFilePart",
      "function replaceSuggestionById",
      "function resolveJoinPostAuthReturnTo",
      'from "@/src/components/OverviewPage"',
      'from "@/src/components/TimelineView"',
    ] as const;
