export const iconButtonBaseClassName = [
  "icon-button",
  "inline-flex",
  "min-h-9",
  "w-9",
  "items-center",
  "justify-center",
  "rounded-(--radius-sm)",
  "border",
  "border-(--color-border)",
  "bg-(--color-surface)",
  "text-[#334155]",
];

export const buttonBaseClassName = [
  "button",
  "inline-flex",
  "min-h-9",
  "items-center",
  "justify-center",
  "gap-2",
  "rounded-(--radius-sm)",
  "border",
  "border-transparent",
  "px-3",
  "py-[7px]",
  "text-[13px]",
  "font-extrabold",
  "no-underline",
  "transition-[background,border-color,color,box-shadow]",
  "duration-150",
  "disabled:text-(--color-text-subtle)",
  "disabled:bg-(--color-surface-muted)",
  "disabled:shadow-none",
];

export const buttonVariantClassNames = {
  primary: [
    "button--primary",
    "bg-(--color-primary)",
    "text-white",
    "shadow-[0_10px_20px_rgb(194_79_22_/_0.18)]",
    "hover:enabled:bg-(--color-primary-strong)",
  ],
  secondary: [
    "button--secondary",
    "w-full",
    "border-(--color-border)",
    "bg-(--color-surface)",
    "text-(--color-primary-strong)",
  ],
  ghost: [
    "button--ghost",
    "border-(--color-border)",
    "bg-(--color-surface)",
    "text-(--color-text-muted)",
  ],
  danger: [
    "button--danger",
    "border-(--color-danger-border)",
    "bg-(--color-danger-soft)",
    "text-[#b91c1c]",
  ],
} satisfies Record<string, string[]>;
export type ButtonVariant = keyof typeof buttonVariantClassNames;

export const floatingActionButtonClassName = [
  "floating-action-button",
  "fixed",
  "right-4",
  "bottom-4",
  "z-[30]",
  "inline-flex",
  "min-h-12",
  "min-w-12",
  "items-center",
  "justify-center",
  "gap-2",
  "rounded-full",
  "border",
  "border-(--color-primary)",
  "bg-(--color-primary)",
  "px-4",
  "text-sm",
  "font-extrabold",
  "text-white",
  "shadow-[0_10px_18px_rgb(15_118_110_/_0.22)]",
  "transition-[background,border-color,box-shadow,transform]",
  "duration-150",
  "hover:bg-(--color-primary-strong)",
  "focus-visible:outline",
  "focus-visible:outline-2",
  "focus-visible:outline-offset-2",
  "focus-visible:outline-(--color-primary)",
  "disabled:border-(--color-border)",
  "disabled:bg-(--color-surface-muted)",
  "disabled:text-(--color-text-muted)",
  "disabled:shadow-none",
];
