import { describe, expect, it } from "vitest";
import { readItineraryArchitectureSource } from "./project-itinerary-architecture.test-support";

describe("Sagittarius itinerary stop-dialog architecture contracts", () => {
  it("keeps StopDialog render split from form model state", () => {
    const stopDialog = readItineraryArchitectureSource("src/features/itinerary/components/stop-dialog/StopDialog.tsx");
    const stopDialogFormFields = readItineraryArchitectureSource("src/features/itinerary/components/stop-dialog/StopDialogFormFields.tsx");
    const stopDialogModel = readItineraryArchitectureSource("src/features/itinerary/components/stop-dialog/use-stop-dialog-model.ts");
    const stopDialogActions = readItineraryArchitectureSource("src/features/itinerary/components/stop-dialog/use-stop-dialog-actions.ts");
    const stopDialogDraftHook = readItineraryArchitectureSource("src/features/itinerary/components/stop-dialog/use-stop-dialog-draft-state.ts");
    const stopDialogDraftTypes = readItineraryArchitectureSource("src/features/itinerary/components/stop-dialog/stop-dialog-draft.types.ts");
    const stopDialogDraftInitialState = readItineraryArchitectureSource("src/features/itinerary/components/stop-dialog/stop-dialog-draft-initial-state.ts");
    const stopDialogDraftUpdaters = readItineraryArchitectureSource("src/features/itinerary/components/stop-dialog/stop-dialog-draft-updaters.ts");
    const stopDialogDraftSubmit = readItineraryArchitectureSource("src/features/itinerary/components/stop-dialog/stop-dialog-draft-submit.ts");
    const stopDialogTypes = readItineraryArchitectureSource("src/features/itinerary/components/stop-dialog/stop-dialog.types.ts");
    const stopDialogCopy = readItineraryArchitectureSource("src/features/itinerary/domain/stop-dialog-copy.ts");
    const stopDialogTimeWindow = readItineraryArchitectureSource("src/features/itinerary/components/stop-dialog/StopDialogTimeWindow.tsx");

    expect(stopDialog).toContain("./use-stop-dialog-model");
    expect(stopDialog).toContain("./StopDialogFormFields");
    expect(stopDialog).not.toContain("useState");
    expect(stopDialog).not.toContain("interface StopDialogProps");
    expect(stopDialog).not.toContain("buildStopSubmitValues");
    expect(stopDialog).not.toContain("applyStopActivityInput");
    expect(stopDialog).not.toContain("StopDialogPrimaryFields");
    expect(stopDialog).not.toContain('locale === "th"');
    expect(stopDialogFormFields).not.toContain('locale === "th"');
    expect(stopDialogTimeWindow).not.toContain('locale === "th"');
    expect(stopDialog).toContain("@/src/features/itinerary/domain/stop-dialog-copy");
    expect(stopDialogFormFields).toContain("stopDialogCopy");
    expect(stopDialogTimeWindow).toContain("timeWindowCopy");
    expect(stopDialogFormFields).toContain("export function StopDialogFormFields");
    expect(stopDialogFormFields).toContain("StopDialogPrimaryFields");
    expect(stopDialogFormFields).toContain("StopDialogPlaceResolution");
    expect(stopDialogModel).toContain("export function useStopDialogModel");
    expect(stopDialogModel).toContain("./use-stop-dialog-draft-state");
    expect(stopDialogModel).toContain("./use-stop-dialog-actions");
    expect(stopDialogModel).toContain("const draftState = useStopDialogDraftState");
    expect(stopDialogModel).toContain("const [submitState, setSubmitState]");
    expect(stopDialogModel).toContain("const actions = useStopDialogActions");
    expect(stopDialogModel).not.toContain("const [draftState, setDraftState]");
    expect(stopDialogModel).not.toContain("const [values, setValues]");
    expect(stopDialogModel).not.toContain("const [detailType, setDetailType]");
    expect(stopDialogModel).not.toContain("const [detailValues, setDetailValues]");
    expect(stopDialogModel).not.toContain("useState<PlaceResolutionCandidate>");
    expect(stopDialogModel).not.toContain("function submitValues");
    expect(stopDialogModel).not.toContain("async function");
    expect(stopDialogActions).toContain("export function useStopDialogActions");
    expect(stopDialogActions).toContain("./stop-dialog-submit-state");
    expect(stopDialogActions).toContain("async function submitValues");
    expect(stopDialogActions).toContain("function handleSubmit");
    expect(stopDialogActions).toContain("function submitUnresolved");
    expect(stopDialogDraftHook).toContain("export function useStopDialogDraftState");
    expect(stopDialogDraftHook).toContain("./stop-dialog-draft-initial-state");
    expect(stopDialogDraftHook).toContain("./stop-dialog-draft-submit");
    expect(stopDialogDraftHook).toContain("./stop-dialog-draft-updaters");
    expect(stopDialogDraftHook).toContain("const [draftState, setDraftState]");
    expect(stopDialogDraftHook).toContain("function updateActivity");
    expect(stopDialogDraftHook).toContain("buildStopDialogDraftSubmitValues");
    expect(stopDialogDraftTypes).toContain("export interface StopDialogDraftState");
    expect(stopDialogDraftInitialState).toContain("buildInitialStopFormValues");
    expect(stopDialogDraftUpdaters).toContain("applyStopActivityInput");
    expect(stopDialogDraftSubmit).toContain("buildStopSubmitValues");
    expect(stopDialogDraftHook).not.toContain("@/src/features/itinerary/domain/stop-form-model");
    expect(stopDialogDraftUpdaters).toContain("@/src/features/itinerary/domain/stop-form-model");
    expect(stopDialogDraftSubmit).toContain("buildStopDialogDraftSubmitValues");
    expect(stopDialogDraftUpdaters).toContain("updateStopDialogActivity");
    expect(stopDialogModel).not.toContain("./stop-dialog.form");
    expect(stopDialogModel).not.toContain("const [isSubmitting, setIsSubmitting]");
    expect(stopDialogModel).not.toContain("const [submitError, setSubmitError]");
    expect(stopDialogTypes).toContain("export interface StopDialogProps");
    expect(stopDialogTypes).toContain("StopDialogCopy");
    expect(stopDialogCopy).toContain("export function stopDialogCopy");
    expect(stopDialogCopy).toContain("export interface StopDialogCopy");
  });

  it("keeps stop dialog detail serialization split from utility ids", () => {
    const stopDialogFieldIds = readItineraryArchitectureSource("src/features/itinerary/components/stop-dialog/stop-dialog-field-ids.ts");
    const stopDialog = readItineraryArchitectureSource("src/features/itinerary/components/stop-dialog/StopDialog.tsx");
    const stopDialogFormFields = readItineraryArchitectureSource("src/features/itinerary/components/stop-dialog/StopDialogFormFields.tsx");
    const stopDetails = readItineraryArchitectureSource("src/features/itinerary/domain/stop-details.ts");
    const stopDetailDefinitions = readItineraryArchitectureSource("src/features/itinerary/domain/stop-detail-definitions.ts");

    expect(stopDialogFieldIds).toContain("export const stopDialogFieldIds");
    expect(stopDialogFieldIds).not.toContain("@/src/features/itinerary/domain/stop-details");
    expect(stopDialogFieldIds).not.toContain("buildStructuredStopDetails");
    expect(stopDialog).toContain("@/src/features/itinerary/domain/stop-details");
    expect(stopDialogFormFields).toContain("@/src/features/itinerary/domain/stop-details");
    expect(stopDetails).toContain("./stop-detail-definitions");
    expect(stopDetails).toContain("export function buildStructuredStopDetails");
    expect(stopDetails).toContain("function trimmedStopDetailValues");
    expect(stopDetails).not.toContain("export function stopDetailLabels");
    expect(stopDetails).not.toContain("export const emptyStopDetailValues");
    expect(stopDetailDefinitions).toContain("export function stopDetailLabels");
    expect(stopDetailDefinitions).toContain("export const emptyStopDetailValues");
  });
});
