import { describe, expect, it } from "vitest";
import { readItineraryArchitectureSource } from "./project-itinerary-architecture.test-support";

describe("Sagittarius itinerary overview architecture contracts", () => {
  it("keeps overview role panels split by reusable panel responsibility", () => {
    const managerRolePanels = readItineraryArchitectureSource("src/features/itinerary/components/overview/ManagerOverviewPanels.tsx");
    const travelerRolePanels = readItineraryArchitectureSource("src/features/itinerary/components/overview/TravelerOverviewPanels.tsx");
    const viewerRolePanels = readItineraryArchitectureSource("src/features/itinerary/components/overview/ViewerOverviewPanels.tsx");
    const managerChecklist = readItineraryArchitectureSource("src/features/itinerary/components/overview/ManagerChecklistPanel.tsx");
    const snapshotPanels = readItineraryArchitectureSource("src/features/itinerary/components/overview/OverviewSnapshotPanels.tsx");
    const overviewPanelTitle = readItineraryArchitectureSource("src/features/itinerary/components/overview/OverviewPanelTitle.tsx");
    const rolePanelTypes = readItineraryArchitectureSource("src/features/itinerary/components/overview/overview-role-panels.types.ts");

    expect(managerRolePanels).toContain("./ManagerChecklistPanel");
    expect(managerRolePanels).toContain("./overview-role-panels.types");
    expect(travelerRolePanels).toContain("./TravelerChecklistPanel");
    expect(travelerRolePanels).toContain("./OverviewSnapshotPanels");
    expect(viewerRolePanels).toContain("./OverviewSnapshotPanels");
    expect(managerRolePanels).not.toContain("SegmentedControl");
    expect(travelerRolePanels).not.toContain("interface TravelerOverviewPanelsProps");
    expect(viewerRolePanels).not.toContain("interface ViewerOverviewPanelsProps");
    expect(managerChecklist).toContain("export function ManagerTaskChecklistPanel");
    expect(managerChecklist).toContain("./OverviewPanelTitle");
    expect(managerChecklist).not.toContain("overviewPanelTitleClassName");
    expect(snapshotPanels).toContain("export function OverviewHighlightsPanel");
    expect(snapshotPanels).toContain("./OverviewPanelTitle");
    expect(overviewPanelTitle).toContain("export function OverviewPanelTitle");
    expect(overviewPanelTitle).toContain("overviewPanelTitleClassName");
    expect(rolePanelTypes).toContain("export interface ManagerOverviewPanelsProps");
  });

  it("keeps overview cockpit cards split from shared overview sections", () => {
    const overviewSections = readItineraryArchitectureSource("src/features/itinerary/components/overview/OverviewSections.tsx");
    const overviewHero = readItineraryArchitectureSource("src/features/itinerary/components/overview/OverviewHero.tsx");
    const overviewSummaryBand = readItineraryArchitectureSource("src/features/itinerary/components/overview/OverviewSummaryBand.tsx");
    const tripCompletedPostcard = readItineraryArchitectureSource("src/features/itinerary/components/overview/TripCompletedPostcard.tsx");
    const completedPostcardLabels = readItineraryArchitectureSource("src/features/itinerary/domain/overview-completed-postcard.ts");
    const overviewFocusSection = readItineraryArchitectureSource("src/features/itinerary/components/overview/OverviewFocusSection.tsx");
    const cockpit = readItineraryArchitectureSource("src/features/itinerary/components/overview/OverviewCockpit.tsx");
    const cockpitCard = readItineraryArchitectureSource("src/features/itinerary/components/overview/OverviewCockpitCard.tsx");

    expect(cockpit).toContain("./OverviewCockpitCard");
    expect(cockpit).toContain("CockpitCard");
    expect(overviewSections).not.toContain("export function CockpitCard");
    expect(overviewSections).not.toContain("export function OverviewHero");
    expect(overviewSections).not.toContain("export function TripCompletedPostcard");
    expect(overviewHero).toContain("export interface OverviewHeroProps");
    expect(overviewHero).toContain("export function OverviewHero");
    expect(tripCompletedPostcard).toContain("export interface TripCompletedPostcardProps");
    expect(tripCompletedPostcard).toContain("export function TripCompletedPostcard");
    expect(tripCompletedPostcard).toContain("@/src/features/itinerary/domain/overview-completed-postcard");
    expect(tripCompletedPostcard).not.toContain('locale === "th"');
    expect(completedPostcardLabels).toContain("export function buildCompletedPostcardLabels");
    expect(overviewSummaryBand).toContain("./OverviewHero");
    expect(overviewSummaryBand).toContain("OverviewHeroProps");
    expect(overviewSummaryBand).not.toContain("ComponentProps<typeof OverviewHero>");
    expect(overviewFocusSection).toContain("./TripCompletedPostcard");
    expect(overviewSections).not.toContain("cockpitCardButtonClassName");
    expect(cockpitCard).toContain("export function CockpitCard");
    expect(cockpitCard).toContain("cockpitCardButtonClassName");
  });

  it("keeps overview task state split from page composition", () => {
    const overviewPage = readItineraryArchitectureSource("src/features/itinerary/components/overview/OverviewPage.tsx");
    const overviewLensPanels = readItineraryArchitectureSource("src/features/itinerary/components/overview/OverviewLensPanels.tsx");
    const overviewPageState = readItineraryArchitectureSource("src/features/itinerary/components/overview/use-overview-page-state.ts");
    const overviewPageDerived = readItineraryArchitectureSource("src/features/itinerary/components/overview/overview-page-derived.tsx");
    const overviewPageModel = readItineraryArchitectureSource("src/features/itinerary/components/overview/overview-page-model.ts");
    const overviewFocusHeading = readItineraryArchitectureSource("src/features/itinerary/domain/overview-focus-heading.ts");
    const overviewPageTypes = readItineraryArchitectureSource("src/features/itinerary/components/overview/OverviewPage.types.ts");
    const overviewTaskActions = readItineraryArchitectureSource("src/features/itinerary/components/overview/use-overview-task-actions.ts");
    const overviewTaskState = readItineraryArchitectureSource("src/features/itinerary/components/overview/use-overview-task-state.ts");
    const overviewTaskStateModel = readItineraryArchitectureSource("src/features/itinerary/components/overview/overview-task-state.ts");
    const overviewTaskDerivation = readItineraryArchitectureSource("src/features/itinerary/components/overview/overview-task-derivation.ts");

    expect(overviewPage).toContain("./use-overview-page-state");
    expect(overviewPage).toContain("./OverviewPage.types");
    expect(overviewPage).toContain("./OverviewLensPanels");
    expect(overviewPage).not.toContain("./overview-page-derived");
    expect(overviewPage).not.toContain("./overview-page-model");
    expect(overviewPage).not.toContain("./use-overview-task-state");
    expect(overviewPage).not.toContain("./ManagerOverviewPanels");
    expect(overviewPage).not.toContain("./TravelerOverviewPanels");
    expect(overviewPage).not.toContain("./ViewerOverviewPanels");
    expect(overviewPage).not.toContain("useState");
    expect(overviewPage).not.toContain("useMemo");
    expect(overviewPage).not.toContain("interface OverviewPageProps");
    expect(overviewPage).not.toContain("function submitTask");
    expect(overviewPage).not.toContain("function openExpenses");
    expect(overviewPage).not.toContain("isMyTask");
    expect(overviewPage).not.toContain('locale === "th"');
    expect(overviewPageState).toContain("export function useOverviewPageState");
    expect(overviewPageState).toContain("./use-overview-task-state");
    expect(overviewPageState).toContain("./overview-page-derived");
    expect(overviewPageState).toContain("./overview-page-model");
    expect(overviewPageState).toContain("function openExpenses");
    expect(overviewPageModel).toContain("overviewFocusHeading");
    expect(overviewPageModel).not.toContain("completedFocusHeading");
    expect(overviewPageModel).not.toContain("incomingFocusHeading");
    expect(overviewFocusHeading).toContain("export function overviewFocusHeading");
    expect(overviewLensPanels).toContain("export function OverviewLensPanels");
    expect(overviewLensPanels).toContain("./ManagerOverviewPanels");
    expect(overviewLensPanels).toContain("./TravelerOverviewPanels");
    expect(overviewLensPanels).toContain("./ViewerOverviewPanels");
    expect(overviewPageDerived).toContain("export function renderOverviewCurrentMemberCard");
    expect(overviewPageDerived).toContain("export function buildOverviewTaskListLabels");
    expect(overviewPageTypes).toContain("export interface OverviewPageProps");
    expect(overviewTaskState).toContain("export function useOverviewTaskState");
    expect(overviewTaskState).toContain("./overview-task-state");
    expect(overviewTaskState).toContain("./overview-task-derivation");
    expect(overviewTaskState).toContain("./use-overview-task-actions");
    expect(overviewTaskState).toContain("const [taskState, setTaskState]");
    expect(overviewTaskState).toContain("function updateFilterState");
    expect(overviewTaskState).toContain("function updateNewTaskFormState");
    expect(overviewTaskState).not.toContain("function submitTask");
    expect(overviewTaskState).not.toContain("function toggleTask");
    expect(overviewTaskState).not.toContain("function undoTaskToggle");
    expect(overviewTaskActions).toContain("export function useOverviewTaskActions");
    expect(overviewTaskActions).toContain("function submitTask");
    expect(overviewTaskActions).toContain("function toggleTask");
    expect(overviewTaskActions).toContain("function undoTaskToggle");
    expect(overviewTaskActions).toContain("buildOverviewTaskSubmission");
    expect(overviewTaskActions).toContain("applyOverviewTaskSubmission");
    expect(overviewTaskActions).toContain("setOverviewUndoTask");
    expect(overviewTaskState).not.toContain("const [filterState, setFilterState]");
    expect(overviewTaskState).not.toContain("const [isTaskDialogOpen, setIsTaskDialogOpen]");
    expect(overviewTaskState).not.toContain("const [newTaskFormState, setNewTaskFormState]");
    expect(overviewTaskState).not.toContain("const [undoTask, setUndoTask]");
    expect(overviewTaskState).not.toContain("isMyTask");
    expect(overviewTaskState).toContain("myOpenTasks");
    expect(overviewTaskState).toContain("sharedOpenTasks");
    expect(overviewTaskStateModel).toContain("export interface OverviewTaskUiState");
    expect(overviewTaskStateModel).toContain("initialOverviewTaskUiState");
    expect(overviewTaskStateModel).toContain("export interface OverviewTaskFilterState");
    expect(overviewTaskStateModel).toContain("export interface OverviewNewTaskFormState");
    expect(overviewTaskStateModel).not.toContain("export function visibleOverviewTasks");
    expect(overviewTaskStateModel).not.toContain("export function buildOverviewTaskSubmission");
    expect(overviewTaskStateModel).not.toContain("isMyTask");
    expect(overviewTaskDerivation).toContain("export function visibleOverviewTasks");
    expect(overviewTaskDerivation).toContain("export function countOverviewOpenTasks");
    expect(overviewTaskDerivation).toContain("export function buildOverviewTaskSubmission");
    expect(overviewTaskDerivation).toContain("isMyTask");
    expect(overviewTaskState).not.toContain("const [taskScope, setTaskScope]");
    expect(overviewTaskState).not.toContain("const [newTaskTitle, setNewTaskTitle]");
  });
});
