import { describe, expect, it } from "vitest";
import { readItineraryArchitectureSource } from "./project-itinerary-architecture.test-support";

describe("Sagittarius workspace expenses architecture contracts", () => {
  it("keeps expenses page state split from page composition", () => {
    const expensesPage = readItineraryArchitectureSource("src/features/workspace/pages/expenses/TripExpensesPage.tsx");
    const expensesState = readItineraryArchitectureSource("src/features/workspace/pages/expenses/use-trip-expenses-page-state.ts");
    const expenseActions = readItineraryArchitectureSource("src/features/workspace/pages/expenses/model/expense-page-actions.ts");
    const expenseFilters = readItineraryArchitectureSource("src/features/workspace/pages/expenses/model/expense-page-filters.ts");
    const expenseFilterState = readItineraryArchitectureSource("src/features/workspace/pages/expenses/model/expense-page-filter-state.ts");
    const expenseLedgerActions = readItineraryArchitectureSource("src/features/workspace/pages/expenses/hooks/useExpenseLedgerActions.ts");
    const expenseDialog = readItineraryArchitectureSource("src/features/workspace/pages/expenses/ExpenseDialog.tsx");
    const expenseDialogState = readItineraryArchitectureSource("src/features/workspace/pages/expenses/hooks/useExpenseDialogState.ts");
    const expenseSplitEditor = readItineraryArchitectureSource("src/features/workspace/pages/expenses/hooks/useExpenseSplitEditor.ts");
    const expenseSplitEditorModel = readItineraryArchitectureSource("src/features/workspace/pages/expenses/model/expense-split-editor.ts");
    const contextRailExpenseForm = readItineraryArchitectureSource("src/features/itinerary/components/context-rail/use-context-rail-expense-form.ts");
    const contextRailExpenseFormState = readItineraryArchitectureSource("src/features/itinerary/components/context-rail/context-rail-expense-form-state.ts");

    expect(expensesPage).toContain("./use-trip-expenses-page-state");
    expect(expensesPage).not.toContain("useState");
    expect(expensesPage).not.toContain("useMemo");
    expect(expensesPage).not.toContain("buildExpenseCsv");
    expect(expensesPage).not.toContain("refundSplits");
    expect(expensesPage).not.toContain("function recordRefund");
    expect(expensesState).toContain("./model/expense-page-filters");
    expect(expensesState).toContain("./model/expense-page-filter-state");
    expect(expensesState).toContain("./model/expense-page-actions");
    expect(expensesState).toContain("./hooks/useExpenseLedgerActions");
    expect(expensesState).toContain("export function useTripExpensesPageState");
    expect(expensesState).toContain("const [filterState, setFilterState]");
    expect(expensesState).not.toContain("const [query, setQuery]");
    expect(expensesState).not.toContain("const [payerFilter, setPayerFilter]");
    expect(expensesState).not.toContain("const [categoryFilter, setCategoryFilter]");
    expect(expensesState).not.toContain("buildExpenseCsv");
    expect(expensesState).not.toContain("function filterExpenses");
    expect(expensesState).not.toContain("refundSplits");
    expect(expensesState).not.toContain("sumShares");
    expect(expenseFilters).toContain("export function filterExpenses");
    expect(expenseFilters).toContain("export function expenseCategorySpend");
    expect(expenseFilters).toContain("export function inferredScopeExpenses");
    expect(expenseFilterState).toContain("export interface ExpensePageFilterState");
    expect(expenseFilterState).toContain("initialExpensePageFilterState");
    expect(expenseFilterState).toContain("clearedExpensePageFilterState");
    expect(expenseActions).toContain("export function buildSettlementExpenseInput");
    expect(expenseActions).toContain("export function buildRefundExpenseInput");
    expect(expenseActions).toContain("refundSplits");
    expect(expenseActions).toContain("sumShares");
    expect(expenseLedgerActions).toContain("export function useExpenseLedgerActions");
    expect(expenseLedgerActions).toContain("buildExpenseCsv");
    expect(expenseLedgerActions).toContain("buildPaybackReminder");
    expect(expensesState).toContain("function recordRefund");
    expect(expenseDialog).toContain("./hooks/useExpenseDialogState");
    expect(expenseDialog).not.toContain("useState");
    expect(expenseDialog).not.toContain("calculateExpenseDialogState");
    expect(expenseDialog).not.toContain("function submitExpense");
    expect(expenseDialogState).toContain("export function useExpenseDialogState");
    expect(expenseDialogState).toContain("useExpenseSplitEditor");
    expect(expenseDialogState).toContain("const [formValues, setFormValues]");
    expect(expenseDialogState).toContain("const [uiState, setUiState]");
    expect(expenseDialogState).toContain("function updateFormValue");
    expect(expenseDialogState).toContain("function submitExpense");
    expect(expenseDialogState).not.toContain("const [title, setTitle]");
    expect(expenseDialogState).not.toContain("const [amount, setAmount]");
    expect(expenseDialogState).not.toContain("const [currency, setCurrency]");
    expect(expenseDialogState).not.toContain("const [isSaving, setIsSaving]");
    expect(expenseDialogState).not.toContain("const [tripPlanId, setTripPlanId]");
    expect(expenseSplitEditor).toContain("initialExpenseSplitEditorState");
    expect(expenseSplitEditor).toContain("const [state, setState]");
    expect(expenseSplitEditor).not.toContain("const [splitMode, setSplitMode]");
    expect(expenseSplitEditor).not.toContain("const [splitValues, setSplitValues]");
    expect(expenseSplitEditor).not.toContain("const [lineItems, setLineItems]");
    expect(expenseSplitEditorModel).toContain("export interface ExpenseSplitEditorState");
    expect(expenseSplitEditorModel).toContain("export function changeExpenseSplitEditorMode");
    expect(contextRailExpenseForm).toContain("./context-rail-expense-form-state");
    expect(contextRailExpenseForm).toContain("const [state, setState]");
    expect(contextRailExpenseForm).toContain("function updateFormValue");
    expect(contextRailExpenseForm).not.toContain("interface ContextRailExpenseFormState");
    expect(contextRailExpenseForm).not.toContain("const [editingExpenseId, setEditingExpenseId]");
    expect(contextRailExpenseForm).not.toContain("const [formValues, setFormValues]");
    expect(contextRailExpenseForm).not.toContain("const [expenseTitle, setExpenseTitle]");
    expect(contextRailExpenseForm).not.toContain("const [expenseAmount, setExpenseAmount]");
    expect(contextRailExpenseFormState).toContain("export interface ContextRailExpenseFormState");
    expect(contextRailExpenseFormState).toContain("contextRailExpenseCategoryOptions");
    expect(contextRailExpenseFormState).toContain("startContextRailExpenseEdit");
  });
});
