import { describe, expect, it } from "vitest";
import { readItineraryArchitectureSource } from "./project-itinerary-architecture.test-support";

describe("Sagittarius workspace expenses architecture contracts", () => {
  it("keeps expenses page state split from page composition", () => {
    const expensesPage = readItineraryArchitectureSource("src/features/workspace/pages/expenses/TripExpensesPage.tsx");
    const expensesState = readItineraryArchitectureSource("src/features/workspace/pages/expenses/hooks/use-trip-expenses-page-state.ts");
    const expenseDialogTargetState = readItineraryArchitectureSource("src/features/workspace/pages/expenses/hooks/useExpenseDialogTargetState.ts");
    const expensePageFilters = readItineraryArchitectureSource("src/features/workspace/pages/expenses/hooks/useExpensePageFilters.ts");
    const expensePageDerivedState = readItineraryArchitectureSource("src/features/workspace/pages/expenses/hooks/useExpensePageDerivedState.ts");
    const expenseActions = readItineraryArchitectureSource("src/features/workspace/pages/expenses/model/expense-page-actions.ts");
    const expenseSettlementActions = readItineraryArchitectureSource("src/features/workspace/pages/expenses/hooks/useExpenseSettlementActions.ts");
    const expenseFilters = readItineraryArchitectureSource("src/features/workspace/pages/expenses/model/expense-page-filters.ts");
    const expenseFilterState = readItineraryArchitectureSource("src/features/workspace/pages/expenses/model/expense-page-filter-state.ts");
    const expenseLedgerSection = readItineraryArchitectureSource("src/features/workspace/pages/expenses/components/ExpenseLedgerSection.tsx");
    const expenseLedgerRows = readItineraryArchitectureSource("src/features/workspace/pages/expenses/components/ExpenseLedgerRows.tsx");
    const expenseLedgerDisplay = readItineraryArchitectureSource("src/features/workspace/pages/expenses/model/expense-ledger-display.ts");
    const expensePageHeader = readItineraryArchitectureSource("src/features/workspace/pages/expenses/components/ExpensePageHeader.tsx");
    const expenseOverviewPanels = readItineraryArchitectureSource("src/features/workspace/pages/expenses/components/ExpenseOverviewPanels.tsx");
    const expenseOverviewSections = readItineraryArchitectureSource("src/features/workspace/pages/expenses/components/ExpenseOverviewSections.tsx");
    const expenseOverviewDisplay = readItineraryArchitectureSource("src/features/workspace/pages/expenses/model/expense-overview-display.ts");
    const expenseOverviewBalanceDisplay = readItineraryArchitectureSource("src/features/workspace/pages/expenses/model/expense-overview-balance-display.ts");
    const expenseOverviewRowDisplay = readItineraryArchitectureSource("src/features/workspace/pages/expenses/model/expense-overview-row-display.ts");
    const expenseOverviewSettlementDisplay = readItineraryArchitectureSource("src/features/workspace/pages/expenses/model/expense-overview-settlement-display.ts");
    const expenseLedgerActions = readItineraryArchitectureSource("src/features/workspace/pages/expenses/hooks/useExpenseLedgerActions.ts");
    const expenseDialog = readItineraryArchitectureSource("src/features/workspace/pages/expenses/components/ExpenseDialog.tsx");
    const expenseDialogFormContent = readItineraryArchitectureSource("src/features/workspace/pages/expenses/components/ExpenseDialogFormContent.tsx");
    const expenseDialogState = readItineraryArchitectureSource("src/features/workspace/pages/expenses/hooks/useExpenseDialogState.ts");
    const expenseDialogFormValues = readItineraryArchitectureSource("src/features/workspace/pages/expenses/hooks/useExpenseDialogFormValues.ts");
    const expenseDialogLinkingState = readItineraryArchitectureSource("src/features/workspace/pages/expenses/hooks/useExpenseDialogLinkingState.ts");
    const expenseDialogSubmitHandler = readItineraryArchitectureSource("src/features/workspace/pages/expenses/hooks/useExpenseDialogSubmitHandler.ts");
    const expenseDialogSubmitAction = readItineraryArchitectureSource("src/features/workspace/pages/expenses/model/expense-dialog-submit-action.ts");
    const expenseSplitEditor = readItineraryArchitectureSource("src/features/workspace/pages/expenses/hooks/useExpenseSplitEditor.ts");
    const expenseSplitEditorModel = readItineraryArchitectureSource("src/features/workspace/pages/expenses/model/expense-split-editor.ts");
    const expenseDialogSummary = readItineraryArchitectureSource("src/features/workspace/pages/expenses/components/ExpenseDialogSummary.tsx");
    const expenseDialogSummaryDisplay = readItineraryArchitectureSource("src/features/workspace/pages/expenses/model/expense-dialog-summary-display.ts");
    const expenseSummaryStats = readItineraryArchitectureSource("src/features/workspace/pages/expenses/components/ExpenseSummaryStats.tsx");
    const expenseSummaryDisplay = readItineraryArchitectureSource("src/features/workspace/pages/expenses/model/expense-summary-display.ts");
    const expenseStyles = readItineraryArchitectureSource("src/features/workspace/pages/expenses/TripExpensesPage.styles.ts");
    const expenseCommentsSection = readItineraryArchitectureSource("src/features/workspace/pages/expenses/components/ExpenseCommentsSection.tsx");
    const expenseCommentsState = readItineraryArchitectureSource("src/features/workspace/pages/expenses/model/expense-comments-state.ts");
    const contextRailExpenseForm = readItineraryArchitectureSource("src/features/itinerary/components/context-rail/use-context-rail-expense-form.ts");
    const contextRailExpenseFormActions = readItineraryArchitectureSource("src/features/itinerary/components/context-rail/use-context-rail-expense-form-actions.ts");
    const contextRailExpenseFormState = readItineraryArchitectureSource("src/features/itinerary/components/context-rail/context-rail-expense-form-state.ts");

    expect(expensesPage).toContain("./hooks/use-trip-expenses-page-state");
    expect(expensesPage).toContain("./components/ExpensePageHeader");
    expect(expensesPage).not.toContain("formatTripRange");
    expect(expensesPage).not.toContain("TravelMotif");
    expect(expensesPage).not.toContain("useState");
    expect(expensesPage).not.toContain("useMemo");
    expect(expensesPage).not.toContain("buildExpenseCsv");
    expect(expensesPage).not.toContain("refundSplits");
    expect(expensesPage).not.toContain("function recordRefund");
    expect(expensesState).toContain("./useExpenseDialogTargetState");
    expect(expensesState).toContain("./useExpensePageFilters");
    expect(expensesState).toContain("./useExpensePageDerivedState");
    expect(expensesState).toContain("./useExpenseSettlementActions");
    expect(expensesState).not.toContain("../model/expense-page-actions");
    expect(expensesState).toContain("./useExpenseLedgerActions");
    expect(expensesState).toContain("export function useTripExpensesPageState");
    expect(expensesState).not.toContain("const [filterState, setFilterState]");
    expect(expensesState).not.toContain("const [query, setQuery]");
    expect(expensesState).not.toContain("const [payerFilter, setPayerFilter]");
    expect(expensesState).not.toContain("const [categoryFilter, setCategoryFilter]");
    expect(expensesState).not.toContain("const [dialogExpense, setDialogExpense]");
    expect(expensesState).not.toContain("buildExpenseStatement");
    expect(expensesState).not.toContain("currentMemberExpenseBalance");
    expect(expensesState).not.toContain("expenseCategorySpend");
    expect(expensesState).not.toContain("filterExpenses");
    expect(expensesState).not.toContain("filterInferredScopeExpenses");
    expect(expenseDialogTargetState).toContain("const [dialogExpense, setDialogExpense]");
    expect(expenseDialogTargetState).toContain("async function createDialogExpense");
    expect(expenseDialogTargetState).toContain("async function updateDialogExpense");
    expect(expenseDialogTargetState).toContain("export function useExpenseDialogTargetState");
    expect(expensePageFilters).toContain("../model/expense-page-filter-state");
    expect(expensePageFilters).toContain("const [filterState, setFilterState]");
    expect(expensePageFilters).toContain("export function useExpensePageFilters");
    expect(expensePageHeader).toContain("export function ExpensePageHeader");
    expect(expensePageHeader).toContain("PageHeader");
    expect(expensePageHeader).toContain("formatTripRange");
    expect(expensePageHeader).toContain("TravelMotif");
    expect(expensesState).not.toContain("buildExpenseCsv");
    expect(expensesState).not.toContain("buildSettlementExpenseInput");
    expect(expensesState).not.toContain("buildRefundExpenseInput");
    expect(expensesState).not.toContain("function filterExpenses");
    expect(expensesState).not.toContain("refundSplits");
    expect(expensesState).not.toContain("sumShares");
    expect(expenseFilters).toContain("export function filterExpenses");
    expect(expenseFilters).toContain("export function expenseCategorySpend");
    expect(expenseFilters).toContain("export function inferredScopeExpenses");
    expect(expensePageDerivedState).toContain("../model/expense-page-filters");
    expect(expensePageDerivedState).toContain("../model/expense-page-selectors");
    expect(expensePageDerivedState).toContain("buildExpenseStatement");
    expect(expensePageDerivedState).toContain("currentMemberExpenseBalance");
    expect(expensePageDerivedState).toContain("export function useExpensePageDerivedState");
    expect(expenseOverviewPanels).toContain("../model/expense-overview-display");
    expect(expenseOverviewPanels).not.toContain("t.expenses.balance.owed");
    expect(expenseOverviewPanels).not.toContain("t.expenses.balance.payback");
    expect(expenseOverviewPanels).not.toContain("formatMoney");
    expect(expenseOverviewPanels).not.toContain("formatReminderDate");
    expect(expenseOverviewPanels).not.toContain("findMemberById");
    expect(expenseOverviewPanels).not.toContain("categoryTone");
    expect(expenseOverviewPanels).not.toContain("@/src/trip/trip-plans");
    expect(expenseOverviewPanels).not.toContain("tripPlanName(trip");
    expect(expenseOverviewPanels).not.toContain("categorySpendDisplay");
    expect(expenseOverviewPanels).not.toContain("scopeAuditExpenseDisplay");
    expect(expenseOverviewSections).toContain("../model/expense-overview-display");
    expect(expenseOverviewSections).toContain("categorySpendDisplay");
    expect(expenseOverviewSections).toContain("scopeAuditExpenseDisplay");
    expect(expenseOverviewDisplay).toContain("./expense-overview-balance-display");
    expect(expenseOverviewDisplay).toContain("./expense-overview-row-display");
    expect(expenseOverviewDisplay).toContain("./expense-overview-settlement-display");
    expect(expenseOverviewBalanceDisplay).toContain("export function expenseMemberBalanceDisplay");
    expect(expenseOverviewRowDisplay).toContain("export function categorySpendDisplay");
    expect(expenseOverviewRowDisplay).toContain("export function scopeAuditExpenseDisplay");
    expect(expenseOverviewRowDisplay).toContain("export function categorySpendAmountLabel");
    expect(expenseOverviewSettlementDisplay).toContain("export function settlementSuggestionLabel");
    expect(expenseOverviewSettlementDisplay).toContain("export function settlementSuggestionDisplay");
    expect(expenseOverviewSettlementDisplay).toContain("export function settlementReminderLabel");
    expect(expenseFilterState).toContain("export interface ExpensePageFilterState");
    expect(expenseFilterState).toContain("initialExpensePageFilterState");
    expect(expenseFilterState).toContain("clearedExpensePageFilterState");
    expect(expenseActions).toContain("export function buildSettlementExpenseInput");
    expect(expenseSettlementActions).toContain("../model/expense-page-actions");
    expect(expenseSettlementActions).toContain("buildSettlementExpenseInput");
    expect(expenseSettlementActions).toContain("buildRefundExpenseInput");
    expect(expenseSettlementActions).toContain("export function useExpenseSettlementActions");
    expect(expenseActions).toContain("export function buildRefundExpenseInput");
    expect(expenseActions).toContain("refundSplits");
    expect(expenseActions).toContain("sumShares");
    expect(expenseLedgerSection).toContain("./ExpenseLedgerRows");
    expect(expenseLedgerSection).not.toContain("../model/expense-ledger-display");
    expect(expenseLedgerSection).not.toContain("findItineraryItemById");
    expect(expenseLedgerSection).not.toContain("categoryTone");
    expect(expenseLedgerSection).not.toContain("refundAmount");
    expect(expenseLedgerSection).not.toContain("sumShares");
    expect(expenseLedgerSection).not.toContain("formatMoney");
    expect(expenseLedgerSection).not.toContain("findMemberById");
    expect(expenseLedgerSection).not.toContain("memberInitial");
    expect(expenseLedgerRows).toContain("../model/expense-ledger-display");
    expect(expenseLedgerRows).toContain("findItineraryItemById");
    expect(expenseLedgerRows).toContain("categoryTone");
    expect(expenseLedgerDisplay).toContain("export function expenseLedgerRowDisplay");
    expect(expenseLedgerDisplay).toContain("export function expenseLedgerPayerDisplay");
    expect(expenseSummaryStats).toContain("../model/expense-summary-display");
    expect(expenseSummaryStats).toContain("expenseStyles.summaryValueToneClassNames");
    expect(expenseSummaryStats).not.toContain("const summaryValueToneClassNames");
    expect(expenseSummaryStats).not.toContain("formatMoney");
    expect(expenseSummaryDisplay).toContain("export function expenseSummaryDisplay");
    expect(expenseStyles).toContain("export const summaryValueToneClassNames");
    expect(expenseLedgerActions).toContain("export function useExpenseLedgerActions");
    expect(expenseLedgerActions).toContain("buildExpenseCsv");
    expect(expenseLedgerActions).toContain("buildPaybackReminder");
    expect(expensesState).not.toContain("function recordRefund");
    expect(expenseSettlementActions).toContain("function recordRefund");
    expect(expenseSettlementActions).toContain("function recordSettlement");
    expect(expenseDialog).toContain("../hooks/useExpenseDialogState");
    expect(expenseDialog).toContain("./ExpenseDialogFormContent");
    expect(expenseDialog).not.toContain("useState");
    expect(expenseDialog).not.toContain("calculateExpenseDialogState");
    expect(expenseDialog).not.toContain("function submitExpense");
    expect(expenseDialog).not.toContain("ExpenseDetailsFields");
    expect(expenseDialog).not.toContain("ExpenseSplitFields");
    expect(expenseDialog).not.toContain("ExpenseCommentsSection");
    expect(expenseDialog).not.toContain("ExpenseDialogSummary");
    expect(expenseDialogFormContent).toContain("ExpenseDetailsFields");
    expect(expenseDialogFormContent).toContain("ExpenseSplitFields");
    expect(expenseDialogFormContent).toContain("ExpenseCommentsSection");
    expect(expenseDialogFormContent).toContain("ExpenseDialogSummary");
    expect(expenseDialogState).toContain("export function useExpenseDialogState");
    expect(expenseDialogState).toContain("useExpenseDialogFormValues");
    expect(expenseDialogState).toContain("useExpenseDialogLinkingState");
    expect(expenseDialogState).toContain("useExpenseSplitEditor");
    expect(expenseDialogState).toContain("useExpenseDialogSubmitHandler");
    expect(expenseDialogState).not.toContain("const [uiState, setUiState]");
    expect(expenseDialogState).not.toContain("expenseDialogLinkedItem");
    expect(expenseDialogState).not.toContain("expenseDialogItemSelectionFields");
    expect(expenseDialogState).not.toContain("const [formValues, setFormValues]");
    expect(expenseDialogState).not.toContain("function updateFormValue");
    expect(expenseDialogState).not.toContain("function submitExpense");
    expect(expenseDialogState).not.toContain("submitExpenseDialog");
    expect(expenseDialogState).not.toContain("buildExpenseDialogSubmitInput");
    expect(expenseDialogSubmitHandler).toContain("export function useExpenseDialogSubmitHandler");
    expect(expenseDialogSubmitHandler).toContain("function submitExpense");
    expect(expenseDialogSubmitHandler).toContain("buildExpenseDialogSubmitInput");
    expect(expenseDialogSubmitHandler).toContain("submitExpenseDialog");
    expect(expenseDialogState).not.toContain("await onUpdateExpense");
    expect(expenseDialogState).not.toContain("await onCreateExpense");
    expect(expenseDialogSubmitAction).toContain("export async function submitExpenseDialog");
    expect(expenseDialogSubmitAction).toContain("await onUpdateExpense");
    expect(expenseDialogSubmitAction).toContain("await onCreateExpense");
    expect(expenseDialogState).not.toContain("const [title, setTitle]");
    expect(expenseDialogState).not.toContain("const [amount, setAmount]");
    expect(expenseDialogState).not.toContain("const [currency, setCurrency]");
    expect(expenseDialogState).not.toContain("const [isSaving, setIsSaving]");
    expect(expenseDialogState).not.toContain("const [tripPlanId, setTripPlanId]");
    expect(expenseDialogFormValues).toContain("const [formValues, setFormValues]");
    expect(expenseDialogFormValues).toContain("const updateFormValue");
    expect(expenseDialogFormValues).toContain("expenseDialogCurrencyChangeFields");
    expect(expenseDialogFormValues).toContain("expenseDialogManualExchangeRateFields");
    expect(expenseDialogLinkingState).toContain("const [uiState, setUiState]");
    expect(expenseDialogLinkingState).toContain("expenseDialogLinkedItem");
    expect(expenseDialogLinkingState).toContain("expenseDialogItemSelectionFields");
    expect(expenseDialogLinkingState).toContain("setExpenseDialogSaving");
    expect(expenseSplitEditor).toContain("initialExpenseSplitEditorState");
    expect(expenseSplitEditor).toContain("const [state, setState]");
    expect(expenseSplitEditor).not.toContain("const [splitMode, setSplitMode]");
    expect(expenseSplitEditor).not.toContain("const [splitValues, setSplitValues]");
    expect(expenseSplitEditor).not.toContain("const [lineItems, setLineItems]");
    expect(expenseSplitEditorModel).toContain("export interface ExpenseSplitEditorState");
    expect(expenseSplitEditorModel).toContain("export function changeExpenseSplitEditorMode");
    expect(expenseDialogSummary).toContain("../model/expense-dialog-summary-display");
    expect(expenseDialogSummary).not.toContain("formatMoney");
    expect(expenseDialogSummary).not.toContain("copy.settleValue");
    expect(expenseDialogSummaryDisplay).toContain("export function expenseDialogSummaryDisplay");
    expect(expenseDialogSummaryDisplay).toContain("formatMoney");
    expect(expenseCommentsSection).toContain("../model/expense-comments-state");
    expect(expenseCommentsSection).not.toContain("findMemberById");
    expect(expenseCommentsState).toContain("export function expenseCommentDisplay");
    expect(contextRailExpenseForm).toContain("./context-rail-expense-form-state");
    expect(contextRailExpenseForm).toContain("./use-context-rail-expense-form-actions");
    expect(contextRailExpenseForm).toContain("const [state, setState]");
    expect(contextRailExpenseForm).toContain("function updateFormValue");
    expect(contextRailExpenseForm).not.toContain("function submitExpense");
    expect(contextRailExpenseFormActions).toContain("export function useContextRailExpenseFormActions");
    expect(contextRailExpenseFormActions).toContain("function submitExpense");
    expect(contextRailExpenseFormActions).toContain("buildContextRailExpenseSubmission");
    expect(contextRailExpenseFormActions).toContain("resetContextRailExpenseFormAfterSubmit");
    expect(contextRailExpenseForm).not.toContain("interface ContextRailExpenseFormState");
    expect(contextRailExpenseForm).not.toContain("const [editingExpenseId, setEditingExpenseId]");
    expect(contextRailExpenseForm).not.toContain("const [formValues, setFormValues]");
    expect(contextRailExpenseForm).not.toContain("const [expenseTitle, setExpenseTitle]");
    expect(contextRailExpenseForm).not.toContain("const [expenseAmount, setExpenseAmount]");
    expect(contextRailExpenseFormState).toContain("export interface ContextRailExpenseFormState");
    expect(contextRailExpenseFormState).toContain("export interface ContextRailExpenseSubmission");
    expect(contextRailExpenseFormState).toContain("export function buildContextRailExpenseSubmission");
    expect(contextRailExpenseFormState).toContain("contextRailExpenseCategoryOptions");
    expect(contextRailExpenseFormState).toContain("startContextRailExpenseEdit");
  });
});
