import { describe, expect, it } from "vitest";
import { readItineraryArchitectureSource } from "./project-itinerary-architecture.test-support";

describe("Sagittarius itinerary activity modal architecture", () => {
  it("keeps itinerary ticket modal form state split from modal render", () => {
    const noteModal = readItineraryArchitectureSource("src/features/itinerary/components/smart-itinerary-table/activity-cell/ItineraryNoteModal.tsx");
    const noteModel = readItineraryArchitectureSource("src/features/itinerary/components/smart-itinerary-table/activity-cell/use-itinerary-note-modal-model.ts");
    const noteActions = readItineraryArchitectureSource("src/features/itinerary/components/smart-itinerary-table/activity-cell/use-itinerary-note-modal-actions.ts");
    const noteState = readItineraryArchitectureSource("src/features/itinerary/components/smart-itinerary-table/activity-cell/itinerary-note-modal-state.ts");
    const noteDisplay = readItineraryArchitectureSource("src/features/itinerary/domain/itinerary-note-display.ts");
    const modalHeader = readItineraryArchitectureSource("src/features/itinerary/components/smart-itinerary-table/activity-cell/ActivityCellModalHeader.tsx");
    const modalActions = readItineraryArchitectureSource("src/features/itinerary/components/smart-itinerary-table/activity-cell/ActivityCellModalActions.tsx");
    const ticketModal = readItineraryArchitectureSource("src/features/itinerary/components/smart-itinerary-table/activity-cell/ItineraryTicketModal.tsx");
    const modalPortal = readItineraryArchitectureSource("src/features/itinerary/components/smart-itinerary-table/activity-cell/ActivityCellModalPortal.tsx");
    const bookingButton = readItineraryArchitectureSource("src/features/itinerary/components/smart-itinerary-table/activity-cell/ItineraryBookingButton.tsx");
    const ticketFooter = readItineraryArchitectureSource("src/features/itinerary/components/smart-itinerary-table/activity-cell/ItineraryTicketModalFooter.tsx");
    const existingTicketList = readItineraryArchitectureSource("src/features/itinerary/components/smart-itinerary-table/activity-cell/ExistingTicketList.tsx");
    const ticketFieldGrid = readItineraryArchitectureSource("src/features/itinerary/components/smart-itinerary-table/activity-cell/TicketFieldGrid.tsx");
    const linkedActivitiesPicker = readItineraryArchitectureSource("src/features/itinerary/components/smart-itinerary-table/activity-cell/LinkedActivitiesPicker.tsx");
    const ticketModeToggle = readItineraryArchitectureSource("src/features/itinerary/components/smart-itinerary-table/activity-cell/TicketModeToggle.tsx");
    const ticketModel = readItineraryArchitectureSource("src/features/itinerary/components/smart-itinerary-table/activity-cell/use-itinerary-ticket-modal-model.ts");
    const ticketActions = readItineraryArchitectureSource("src/features/itinerary/components/smart-itinerary-table/activity-cell/use-itinerary-ticket-modal-actions.ts");
    const ticketFormValues = readItineraryArchitectureSource("src/features/itinerary/components/smart-itinerary-table/activity-cell/use-itinerary-ticket-form-values.ts");
    const ticketViewState = readItineraryArchitectureSource("src/features/itinerary/components/smart-itinerary-table/activity-cell/itinerary-ticket-modal-view-state.ts");
    const ticketForm = readItineraryArchitectureSource("src/features/itinerary/domain/booking-ticket-form.ts");

    expect(noteModal).toContain("./use-itinerary-note-modal-model");
    expect(noteModal).toContain("./ActivityCellModalHeader");
    expect(noteModal).not.toContain("useState");
    expect(noteModel).toContain("export function useItineraryNoteModalModel");
    expect(noteModel).toContain("@/src/features/itinerary/domain/itinerary-note-display");
    expect(noteModel).toContain("./itinerary-note-modal-state");
    expect(noteModel).toContain("./use-itinerary-note-modal-actions");
    expect(noteModel).toContain("const [state, setState]");
    expect(noteModel).not.toContain("async function submit");
    expect(noteActions).toContain("export function useItineraryNoteModalActions");
    expect(noteActions).toContain("async function submit");
    expect(noteActions).toContain("buildItineraryNoteModalSubmission");
    expect(noteActions).toContain("setItineraryNoteModalSaving");
    expect(noteState).toContain("export function buildItineraryNoteModalSubmission");
    expect(noteModel).not.toContain('locale === "th"');
    expect(noteModel).not.toContain("Close note modal");
    expect(noteModel).not.toContain("const [body, setBody]");
    expect(noteModel).not.toContain("const [saving, setSaving]");
    expect(noteDisplay).toContain("export function itineraryNoteModalCopy");
    expect(noteDisplay).toContain("export interface ItineraryNoteModalCopy");
    expect(ticketModal).toContain("./use-itinerary-ticket-modal-model");
    expect(ticketModal).toContain("./ActivityCellModalHeader");
    expect(bookingButton).toContain("export function ItineraryBookingButton");
    expect(bookingButton).toContain("./ItineraryTicketModal");
    expect(bookingButton).not.toContain("BookingComponents");
    expect(ticketModal).toContain("./ItineraryTicketModalFooter");
    expect(ticketModal).toContain("./ExistingTicketList");
    expect(ticketModal).toContain("./LinkedActivitiesPicker");
    expect(ticketModal).toContain("./TicketFieldGrid");
    expect(ticketModal).toContain("./TicketModeToggle");
    expect(ticketModal).toContain("./ActivityCellModalPortal");
    expect(ticketModal).not.toContain("createPortal");
    expect(ticketModal).not.toContain("@/src/shared/hooks/use-escape-to-close");
    expect(ticketModal).not.toContain("useState");
    expect(ticketModal).not.toContain("buildTicketSubmitInput");
    expect(ticketModal).not.toContain("formatBookingSummary");
    expect(ticketModal).not.toContain("DateTimePickerField");
    expect(ticketFooter).toContain("export function ItineraryTicketModalFooter");
    expect(existingTicketList).toContain("export function ExistingTicketList");
    expect(existingTicketList).toContain("formatBookingSummary");
    expect(ticketFieldGrid).toContain("export function TicketFieldGrid");
    expect(ticketFieldGrid).toContain("DateTimePickerField");
    expect(linkedActivitiesPicker).toContain("export function LinkedActivitiesPicker");
    expect(linkedActivitiesPicker).toContain("toggleId");
    expect(ticketModeToggle).toContain("export function TicketModeToggle");
    expect(ticketModel).toContain("export function useItineraryTicketModalModel");
    expect(ticketModel).toContain("@/src/features/itinerary/domain/booking-ticket-form");
    expect(ticketModel).toContain("./use-itinerary-ticket-modal-actions");
    expect(ticketModel).toContain("./use-itinerary-ticket-form-values");
    expect(ticketModel).toContain("./itinerary-ticket-modal-view-state");
    expect(ticketModel).toContain("const [viewState, setViewState]");
    expect(ticketModel).not.toContain("buildTicketSubmitInput");
    expect(ticketModel).not.toContain("beginItineraryTicketModalViewSave");
    expect(ticketActions).toContain("export function useItineraryTicketModalActions");
    expect(ticketActions).toContain("buildTicketSubmitInput");
    expect(ticketActions).toContain("beginItineraryTicketModalViewSave");
    expect(ticketActions).toContain("beginItineraryTicketModalViewUnlink");
    expect(ticketModel).not.toContain("type TicketFormValues");
    expect(ticketModel).not.toContain("const [formValues, setFormValues]");
    expect(ticketModel).not.toContain("@/src/shared/form-state");
    expect(ticketModel).not.toContain("function updateTicketField");
    expect(ticketFormValues).toContain("export function useItineraryTicketFormValues");
    expect(ticketFormValues).toContain("type TicketFormValues");
    expect(ticketFormValues).toContain("const [formValues, setFormValues]");
    expect(ticketFormValues).toContain("@/src/shared/form-state");
    expect(ticketFormValues).toContain("function updateTicketField");
    expect(ticketFormValues).toContain("buildTicketFormValues");
    expect(ticketModel).not.toContain("function buildTicketSubmitInput");
    expect(ticketModel).not.toContain("const [mode, setMode]");
    expect(ticketModel).not.toContain("const [selectedBookingId, setSelectedBookingId]");
    expect(ticketModel).not.toContain("const [submitState, setSubmitState]");
    expect(ticketModel).not.toContain("const [title, setTitle]");
    expect(ticketModel).not.toContain("const [providerName, setProviderName]");
    expect(ticketModel).not.toContain("const [saving, setSaving]");
    expect(ticketModel).not.toContain("const [unlinking, setUnlinking]");
    expect(ticketViewState).toContain("export interface ItineraryTicketModalViewState");
    expect(ticketViewState).toContain("./itinerary-ticket-modal-submit-state");
    expect(ticketViewState).toContain("buildInitialItineraryTicketModalViewState");
    expect(ticketForm).toContain("export function buildTicketSubmitInput");
    expect(ticketForm).toContain("export interface TicketFormValues");
    expect(modalPortal).toContain("export function ActivityCellModalPortal");
    expect(modalPortal).toContain("createPortal");
    expect(modalPortal).toContain("@/src/shared/hooks/use-escape-to-close");
    expect(modalHeader).toContain("export function ActivityCellModalHeader");
    expect(modalHeader).toContain("subActivityModalCloseClassName");
    expect(modalActions).toContain("export function ActivityCellModalActions");
    expect(modalActions).toContain("saveIconName");
    expect(ticketFooter).toContain("./ActivityCellModalActions");
  });
});
