import type { SeedItineraryItemInput } from "../seed-itinerary-types";

export const arrivalDayItineraryItems: SeedItineraryItemInput[] = [
  {
    id: "item-flight-bkk-hkg",
    day: "2026-06-18",
    sortOrder: 100,
    startTime: "09:00",
    activity: "เดินทางออกจากกรุงเทพฯ (BKK)",
    activityType: "travel",
    place: "Bangkok → Hong Kong",
    linkLabel: "QR349",
    mapLink: "https://maps.google.com/?q=Bangkok+Airport",
    coordinates: { lat: 13.69, lng: 100.7501 },
    durationMinutes: null,
    transportation: "CT ✓ → HKG",
    note: "เตรียมพาสปอร์ตและเอกสารเข้าเมืองไว้ในกระเป๋าถือ",
  },
  {
    id: "item-arrive-hkg",
    day: "2026-06-18",
    sortOrder: 200,
    startTime: "12:55",
    activity: "ถึง Hong Kong International Airport",
    activityType: "travel",
    place: "Hong Kong International Airport",
    linkLabel: "HKG",
    mapLink: "https://maps.google.com/?q=Hong+Kong+International+Airport",
    coordinates: { lat: 22.308, lng: 113.9185 },
    durationMinutes: null,
    transportation: "",
    note: "รอรับกระเป๋าและซื้อ Octopus Card ถ้ายังไม่มี",
  },
  {
    id: "item-airport-express",
    day: "2026-06-18",
    sortOrder: 300,
    startTime: "14:00",
    activity: "Airport Express ไป Kowloon",
    activityType: "travel",
    place: "Kowloon Station",
    linkLabel: "Airport Express",
    mapLink: "https://maps.google.com/?q=Kowloon+Station",
    coordinates: { lat: 22.3048, lng: 114.1615 },
    durationMinutes: 24,
    transportation: "Airport Express",
    note: "เช็คเวลา shuttle หรือเรียกแท็กซี่ต่อเข้าโรงแรม",
  },
  {
    id: "item-hotel-checkin",
    day: "2026-06-18",
    sortOrder: 400,
    startTime: "14:30",
    activity: "เช็คอินที่โรงแรม (Tsim Sha Tsui)",
    activityType: "stay",
    place: "The Elements / Tsim Sha Tsui",
    linkLabel: "โรงแรม",
    mapLink: "https://maps.google.com/?q=Tsim+Sha+Tsui+hotel",
    coordinates: { lat: 22.2993, lng: 114.1722 },
    durationMinutes: 30,
    transportation: "แท็กซี่",
    note: "ฝากกระเป๋าก่อนออกไปเดินริมอ่าว",
  },
  {
    id: "item-avenue-stars",
    day: "2026-06-18",
    sortOrder: 500,
    startTime: "16:00",
    activity: "Avenue of Stars (星光大道)",
    activityType: "attraction",
    place: "Tsim Sha Tsui promenade",
    linkLabel: "แผนที่",
    mapLink: "https://maps.google.com/?q=Avenue+of+Stars+Hong+Kong",
    coordinates: { lat: 22.2931, lng: 114.1743 },
    durationMinutes: 60,
    transportation: "เดิน",
    note: "จุดถ่ายรูปริมอ่าว เหมาะสำหรับดูแสงเย็น",
  },
  {
    id: "item-symphony-lights",
    day: "2026-06-18",
    sortOrder: 600,
    startTime: "17:30",
    activity: "Symphony of Lights",
    activityType: "experience",
    place: "Victoria Harbour",
    linkLabel: "แผนที่",
    mapLink: "https://maps.google.com/?q=Symphony+of+Lights",
    coordinates: { lat: 22.2935, lng: 114.1696 },
    durationMinutes: 20,
    transportation: "เดิน",
    note: "เผื่อเวลาหามุมยืนก่อนแสงเริ่ม",
  },
  {
    id: "item-temple-street",
    day: "2026-06-18",
    sortOrder: 700,
    startTime: "19:00",
    activity: "อาหารเย็นที่ Temple Street Night Market",
    activityType: "food",
    place: "Temple Street",
    linkLabel: "แผนที่",
    mapLink: "https://maps.google.com/?q=Temple+Street+Night+Market",
    coordinates: { lat: 22.3067, lng: 114.1707 },
    durationMinutes: 90,
    transportation: "เดิน / MTR",
    note: "เลือกร้านหน้างานตามคิวและเมนูที่ทุกคนกินได้",
  },
];
