import type { SeedItineraryItemInput } from "../seed-itinerary-types";

export const hongKongDayItineraryItems: SeedItineraryItemInput[] = [
  {
    id: "item-dimdim",
    day: "2026-06-19",
    sortOrder: 100,
    startTime: "08:30",
    activity: "Dim Dim Sum ที่ Tim Ho Wan",
    activityType: "food",
    place: "Shop G72, G/F, The Elements",
    linkLabel: "แผนที่",
    mapLink: "https://maps.google.com/?q=Dim+Dim+Sum+Tim+Ho+Wan+The+Elements+Hong+Kong",
    coordinates: { lat: 22.3049, lng: 114.1617 },
    address: "Shop G72, G/F, The Elements, 1 Austin Rd W, Tsim Sha Tsui",
    durationMinutes: 60,
    transportation: "เดิน",
    advisories: [{ code: "booking-recommended", label: "จองล่วงหน้าแนะนำ", severity: "warning" }],
    note: "ร้านนี้ได้รับคะแนนสูง 4.3/5 จากรีวิวจำนวนมาก เหมาะกับมื้อเช้าแบบไม่เร่ง",
    version: 4,
  },
  {
    id: "item-victoria-peak",
    day: "2026-06-19",
    sortOrder: 200,
    startTime: "10:00",
    activity: "Victoria Peak (The Peak Tram)",
    activityType: "attraction",
    place: "The Peak Tram",
    linkLabel: "แผนที่",
    mapLink: "https://maps.google.com/?q=The+Peak+Tram",
    coordinates: { lat: 22.2759, lng: 114.1455 },
    durationMinutes: 120,
    transportation: "Tram",
    advisories: [{ code: "crowd-window", label: "คนเยอะช่วงสาย", severity: "warning" }],
    note: "ถ้าคิวหนาแน่นให้ขยับไปช่วงบ่ายหรือใช้รถบัสขึ้นเขา",
  },
  {
    id: "item-pacific-place",
    day: "2026-06-19",
    sortOrder: 300,
    startTime: "12:30",
    activity: "ช้อปปิ้งที่ Pacific Place",
    activityType: "shopping",
    place: "Admiralty",
    linkLabel: "แผนที่",
    mapLink: "https://maps.google.com/?q=Pacific+Place+Hong+Kong",
    coordinates: { lat: 22.2776, lng: 114.1662 },
    durationMinutes: 90,
    transportation: "Taxi / เดิน",
    note: "พักเดินในห้างและหาเครื่องดื่มก่อนข้ามฝั่ง",
  },
  {
    id: "item-star-ferry",
    day: "2026-06-19",
    sortOrder: 400,
    startTime: "14:30",
    activity: "Star Ferry ไป Central",
    activityType: "travel",
    place: "Tsim Sha Tsui Pier",
    linkLabel: "แผนที่",
    mapLink: "https://maps.google.com/?q=Star+Ferry+Pier",
    coordinates: { lat: 22.2939, lng: 114.1698 },
    durationMinutes: 15,
    transportation: "เรือเฟอร์รี่",
    note: "เลือกชั้นบนถ้ามีที่ว่างเพื่อชมวิวอ่าว",
  },
  {
    id: "item-central-soho",
    day: "2026-06-19",
    sortOrder: 500,
    startTime: "15:00",
    activity: "เดินเล่นย่าน Central – SOHO",
    activityType: "experience",
    place: "Central / SOHO",
    linkLabel: "แผนที่",
    mapLink: "https://maps.google.com/?q=Central+SOHO+Hong+Kong",
    coordinates: { lat: 22.282, lng: 114.1523 },
    durationMinutes: 120,
    transportation: "เดิน",
    note: "คุม pace ให้ไม่เหนื่อยก่อนมื้อเย็น",
  },
  {
    id: "item-luk-yu",
    day: "2026-06-19",
    sortOrder: 600,
    startTime: "18:30",
    activity: "อาหารเย็น Luk Yu Tea House",
    activityType: "food",
    place: "Central",
    linkLabel: "แผนที่",
    mapLink: "https://maps.google.com/?q=Luk+Yu+Tea+House",
    coordinates: { lat: 22.2817, lng: 114.1565 },
    durationMinutes: 90,
    transportation: "MTR",
    advisories: [{ code: "booking-dinner", label: "จองล่วงหน้าแนะนำ", severity: "warning" }],
    note: "โทรยืนยันโต๊ะอีกครั้งช่วงบ่าย",
  },
];
