import type { SeedItineraryItemInput } from "../seed-itinerary-types";

export const shenzhenDayItineraryItems: SeedItineraryItemInput[] = [
  {
    id: "item-checkout",
    day: "2026-06-20",
    sortOrder: 100,
    startTime: "09:00",
    activity: "เช็คเอาท์จากโรงแรม",
    activityType: "stay",
    place: "Tsim Sha Tsui",
    linkLabel: "โรงแรม",
    mapLink: "https://maps.google.com/?q=Tsim+Sha+Tsui+hotel",
    coordinates: { lat: 22.2993, lng: 114.1722 },
    durationMinutes: 30,
    transportation: "เดิน",
    note: "ตรวจของก่อนออกจากห้อง",
  },
  {
    id: "item-shenzhen-transfer",
    day: "2026-06-20",
    sortOrder: 200,
    startTime: "10:00",
    activity: "เดินทางไป Shenzhen (Lo Wu / Lok Ma Chau)",
    activityType: "travel",
    place: "Lo Wu / Lok Ma Chau",
    linkLabel: "แผนที่",
    mapLink: "https://maps.google.com/?q=Lo+Wu+Control+Point",
    coordinates: { lat: 22.5316, lng: 114.1131 },
    durationMinutes: 60,
    transportation: "MTR / เดิน",
    advisories: [{ code: "passport", label: "พกพาสปอร์ต", severity: "warning" }],
    note: "เช็ควีซ่า อินเทอร์เน็ต และวิธีจ่ายเงินก่อนข้ามแดน",
  },
  {
    id: "item-shenzhen-hotel",
    day: "2026-06-20",
    sortOrder: 300,
    startTime: "11:30",
    activity: "เข้าพักโรงแรมที่ Shenzhen",
    activityType: "stay",
    place: "Shenzhen hotel",
    linkLabel: "โรงแรม",
    mapLink: "https://maps.google.com/?q=Shenzhen+hotel",
    coordinates: { lat: 22.5431, lng: 114.0579 },
    durationMinutes: 30,
    transportation: "แท็กซี่",
    note: "ฝากกระเป๋าและพักสั้นๆ ก่อนออกไปมื้อกลางวัน",
  },
];
