"use client";

import { useI18n } from "@/src/i18n/I18nProvider";
import {
  useWorkspaceCommands,
  useWorkspacePlanningContext,
  useWorkspaceSetupContext,
} from "./hooks";
import { nextClientMutationId } from "@/src/trip/local-ids";
import { seedTrip } from "@/src/trip/seed";
import { WorkspaceAppFrame } from "./WorkspaceAppFrame";
import {
  buildWorkspaceFrameProps,
} from "./props";
import type { SagittariusAppProps } from "./types";

export function SagittariusApp({
  initialView = "overview",
  requireJoin = false,
  dataSource = "local",
  apiClient,
  placeResolver,
  routeTripId,
  initialJoinCode,
  initialJoinToken,
  accessMode = "combined",
  accountSuccessRedirectHref,
  portalSection = "dashboard",
  initialMemberId,
  initialTrip = seedTrip,
}: SagittariusAppProps) {
  const { t } = useI18n();
  const {
    accountClient,
    accountClaimState,
    accessError,
    accountSession,
    accountSessionLoaded,
    apiBaseUrl,
    activePlanItems,
    backendExpenseSummary,
    canAccessPanel,
    canCreateStopNote,
    canCreateSuggestion,
    canEdit,
    canEditBookings,
    canEditExpenses,
    canEditPhotoAlbums,
    canManagePeople,
    canManageTripPlans,
    canReviewSuggestions,
    changeAccountSession,
    changeDayPath,
    clearDayPath,
    commitTrip,
    contextRailMounted,
    contextRailOpen,
    contextRailPreferredTab,
    createPhotoAlbum,
    currentMember,
    currentMemberId,
    currentView,
    dayPathOverrides,
    deletePhotoAlbum,
    dialogDeleteItem,
    dialogState,
    dismissWorkspaceToast,
    effectivePlaceResolver,
    isAccountTripAccessPending,
    isApiMode,
    isTripLoading,
    isTripPlanBusy,
    joinInviteToken,
    latestTripRef,
    mainPlanItems,
    navigateWorkspaceView,
    openExpensesWorkspace,
    participantSession,
    pathOptions,
    pathSelection,
    planItems,
    refreshBackendExpenseSummary,
    replaceApiTrip,
    replaceDailyBriefings,
    replaceWorkspacePath,
    resetBackendExpenseSummary,
    resetDailyBriefings,
    resetTrip,
    resolvedApiClient,
    saveDailyBriefingOverrides,
    selectedItemId,
    selectedTripPathId,
    selectedTripPlanId,
    sessionMember,
    sessionRestored,
    setAccessError,
    setAccountClaimState,
    setBackendExpenseSummary,
    setContextRailPreferredTab,
    setContextRailVisibility,
    setCurrentMemberId,
    setDialogDeleteItem,
    setDialogState,
    setIsCockpitLoaded,
    setIsTripPlanBusy,
    setJoinInviteToken,
    setParticipantSession,
    setSelectedItemId,
    setSelectedTripPlanId,
    setStopPlaceResolution,
    setTripPlanError,
    setTripState,
    shouldRedirectUnauthenticatedTripRoute,
    sidebarCollapsed,
    showAllPaths,
    stopPlaceResolution,
    supportsContextRail,
    toggleContextRail,
    toggleSidebarCollapsed,
    toggleShowAllPaths,
    toastDismissed,
    toastDismissing: isToastDismissing,
    trip,
    tripPlanError,
    updateApiTrip,
    updatePhotoAlbum,
    visibleDailyBriefings,
  } = useWorkspaceSetupContext({
    accessMode,
    apiClient,
    dataSource,
    initialJoinToken,
    initialMemberId,
    initialTrip,
    initialView,
    placeResolver,
    requireJoin,
    routeTripId,
  });

  const {
    createItineraryNote,
    createStopNote,
    createTask,
    createTripPlan,
    deleteStopNote,
    expenseSummary,
    itineraryView,
    mainItineraryView,
    renameTripPlan,
    replaceCockpitFromApi,
    reviewSuggestion,
    scopedSuggestions,
    scopedTripForRecords,
    scopedTripPlanRecords,
    selectTripPlan,
    selectedDay,
    selectedItem,
    selectedItemIdForView,
    setStopNotes,
    setMainTripPlan,
    setTasks,
    stopNotes,
    suggestSelectedStop,
    tasks,
    toggleTaskStatus,
    updateStopNote,
    updateTripPlanStatus,
  } = useWorkspacePlanningContext({
    activePlanItems,
    backendExpenseSummary,
    canCreateStopNote,
    canCreateSuggestion,
    canReviewSuggestions,
    canEdit,
    canManageTripPlans,
    commitTrip,
    currentMember,
    initialTrip,
    isApiMode,
    latestTripRef,
    mainPlanItems,
    participantSession,
    planItems,
    replaceDailyBriefings,
    resetBackendExpenseSummary,
    resetDailyBriefings,
    resolvedApiClient,
    selectedItemId,
    selectedTripPlanId,
    sessionRestored,
    setAccessError,
    setContextRailPreferredTab,
    setIsCockpitLoaded,
    setIsTripPlanBusy,
    setParticipantSession,
    setSelectedItemId,
    setSelectedTripPlanId,
    setTripPlanError,
    setTripState,
    trip,
    tripPlanErrorMessage: t.itinerary.tripPlans.error,
    updateApiTrip,
  });

  const {
    addStop,
    addSubActivity,
    applyPendingItineraryImport,
    authenticateParticipant,
    changeBookingDocQuickFields,
    changeBookingDocType,
    changeMemberAccessStatus,
    changeMemberPassword,
    changeMemberRole,
    claimCurrentMemberToAccount,
    clearPendingItineraryImport,
    createBookingDoc,
    createExpense,
    createItineraryBookingDraft,
    createMember,
    createStop,
    deleteBookingDoc,
    deleteExpense,
    deleteSelectedStop,
    deleteStop,
    duplicateExpenseAsEstimate,
    editItem,
    importItineraryError,
    leaveParticipantSession,
    moveItemToPath,
    openItemDetails,
    pendingItineraryImport,
    promoteFoodRecommendation,
    recordPaybackReminder,
    replaceTripFromJoin,
    resetMemberClaim,
    resolveMissingMapCoordinates,
    rotateJoinInviteToken,
    saveItineraryBookingTicket,
    saveTripSettings,
    selectItem,
    transferOwnerToAccountMember,
    unlinkBookingFromItineraryItem,
    updateBookingDoc,
    updateExpense,
    updateItineraryItemInline,
    updateSelectedStop,
  } = useWorkspaceCommands({
    canEdit,
    canEditBookings,
    canEditExpenses,
    canManagePeople,
    canSaveItineraryErrorMessage: t.itinerary.saveError,
    accountClient,
    accountSession,
    activeMemberId: currentMember.id,
    commitTrip,
    currentMemberId,
    dialogState,
    effectivePlaceResolver,
    initialTrip,
    isApiMode,
    latestTripRef,
    nextClientMutationId,
    pathOptions,
    pathSelection,
    planItems,
    participantSession,
    refreshBackendExpenseSummary,
    replaceApiTrip,
    replaceCockpitFromApi,
    replaceWorkspacePath,
    resetTrip,
    resolvedApiClient,
    routeTripId,
    selectedDay,
    selectedItemId,
    selectedTripPlanId,
    setAccessError,
    setAccountClaimState,
    setBackendExpenseSummary,
    setContextRailPreferredTab,
    setContextRailVisibility,
    setCurrentMemberId,
    setDialogDeleteItem,
    setDialogState,
    setIsCockpitLoaded,
    setJoinInviteToken,
    setParticipantSession,
    setSelectedItemId,
    setStopNotes,
    setStopPlaceResolution,
    setTasks,
    setTripPlanError,
    stopNotes,
    tasks,
    trip,
    tripPlanErrorMessage: t.itinerary.tripPlans.error,
    updateApiTrip,
  });

  const frameProps = buildWorkspaceFrameProps({
    accessError,
    accessMode,
    accountClaimState,
    accountClient,
    accountSession,
    accountSessionLoaded,
    accountSuccessRedirectHref,
    activePlanItems,
    apiBaseUrl,
    applyPendingItineraryImport,
    authenticateParticipant,
    bookingDocs: scopedTripPlanRecords.bookingDocs,
    canAccessPanel,
    canCreateStopNote,
    canCreateSuggestion,
    canEdit,
    canEditBookings,
    canEditExpenses,
    canEditPhotoAlbums,
    canManagePeople,
    canReviewSuggestions,
    changeBookingDocQuickFields,
    changeBookingDocType,
    claimCurrentMemberToAccount,
    clearPendingItineraryImport,
    contextRailMounted,
    contextRailOpen,
    contextRailPreferredTab,
    createBookingDoc,
    createExpense,
    createItineraryNote,
    createStop,
    currentMember,
    currentView,
    dailyBriefings: visibleDailyBriefings,
    dayPathOverrides,
    deleteExpense,
    deleteSelectedStop,
    deleteStop,
    deleteStopNote,
    dialogDeleteItem,
    dialogState,
    dismissWorkspaceToast,
    editItem,
    expenseSummary,
    effectivePlaceResolver,
    importItineraryError,
    initialJoinCode,
    initialJoinToken,
    itineraryView,
    isAccountTripAccessPending,
    isApiMode,
    isToastDismissing,
    isTripLoading,
    isTripPlanBusy,
    joinInviteToken,
    leaveParticipantSession,
    mainItineraryView,
    mainPlanItems,
    navigateWorkspaceView,
    onAddBookingForItem: createItineraryBookingDraft,
    onAddStop: addStop,
    onAddSubActivity: addSubActivity,
    onChangeDayPath: changeDayPath,
    onChangeMemberAccessStatus: changeMemberAccessStatus,
    onChangeMemberPassword: changeMemberPassword,
    onChangeMemberRole: changeMemberRole,
    onChangeTripPlan: selectTripPlan,
    onChangeTripPlanStatus: updateTripPlanStatus,
    onClearDayPath: clearDayPath,
    onCreateExpense: createExpense,
    onCreateMember: createMember,
    onCreatePhotoAlbum: createPhotoAlbum,
    onCreateTask: createTask,
    onCreateTripPlan: createTripPlan,
    onDeleteBookingDoc: deleteBookingDoc,
    onDeleteExpense: deleteExpense,
    onDeleteItem: deleteStop,
    onDeletePhotoAlbum: deletePhotoAlbum,
    onDuplicateExpenseAsEstimate: duplicateExpenseAsEstimate,
    onEditItem: editItem,
    onMoveItemToPath: moveItemToPath,
    onOpenExpenses: openExpensesWorkspace,
    onOpenItemDetails: openItemDetails,
    onRecordPaybackReminder: recordPaybackReminder,
    onRenameTripPlan: renameTripPlan,
    onResetMemberClaim: resetMemberClaim,
    onSaveDailyBriefingOverrides: saveDailyBriefingOverrides,
    onSaveItineraryBookingTicket: saveItineraryBookingTicket,
    onSaveTripSettings: saveTripSettings,
    onSelectItem: selectItem,
    onSetMainTripPlan: setMainTripPlan,
    onToggleContextRail: toggleContextRail,
    onToggleShowAllPaths: toggleShowAllPaths,
    onToggleTaskStatus: toggleTaskStatus,
    onUnlinkBookingForItem: unlinkBookingFromItineraryItem,
    onUpdateBookingDoc: updateBookingDoc,
    onUpdateExpense: updateExpense,
    onUpdateItemInline: updateItineraryItemInline,
    onUpdatePhotoAlbum: updatePhotoAlbum,
    onAccountSessionChange: changeAccountSession,
    onCockpitLoaded: replaceCockpitFromApi,
    pendingItineraryImport,
    pathOptions,
    photoAlbumLinks: trip.photoAlbumLinks ?? [],
    planItems,
    portalSection,
    promoteFoodRecommendation,
    participantSession,
    replaceTripFromJoin,
    requireJoin,
    resolvedApiClient,
    resolveMissingMapCoordinates,
    reviewSuggestion,
    rotateJoinInviteToken,
    routeTripId,
    saveDailyBriefingOverrides,
    scopedSuggestions,
    scopedTripForRecords,
    scopedTripPlanRecords,
    selectedDay,
    selectedItem,
    selectedItemIdForView,
    selectedTripPathId,
    selectedTripPlanId,
    sessionMember,
    sessionRestored,
    setContextRailVisibility,
    setCurrentMemberId,
    setDialogDeleteItem,
    setDialogState,
    setStopPlaceResolution,
    shouldRedirectUnauthenticatedTripRoute,
    showAllPaths,
    sidebarCollapsed,
    stopPlaceResolution,
    suggestSelectedStop,
    supportsContextRail,
    t,
    tasks: scopedTripPlanRecords.tasks,
    toastDismissed,
    transferOwnerToAccountMember,
    toggleContextRailCollapsed: toggleSidebarCollapsed,
    toggleTaskStatus,
    trip,
    tripPlanError,
    createStopNote,
    updateExpense,
    updateSelectedStop,
    updateStopNote,
  });

  return <WorkspaceAppFrame {...frameProps} />;
}
