"use client";

import { useI18n } from "@/src/i18n/I18nProvider";
import {
  type TripApiClient,
} from "@/src/trip/api-client";
import { type PlaceResolver } from "@/src/trip/place-resolution";
import { type PlanningView } from "@/src/trip/workspace/planning-view";
import { useDailyBriefings } from "@/src/trip/workspace/use-daily-briefings";
import { useItineraryPathWorkspace } from "@/src/trip/workspace/use-itinerary-path-workspace";
import { useTripWorkspaceState } from "@/src/trip/workspace/use-trip-workspace-state";
import { useWorkspaceChrome } from "@/src/trip/workspace/use-workspace-chrome";
import {
  useWorkspacePhotoAlbums,
  useWorkspaceAccessContext,
  useWorkspaceApiClients,
  useWorkspaceBackendExpenseSummary,
  useWorkspaceCommands,
  useWorkspacePlanningContext,
  useWorkspaceSession,
  useEffectivePlaceResolver,
  useWorkspaceNavigationContext,
  useWorkspaceSelectedTripPlanState,
  useWorkspaceUiState,
} from "./hooks";
import { nextClientMutationId } from "@/src/trip/local-ids";
import { seedTrip } from "@/src/trip/seed";
import { WorkspaceAppFrame } from "./WorkspaceAppFrame";
import {
  buildWorkspaceFrameProps,
} from "./props";
import type { Trip } from "@/src/trip/types";
import type { SagittariusAccessMode, SagittariusPortalSection } from "./types";

interface SagittariusAppProps {
  initialView?: PlanningView;
  requireJoin?: boolean;
  dataSource?: "api" | "local";
  apiClient?: TripApiClient;
  placeResolver?: PlaceResolver;
  routeTripId?: string;
  initialJoinCode?: string;
  initialJoinToken?: string | null;
  accessMode?: SagittariusAccessMode;
  accountSuccessRedirectHref?: string;
  portalSection?: SagittariusPortalSection;
  initialMemberId?: string;
  initialTrip?: Trip;
}

export function SagittariusApp({
  initialView = "overview",
  requireJoin = false,
  dataSource = "local",
  apiClient,
  placeResolver,
  routeTripId,
  initialJoinCode,
  initialJoinToken,
  accessMode = "combined",
  accountSuccessRedirectHref,
  portalSection = "dashboard",
  initialMemberId,
  initialTrip = seedTrip,
}: SagittariusAppProps) {
  const { t } = useI18n();
  const {
    accountClient,
    apiBaseUrl,
    resolvedApiClient,
  } = useWorkspaceApiClients({ apiClient, dataSource });
  const {
    accountClaimState,
    currentMemberId,
    dialogDeleteItem,
    dialogState,
    isCockpitLoaded,
    isTripPlanBusy,
    joinInviteToken,
    selectedItemId,
    setAccountClaimState,
    setCurrentMemberId,
    setDialogDeleteItem,
    setDialogState,
    setIsCockpitLoaded,
    setIsTripPlanBusy,
    setJoinInviteToken,
    setSelectedItemId,
    setStopPlaceResolution,
    setTripPlanError,
    stopPlaceResolution,
    tripPlanError,
  } = useWorkspaceUiState({
    initialJoinToken,
    initialMemberId,
    initialTrip,
  });
  const {
    contextRailMounted,
    contextRailOpen,
    contextRailPreferredTab,
    dismissWorkspaceToast,
    setContextRailPreferredTab,
    setContextRailVisibility,
    sidebarCollapsed,
    toggleContextRail,
    toggleSidebarCollapsed,
    toastDismissed,
    toastDismissing,
  } = useWorkspaceChrome({ autoDismissToast: requireJoin });
  const [selectedTripPlanId, setSelectedTripPlanId] =
    useWorkspaceSelectedTripPlanState(initialTrip);
  const {
    commitTrip,
    latestTripRef,
    replaceApiTrip,
    resetTrip,
    setTripState,
    trip,
    updateApiTrip,
  } = useTripWorkspaceState(initialTrip, setSelectedItemId);
  const isDataSourceApiMode = dataSource === "api";
  const {
    accessError,
    accountSession,
    accountSessionLoaded,
    accountTripAccessDeniedRouteId,
    changeAccountSession,
    participantSession,
    sessionRestored,
    setAccessError,
    setParticipantSession,
  } = useWorkspaceSession({
    accountClient,
    initialTrip,
    isApiMode: isDataSourceApiMode,
    requireJoin,
    routeTripId,
    setCurrentMemberId,
    setSelectedTripPlanId,
    setTripState,
  });
  const {
    activePlanItems,
    changeDayPath,
    clearDayPath,
    dayPathOverrides,
    mainPlanItems,
    pathOptions,
    pathSelection,
    planItems,
    selectedTripPathId,
    showAllPaths,
    toggleShowAllPaths,
  } = useItineraryPathWorkspace(trip, selectedTripPlanId);

  const {
    currentView,
    navigateWorkspaceView,
    openExpensesWorkspace,
    replaceWorkspacePath,
    supportsContextRail,
  } = useWorkspaceNavigationContext({
    initialView,
    routeTripId,
    setContextRailVisibility,
    tripId: trip.id,
  });
  const effectivePlaceResolver = useEffectivePlaceResolver({
    apiClient: resolvedApiClient,
    participantSession,
    placeResolver,
    tripId: trip.id,
  });
  const {
    canAccessPanel,
    canCreateStopNote,
    canCreateSuggestion,
    canEdit,
    canEditBookings,
    canEditExpenses,
    canEditPhotoAlbums,
    canManagePeople,
    canManageTripPlans,
    canReviewSuggestions,
    canViewExpenses,
    currentMember,
    isAccountTripAccessPending,
    isApiMode,
    isTripLoading,
    sessionMember,
    shouldRedirectUnauthenticatedTripRoute,
  } = useWorkspaceAccessContext({
    accessError,
    accessMode,
    accountSession,
    accountSessionLoaded,
    accountTripAccessDeniedRouteId,
    currentMemberId,
    dataSource,
    isCockpitLoaded,
    participantSession,
    requireJoin,
    routeTripId,
    sessionRestored,
    trip,
  });
  const {
    replaceDailyBriefings,
    resetDailyBriefings,
    saveDailyBriefingOverrides,
    visibleDailyBriefings,
  } = useDailyBriefings({
    apiClient: resolvedApiClient,
    isApiMode,
    participantSession,
    trip,
  });
  const {
    backendExpenseSummary,
    refreshBackendExpenseSummary,
    resetBackendExpenseSummary,
    setBackendExpenseSummary,
  } = useWorkspaceBackendExpenseSummary({
    apiClient: resolvedApiClient,
    canViewExpenses,
    currentView,
    isApiMode,
    isCockpitLoaded,
    participantSession,
    selectedTripPlanId,
    setAccessError,
    setParticipantSession,
    trip,
  });
  const {
    createPhotoAlbum,
    deletePhotoAlbum,
    updatePhotoAlbum,
  } = useWorkspacePhotoAlbums({
    apiClient: resolvedApiClient,
    canEditPhotoAlbums,
    commitTrip,
    currentMemberId: currentMember.id,
    isApiMode,
    latestTripRef,
    participantSession,
    replaceApiTrip,
    setTripState,
    trip,
  });

  const {
    createItineraryNote,
    createStopNote,
    createTask,
    createTripPlan,
    deleteStopNote,
    expenseSummary,
    itineraryView,
    mainItineraryView,
    renameTripPlan,
    replaceCockpitFromApi,
    reviewSuggestion,
    scopedSuggestions,
    scopedTripForRecords,
    scopedTripPlanRecords,
    selectTripPlan,
    selectedDay,
    selectedItem,
    selectedItemIdForView,
    setStopNotes,
    setMainTripPlan,
    setTasks,
    stopNotes,
    suggestSelectedStop,
    tasks,
    toggleTaskStatus,
    updateStopNote,
    updateTripPlanStatus,
  } = useWorkspacePlanningContext({
    activePlanItems,
    backendExpenseSummary,
    canCreateStopNote,
    canCreateSuggestion,
    canReviewSuggestions,
    canEdit,
    canManageTripPlans,
    commitTrip,
    currentMember,
    initialTrip,
    isApiMode,
    latestTripRef,
    mainPlanItems,
    participantSession,
    planItems,
    replaceDailyBriefings,
    resetBackendExpenseSummary,
    resetDailyBriefings,
    resolvedApiClient,
    selectedItemId,
    selectedTripPlanId,
    sessionRestored,
    setAccessError,
    setContextRailPreferredTab,
    setIsCockpitLoaded,
    setIsTripPlanBusy,
    setParticipantSession,
    setSelectedItemId,
    setSelectedTripPlanId,
    setTripPlanError,
    setTripState,
    trip,
    tripPlanErrorMessage: t.itinerary.tripPlans.error,
    updateApiTrip,
  });

  const {
    addStop,
    addSubActivity,
    applyPendingItineraryImport,
    authenticateParticipant,
    changeBookingDocQuickFields,
    changeBookingDocType,
    changeMemberAccessStatus,
    changeMemberPassword,
    changeMemberRole,
    claimCurrentMemberToAccount,
    clearPendingItineraryImport,
    createBookingDoc,
    createExpense,
    createItineraryBookingDraft,
    createMember,
    createStop,
    deleteBookingDoc,
    deleteExpense,
    deleteSelectedStop,
    deleteStop,
    duplicateExpenseAsEstimate,
    editItem,
    importItineraryError,
    leaveParticipantSession,
    moveItemToPath,
    openItemDetails,
    pendingItineraryImport,
    promoteFoodRecommendation,
    recordPaybackReminder,
    replaceTripFromJoin,
    resetMemberClaim,
    resolveMissingMapCoordinates,
    rotateJoinInviteToken,
    saveItineraryBookingTicket,
    saveTripSettings,
    selectItem,
    transferOwnerToAccountMember,
    unlinkBookingFromItineraryItem,
    updateBookingDoc,
    updateExpense,
    updateItineraryItemInline,
    updateSelectedStop,
  } = useWorkspaceCommands({
    canEdit,
    canEditBookings,
    canEditExpenses,
    canManagePeople,
    canSaveItineraryErrorMessage: t.itinerary.saveError,
    accountClient,
    accountSession,
    activeMemberId: currentMember.id,
    commitTrip,
    currentMemberId,
    dialogState,
    effectivePlaceResolver,
    initialTrip,
    isApiMode,
    latestTripRef,
    nextClientMutationId,
    pathOptions,
    pathSelection,
    planItems,
    participantSession,
    refreshBackendExpenseSummary,
    replaceApiTrip,
    replaceCockpitFromApi,
    replaceWorkspacePath,
    resetTrip,
    resolvedApiClient,
    routeTripId,
    selectedDay,
    selectedItemId,
    selectedTripPlanId,
    setAccessError,
    setAccountClaimState,
    setBackendExpenseSummary,
    setContextRailPreferredTab,
    setContextRailVisibility,
    setCurrentMemberId,
    setDialogDeleteItem,
    setDialogState,
    setIsCockpitLoaded,
    setJoinInviteToken,
    setParticipantSession,
    setSelectedItemId,
    setStopNotes,
    setStopPlaceResolution,
    setTasks,
    setTripPlanError,
    stopNotes,
    tasks,
    trip,
    tripPlanErrorMessage: t.itinerary.tripPlans.error,
    updateApiTrip,
  });

  const frameProps = buildWorkspaceFrameProps({
    accessError,
    accessMode,
    accountClaimState,
    accountClient,
    accountSession,
    accountSessionLoaded,
    accountSuccessRedirectHref,
    activePlanItems,
    apiBaseUrl,
    applyPendingItineraryImport,
    authenticateParticipant,
    bookingDocs: scopedTripPlanRecords.bookingDocs,
    canAccessPanel,
    canCreateStopNote,
    canCreateSuggestion,
    canEdit,
    canEditBookings,
    canEditExpenses,
    canEditPhotoAlbums,
    canManagePeople,
    canReviewSuggestions,
    changeBookingDocQuickFields,
    changeBookingDocType,
    claimCurrentMemberToAccount,
    clearPendingItineraryImport,
    contextRailMounted,
    contextRailOpen,
    contextRailPreferredTab,
    createBookingDoc,
    createExpense,
    createItineraryNote,
    createStop,
    currentMember,
    currentView,
    dailyBriefings: visibleDailyBriefings,
    dayPathOverrides,
    deleteExpense,
    deleteSelectedStop,
    deleteStop,
    deleteStopNote,
    dialogDeleteItem,
    dialogState,
    dismissWorkspaceToast,
    editItem,
    expenseSummary,
    effectivePlaceResolver,
    importItineraryError,
    initialJoinCode,
    initialJoinToken,
    itineraryView,
    isAccountTripAccessPending,
    isApiMode,
    isToastDismissing: toastDismissing,
    isTripLoading,
    isTripPlanBusy,
    joinInviteToken,
    leaveParticipantSession,
    mainItineraryView,
    mainPlanItems,
    navigateWorkspaceView,
    onAddBookingForItem: createItineraryBookingDraft,
    onAddStop: addStop,
    onAddSubActivity: addSubActivity,
    onChangeDayPath: changeDayPath,
    onChangeMemberAccessStatus: changeMemberAccessStatus,
    onChangeMemberPassword: changeMemberPassword,
    onChangeMemberRole: changeMemberRole,
    onChangeTripPlan: selectTripPlan,
    onChangeTripPlanStatus: updateTripPlanStatus,
    onClearDayPath: clearDayPath,
    onCreateExpense: createExpense,
    onCreateMember: createMember,
    onCreatePhotoAlbum: createPhotoAlbum,
    onCreateTask: createTask,
    onCreateTripPlan: createTripPlan,
    onDeleteBookingDoc: deleteBookingDoc,
    onDeleteExpense: deleteExpense,
    onDeleteItem: deleteStop,
    onDeletePhotoAlbum: deletePhotoAlbum,
    onDuplicateExpenseAsEstimate: duplicateExpenseAsEstimate,
    onEditItem: editItem,
    onMoveItemToPath: moveItemToPath,
    onOpenExpenses: openExpensesWorkspace,
    onOpenItemDetails: openItemDetails,
    onRecordPaybackReminder: recordPaybackReminder,
    onRenameTripPlan: renameTripPlan,
    onResetMemberClaim: resetMemberClaim,
    onSaveDailyBriefingOverrides: saveDailyBriefingOverrides,
    onSaveItineraryBookingTicket: saveItineraryBookingTicket,
    onSaveTripSettings: saveTripSettings,
    onSelectItem: selectItem,
    onSetMainTripPlan: setMainTripPlan,
    onToggleContextRail: toggleContextRail,
    onToggleShowAllPaths: toggleShowAllPaths,
    onToggleTaskStatus: toggleTaskStatus,
    onUnlinkBookingForItem: unlinkBookingFromItineraryItem,
    onUpdateBookingDoc: updateBookingDoc,
    onUpdateExpense: updateExpense,
    onUpdateItemInline: updateItineraryItemInline,
    onUpdatePhotoAlbum: updatePhotoAlbum,
    onAccountSessionChange: changeAccountSession,
    onCockpitLoaded: replaceCockpitFromApi,
    pendingItineraryImport,
    pathOptions,
    photoAlbumLinks: trip.photoAlbumLinks ?? [],
    planItems,
    portalSection,
    promoteFoodRecommendation,
    participantSession,
    replaceTripFromJoin,
    requireJoin,
    resolvedApiClient,
    resolveMissingMapCoordinates,
    reviewSuggestion,
    rotateJoinInviteToken,
    routeTripId,
    saveDailyBriefingOverrides,
    scopedSuggestions,
    scopedTripForRecords,
    scopedTripPlanRecords,
    selectedDay,
    selectedItem,
    selectedItemIdForView,
    selectedTripPathId,
    selectedTripPlanId,
    sessionMember,
    sessionRestored,
    setContextRailVisibility,
    setCurrentMemberId,
    setDialogDeleteItem,
    setDialogState,
    setStopPlaceResolution,
    shouldRedirectUnauthenticatedTripRoute,
    showAllPaths,
    sidebarCollapsed,
    stopPlaceResolution,
    suggestSelectedStop,
    supportsContextRail,
    t,
    tasks: scopedTripPlanRecords.tasks,
    toastDismissed,
    transferOwnerToAccountMember,
    toggleContextRailCollapsed: toggleSidebarCollapsed,
    toggleTaskStatus,
    trip,
    tripPlanError,
    createStopNote,
    updateExpense,
    updateSelectedStop,
    updateStopNote,
  });

  return <WorkspaceAppFrame {...frameProps} />;
}
