import type {
  BuildWorkspaceViewsPropsInput,
  WorkspaceViewsProps,
} from "./workspace-view-props.types";

type WorkspacePageViewProps = Pick<
  WorkspaceViewsProps,
  "bookingsProps" | "expensesProps" | "membersProps" | "photosProps" | "settingsProps"
>;

export function buildWorkspacePageViewProps({
  apiBaseUrl,
  bookingDocs,
  canCreateExpenses,
  canEditBookings,
  canEditExpenses,
  canEditPhotoAlbums,
  canManagePeople,
  currentMember,
  expenseSummary,
  joinInviteToken,
  onChangeMemberAccessStatus,
  onChangeMemberPassword,
  onChangeMemberRole,
  onChangeTripPlan,
  onCreateBookingDoc,
  onCreateExpense,
  onCreateMember,
  onCreatePhotoAlbum,
  onDeleteBookingDoc,
  onDeleteExpense,
  onDeletePhotoAlbum,
  onDuplicateExpenseAsEstimate,
  onRecordPaybackReminder,
  onResetMemberClaim,
  onRotateJoinInviteToken,
  onSaveTripSettings,
  onTransferOwnership,
  onUpdateBookingDoc,
  onUpdateExpense,
  onUpdatePhotoAlbum,
  photoAlbumLinks,
  scopedTripForRecords,
  selectedTripPlanId,
  tasks,
  trip,
}: BuildWorkspaceViewsPropsInput): WorkspacePageViewProps {
  return {
    settingsProps: {
      canEdit: canManagePeople,
      currentMember,
      trip,
      onSave: onSaveTripSettings,
    },
    membersProps: {
      trip,
      currentMember,
      canManagePeople,
      joinInviteToken,
      onChangeMemberAccessStatus,
      onChangeMemberPassword,
      onChangeMemberRole,
      onCreateMember,
      onRotateJoinInviteToken,
      onResetMemberClaim,
      onTransferOwnership,
    },
    bookingsProps: {
      trip: scopedTripForRecords,
      tasks,
      currentMember,
      bookingDocs,
      canEditBookings,
      onCreateBookingDoc,
      onUpdateBookingDoc,
      onDeleteBookingDoc,
    },
    photosProps: {
      trip,
      currentMember,
      photoAlbumLinks,
      canEditPhotoAlbums,
      onCreatePhotoAlbum,
      onUpdatePhotoAlbum,
      onDeletePhotoAlbum,
    },
    expensesProps: {
      trip: scopedTripForRecords,
      currentMember,
      expenseSummary,
      canCreateExpenses,
      canEditExpenses,
      selectedTripPlanId,
      workspaceTrip: trip,
      apiBaseUrl,
      onChangeTripPlan,
      onCreateExpense,
      onUpdateExpense,
      onDeleteExpense,
      onDuplicateExpenseAsEstimate,
      onRecordPaybackReminder,
    },
  };
}
