import type {
  WorkspaceCommands,
  WorkspaceCoreAppCommandProps,
} from "./workspace-core-command-props.types";

export function buildWorkspaceCoreAppCommandProps(
  commands: WorkspaceCommands,
): WorkspaceCoreAppCommandProps {
  return {
    applyPendingItineraryImport: commands.applyPendingItineraryImport,
    authenticateParticipant: commands.authenticateParticipant,
    changeBookingDocQuickFields: commands.changeBookingDocQuickFields,
    changeBookingDocType: commands.changeBookingDocType,
    claimCurrentMemberToAccount: commands.claimCurrentMemberToAccount,
    clearPendingItineraryImport: commands.clearPendingItineraryImport,
    createBookingDoc: commands.createBookingDoc,
    createExpense: commands.createExpense,
    createStop: commands.createStop,
    deleteExpense: commands.deleteExpense,
    deleteSelectedStop: commands.deleteSelectedStop,
    deleteStop: commands.deleteStop,
    editItem: commands.editItem,
    importItineraryError: commands.importItineraryError,
    leaveParticipantSession: commands.leaveParticipantSession,
    onAddBookingForItem: commands.createItineraryBookingDraft,
    onAddStop: commands.addStop,
    onAddSubActivity: commands.addSubActivity,
    onChangeMemberAccessStatus: commands.changeMemberAccessStatus,
    onChangeMemberPassword: commands.changeMemberPassword,
    onChangeMemberRole: commands.changeMemberRole,
    onCreateExpense: commands.createExpense,
    onCreateMember: commands.createMember,
    onDeleteBookingDoc: commands.deleteBookingDoc,
    onDeleteExpense: commands.deleteExpense,
    onDeleteItem: commands.deleteStop,
    onDuplicateExpenseAsEstimate: commands.duplicateExpenseAsEstimate,
    onEditItem: commands.editItem,
    onMoveItemToPath: commands.moveItemToPath,
    onOpenItemDetails: commands.openItemDetails,
    onRecordPaybackReminder: commands.recordPaybackReminder,
    onResetMemberClaim: commands.resetMemberClaim,
    onSaveItineraryBookingTicket: commands.saveItineraryBookingTicket,
    onSaveTripSettings: commands.saveTripSettings,
    onSelectItem: commands.selectItem,
    onUnlinkBookingForItem: commands.unlinkBookingFromItineraryItem,
    onUpdateBookingDoc: commands.updateBookingDoc,
    onUpdateExpense: commands.updateExpense,
    onUpdateItemInline: commands.updateItineraryItemInline,
    pendingItineraryImport: commands.pendingItineraryImport,
    promoteFoodRecommendation: commands.promoteFoodRecommendation,
    replaceTripFromJoin: commands.replaceTripFromJoin,
    resolveMissingMapCoordinates: commands.resolveMissingMapCoordinates,
    rotateJoinInviteToken: commands.rotateJoinInviteToken,
    transferOwnerToAccountMember: commands.transferOwnerToAccountMember,
    updateExpense: commands.updateExpense,
    updateSelectedStop: commands.updateSelectedStop,
  };
}
