import type {
  useWorkspaceCommands,
  useWorkspacePlanningContext,
  useWorkspaceSetupContext,
} from "../hooks";
import type { SagittariusAccessMode, SagittariusPortalSection } from "../types";
import { buildWorkspaceFrameProps } from "./workspace-frame-props";
import { buildWorkspaceCoreRecordProps } from "./workspace-core-record-props";

type WorkspaceSetupContext = ReturnType<typeof useWorkspaceSetupContext>;
type WorkspacePlanningContext = ReturnType<typeof useWorkspacePlanningContext>;
type WorkspaceCommands = ReturnType<typeof useWorkspaceCommands>;

interface BuildWorkspaceCoreFramePropsInput {
  accessMode: SagittariusAccessMode;
  accountSuccessRedirectHref?: string;
  commands: WorkspaceCommands;
  initialJoinCode?: string;
  initialJoinToken?: string | null;
  planning: WorkspacePlanningContext;
  portalSection: SagittariusPortalSection;
  requireJoin: boolean;
  routeTripId?: string;
  setup: WorkspaceSetupContext;
  t: Parameters<typeof buildWorkspaceFrameProps>[0]["t"];
}

export function buildWorkspaceCoreFrameProps({
  accessMode,
  accountSuccessRedirectHref,
  commands,
  initialJoinCode,
  initialJoinToken,
  planning,
  portalSection,
  requireJoin,
  routeTripId,
  setup,
  t,
}: BuildWorkspaceCoreFramePropsInput) {
  return buildWorkspaceFrameProps({
    ...buildWorkspaceCoreRecordProps(planning),
    accessError: setup.accessError,
    accessMode,
    accountClaimState: setup.accountClaimState,
    accountClient: setup.accountClient,
    accountSession: setup.accountSession,
    accountSessionLoaded: setup.accountSessionLoaded,
    accountSuccessRedirectHref,
    activePlanItems: setup.activePlanItems,
    apiBaseUrl: setup.apiBaseUrl,
    applyPendingItineraryImport: commands.applyPendingItineraryImport,
    authenticateParticipant: commands.authenticateParticipant,
    canAccessPanel: setup.canAccessPanel,
    canCreateStopNote: setup.canCreateStopNote,
    canCreateSuggestion: setup.canCreateSuggestion,
    canEdit: setup.canEdit,
    canEditBookings: setup.canEditBookings,
    canEditExpenses: setup.canEditExpenses,
    canEditPhotoAlbums: setup.canEditPhotoAlbums,
    canManagePeople: setup.canManagePeople,
    canReviewSuggestions: setup.canReviewSuggestions,
    changeBookingDocQuickFields: commands.changeBookingDocQuickFields,
    changeBookingDocType: commands.changeBookingDocType,
    claimCurrentMemberToAccount: commands.claimCurrentMemberToAccount,
    clearPendingItineraryImport: commands.clearPendingItineraryImport,
    contextRailMounted: setup.contextRailMounted,
    contextRailOpen: setup.contextRailOpen,
    contextRailPreferredTab: setup.contextRailPreferredTab,
    createBookingDoc: commands.createBookingDoc,
    createExpense: commands.createExpense,
    createItineraryNote: planning.createItineraryNote,
    createStop: commands.createStop,
    createStopNote: planning.createStopNote,
    currentMember: setup.currentMember,
    currentView: setup.currentView,
    dailyBriefings: setup.visibleDailyBriefings,
    dayPathOverrides: setup.dayPathOverrides,
    deleteExpense: commands.deleteExpense,
    deleteSelectedStop: commands.deleteSelectedStop,
    deleteStop: commands.deleteStop,
    deleteStopNote: planning.deleteStopNote,
    dialogDeleteItem: setup.dialogDeleteItem,
    dialogState: setup.dialogState,
    dismissWorkspaceToast: setup.dismissWorkspaceToast,
    editItem: commands.editItem,
    effectivePlaceResolver: setup.effectivePlaceResolver,
    importItineraryError: commands.importItineraryError,
    initialJoinCode,
    initialJoinToken,
    isAccountTripAccessPending: setup.isAccountTripAccessPending,
    isApiMode: setup.isApiMode,
    isToastDismissing: setup.toastDismissing,
    isTripLoading: setup.isTripLoading,
    isTripPlanBusy: setup.isTripPlanBusy,
    joinInviteToken: setup.joinInviteToken,
    leaveParticipantSession: commands.leaveParticipantSession,
    mainPlanItems: setup.mainPlanItems,
    navigateWorkspaceView: setup.navigateWorkspaceView,
    onAccountSessionChange: setup.changeAccountSession,
    onAddBookingForItem: commands.createItineraryBookingDraft,
    onAddStop: commands.addStop,
    onAddSubActivity: commands.addSubActivity,
    onChangeDayPath: setup.changeDayPath,
    onChangeMemberAccessStatus: commands.changeMemberAccessStatus,
    onChangeMemberPassword: commands.changeMemberPassword,
    onChangeMemberRole: commands.changeMemberRole,
    onChangeTripPlan: planning.selectTripPlan,
    onChangeTripPlanStatus: planning.updateTripPlanStatus,
    onClearDayPath: setup.clearDayPath,
    onCockpitLoaded: planning.replaceCockpitFromApi,
    onCreateExpense: commands.createExpense,
    onCreateMember: commands.createMember,
    onCreatePhotoAlbum: setup.createPhotoAlbum,
    onCreateTask: planning.createTask,
    onCreateTripPlan: planning.createTripPlan,
    onDeleteBookingDoc: commands.deleteBookingDoc,
    onDeleteExpense: commands.deleteExpense,
    onDeleteItem: commands.deleteStop,
    onDeletePhotoAlbum: setup.deletePhotoAlbum,
    onDuplicateExpenseAsEstimate: commands.duplicateExpenseAsEstimate,
    onEditItem: commands.editItem,
    onMoveItemToPath: commands.moveItemToPath,
    onOpenExpenses: setup.openExpensesWorkspace,
    onOpenItemDetails: commands.openItemDetails,
    onRecordPaybackReminder: commands.recordPaybackReminder,
    onRenameTripPlan: planning.renameTripPlan,
    onResetMemberClaim: commands.resetMemberClaim,
    onSaveDailyBriefingOverrides: setup.saveDailyBriefingOverrides,
    onSaveItineraryBookingTicket: commands.saveItineraryBookingTicket,
    onSaveTripSettings: commands.saveTripSettings,
    onSelectItem: commands.selectItem,
    onSetMainTripPlan: planning.setMainTripPlan,
    onToggleContextRail: setup.toggleContextRail,
    onToggleShowAllPaths: setup.toggleShowAllPaths,
    onToggleTaskStatus: planning.toggleTaskStatus,
    onUnlinkBookingForItem: commands.unlinkBookingFromItineraryItem,
    onUpdateBookingDoc: commands.updateBookingDoc,
    onUpdateExpense: commands.updateExpense,
    onUpdateItemInline: commands.updateItineraryItemInline,
    onUpdatePhotoAlbum: setup.updatePhotoAlbum,
    pathOptions: setup.pathOptions,
    pendingItineraryImport: commands.pendingItineraryImport,
    photoAlbumLinks: setup.trip.photoAlbumLinks ?? [],
    planItems: setup.planItems,
    portalSection,
    promoteFoodRecommendation: commands.promoteFoodRecommendation,
    participantSession: setup.participantSession,
    replaceTripFromJoin: commands.replaceTripFromJoin,
    requireJoin,
    resolvedApiClient: setup.resolvedApiClient,
    resolveMissingMapCoordinates: commands.resolveMissingMapCoordinates,
    reviewSuggestion: planning.reviewSuggestion,
    rotateJoinInviteToken: commands.rotateJoinInviteToken,
    routeTripId,
    saveDailyBriefingOverrides: setup.saveDailyBriefingOverrides,
    selectedTripPathId: setup.selectedTripPathId,
    selectedTripPlanId: setup.selectedTripPlanId,
    sessionMember: setup.sessionMember,
    sessionRestored: setup.sessionRestored,
    setContextRailVisibility: setup.setContextRailVisibility,
    setCurrentMemberId: setup.setCurrentMemberId,
    setDialogDeleteItem: setup.setDialogDeleteItem,
    setDialogState: setup.setDialogState,
    setStopPlaceResolution: setup.setStopPlaceResolution,
    shouldRedirectUnauthenticatedTripRoute:
      setup.shouldRedirectUnauthenticatedTripRoute,
    showAllPaths: setup.showAllPaths,
    sidebarCollapsed: setup.sidebarCollapsed,
    stopPlaceResolution: setup.stopPlaceResolution,
    suggestSelectedStop: planning.suggestSelectedStop,
    supportsContextRail: setup.supportsContextRail,
    t,
    toastDismissed: setup.toastDismissed,
    transferOwnerToAccountMember: commands.transferOwnerToAccountMember,
    toggleContextRailCollapsed: setup.toggleSidebarCollapsed,
    toggleTaskStatus: planning.toggleTaskStatus,
    trip: setup.trip,
    tripPlanError: setup.tripPlanError,
    updateExpense: commands.updateExpense,
    updateSelectedStop: commands.updateSelectedStop,
    updateStopNote: planning.updateStopNote,
  });
}
