import {
  defaultTripPlanId,
  tripPlanOptions,
} from "@/src/trip/trip-plans";
import type {
  BuildWorkspaceViewsPropsInput,
  WorkspaceViewsProps,
} from "./workspace-view-props.types";

type WorkspacePlanningViewProps = Pick<
  WorkspaceViewsProps,
  "itineraryProps" | "mapProps" | "overviewProps" | "timelineProps" | "detailPlannerProps"
>;

export function buildWorkspacePlanningViewProps({
  activePlanItems,
  bookingDocs,
  canEdit,
  contextRailOpen,
  currentMember,
  dailyBriefings,
  dayPathOverrides,
  expenseSummary,
  itineraryView,
  mainItineraryView,
  mainPlanItems,
  onAddBookingForItem,
  onAddNoteForItem,
  onAddStop,
  onAddSubActivity,
  onChangeDayPath,
  onChangeTripPlan,
  onChangeTripPlanStatus,
  onClearDayPath,
  onCreateTask,
  onCreateTripPlan,
  onDeleteItem,
  onEditItem,
  onMoveItemToPath,
  onOpenExpenses,
  onOpenItemDetails,
  onRenameTripPlan,
  onResolveMissingCoordinates,
  onSaveDailyBriefingOverrides,
  onSaveDayTitle,
  onSaveItineraryBookingTicket,
  onSelectItem,
  onSetMainTripPlan,
  onToggleContextRail,
  onToggleShowAllPaths,
  onToggleTaskStatus,
  onUnlinkBookingForItem,
  onUpdateItemInline,
  pathOptions,
  planItems,
  scopedSuggestions,
  scopedTripForRecords,
  selectedItemIdForView,
  selectedTripPlanId,
  showAllPaths,
  tasks,
  trip,
  tripPlanError,
  isTripPlanBusy,
}: BuildWorkspaceViewsPropsInput): WorkspacePlanningViewProps {
  return {
    overviewProps: {
      trip: scopedTripForRecords,
      currentMemberId: currentMember.id,
      expenseSummary,
      items: planItems,
      itineraryView,
      suggestions: scopedSuggestions,
      tasks,
      dailyBriefings,
      onOpenExpenses,
      onCreateTask,
      onSaveDailyBriefingOverrides,
      onToggleTaskStatus,
    },
    itineraryProps: {
      canRestructure: canEdit,
      endDate: trip.endDate,
      graphItems: activePlanItems,
      items: planItems,
      dailyBriefings,
      itineraryView,
      pathOptions,
      tripPlans: tripPlanOptions(trip),
      selectedTripPlanId,
      mainTripPlanId: defaultTripPlanId(trip),
      onChangeTripPlan,
      onSetMainTripPlan,
      onChangeTripPlanStatus,
      onCreateTripPlan,
      onRenameTripPlan,
      onSaveDayTitle,
      tripPlanError,
      isTripPlanBusy,
      role: currentMember.role,
      startDate: trip.startDate,
      selectedItemId: selectedItemIdForView,
      dayPathOverrides,
      showAllPaths,
      tripName: trip.name,
      bookingDocs,
      onAddBookingForItem,
      onSaveBookingForItem: onSaveItineraryBookingTicket,
      onUnlinkBookingForItem,
      onAddStop,
      onAddSubActivity,
      onAddNoteForItem,
      onOpenItemDetails,
      onSelectItem,
      onMoveItemToPath,
      onUpdateItemInline,
      onEditItem,
      onDeleteItem,
      onChangeDayPath,
      onClearDayPath,
      onToggleShowAllPaths,
    },
    mapProps: {
      countries: trip.countries ?? [],
      destinationLabel: trip.destinationLabel,
      endDate: trip.endDate,
      items: mainPlanItems,
      itineraryView: mainItineraryView,
      startDate: trip.startDate,
      tripName: trip.name,
      onResolveMissingCoordinates,
    },
    timelineProps: {
      contextRailOpen,
      endDate: trip.endDate,
      items: planItems,
      itineraryView,
      selectedItemId: selectedItemIdForView,
      startDate: trip.startDate,
      tripName: trip.name,
      onSelectItem,
      onToggleContextRail,
    },
    detailPlannerProps: {
      tableProps: {
        items: planItems,
        startDate: trip.startDate,
        endDate: trip.endDate,
        tripPlans: tripPlanOptions(trip),
        selectedTripPlanId,
        mainTripPlanId: defaultTripPlanId(trip),
        tripPlanError,
        isTripPlanBusy,
        role: currentMember.role,
        selectedItemId: selectedItemIdForView,
        tripName: trip.name,
        onAddStop,
        onOpenItemDetails,
        onSelectItem,
        onChangeTripPlan,
        onChangeTripPlanStatus,
        onSetMainTripPlan,
        onCreateTripPlan,
        onRenameTripPlan,
      },
      waypoints: trip.waypoints ?? [],
    },
  };
}
